module FTPBlock.Wire.Generated.Ftp_block_data

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LT = LowParse.TacLib
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPBY = LowParse.PulseParse.Bytes
module PPVD = LowParse.PulseParse.VLData
module PPAR = LowParse.PulseParse.Array
module PPVCL = LowParse.PulseParse.VCList
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPDER = LowParse.Pulse.DER
module PPLS = LowParse.PulseParse.List
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse


inline_for_extraction noextract let min_len = 0
inline_for_extraction noextract let max_len = 65535
noextract type ftp_block_data = LP.parse_bounded_seq_vlbytes_t 0 65535

inline_for_extraction noextract let ftp_block_data_parser_kind = LP.strong_parser_kind 2 65537 None

noextract val ftp_block_data_parser: LP.parser ftp_block_data_parser_kind ftp_block_data

noextract val ftp_block_data_serializer: LP.serializer ftp_block_data_parser

noextract let ftp_block_data_bytesize (x:ftp_block_data) : GTot nat = Seq.length (LP.serialize ftp_block_data_serializer x)

noextract val ftp_block_data_bytesize_eq (x:ftp_block_data) : Lemma (ftp_block_data_bytesize x == Seq.length (LP.serialize ftp_block_data_serializer x))

val ftp_block_data_validator: LPS.validator ftp_block_data_parser

val ftp_block_data_jumper: LPS.jumper ftp_block_data_parser

let ftp_block_data_lowtype = PPBY.lvec FStar.UInt8.t

noextract let ftp_block_data_mid = Seq.seq FStar.UInt8.t

let ftp_block_data_vmatch : ftp_block_data_lowtype -> ftp_block_data_mid -> Pulse.Lib.Core.slprop = LSeqB.vmatch_copy_seqbytes

noextract let ftp_block_data_conv : ftp_block_data_mid -> GTot (FStar.Pervasives.Native.option ftp_block_data) = LSeqB.seq_vlbytes_conv 0 65535

val read_ftp_block_data : PPB.copyful_parse ftp_block_data_vmatch ftp_block_data_parser ftp_block_data_conv

val free_ftp_block_data : PPB.free_t ftp_block_data_vmatch

val write_ftp_block_data : PPB.l2r_safe_writer ftp_block_data_vmatch ftp_block_data_serializer ftp_block_data_conv

val size_ftp_block_data : PPB.l2r_safe_size ftp_block_data_vmatch ftp_block_data_serializer ftp_block_data_conv

val ftp_block_data_bytesize_eqn (x: ftp_block_data) : Lemma (ftp_block_data_bytesize x == 2 + Seq.length x) [SMTPat (ftp_block_data_bytesize x)]

