module FTPBlock.Wire.Generated.Ftp_block_data

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LT = LowParse.TacLib
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBY = LowParse.PulseParse.Bytes
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPVCL = LowParse.PulseParse.VCList
module PPDER = LowParse.Pulse.DER
module PPVD = LowParse.PulseParse.VLData
module PPLS = LowParse.PulseParse.List
module PPAR = LowParse.PulseParse.Array
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse

#reset-options "--using_facts_from '* -FStar.Tactics -FStar.Reflection -Pulse -PulseCore' --z3rlimit 16 --z3cliopt smt.arith.nl=false --max_fuel 2 --max_ifuel 2"

assume val fits_u64_squash : squash FStar.SizeT.fits_u64

noextract let ftp_block_data_parser = LP.parse_bounded_seq_vlbytes 0 65535

noextract let ftp_block_data_serializer = LP.serialize_bounded_seq_vlbytes 0 65535

let ftp_block_data_bytesize_eq x = ()

let ftp_block_data_validator = LSeqB.validate_bounded_seq_vlbytes 0 65535 (PPBI.leaf_read_bounded_integer_2 fits_u64_squash) fits_u64_squash

let ftp_block_data_jumper = LSeqB.jump_bounded_seq_vlbytes 0 65535 (PPB.serialized_of_leaf_reader (LP.serialize_bounded_integer (LP.log256' 65535)) (PPBI.leaf_read_bounded_integer_2 fits_u64_squash)) fits_u64_squash

let read_ftp_block_data = LSeqB.copyful_parse_bounded_seq_vlbytes 0 65535 (PPBI.leaf_read_bounded_integer_2 fits_u64_squash) fits_u64_squash

let free_ftp_block_data : PPB.free_t ftp_block_data_vmatch = fun x #v -> LSeqB.free_copy_seqbytes x #(Ghost.hide (Ghost.reveal v <: Seq.seq FStar.UInt8.t))

let write_ftp_block_data = LSeqB.l2r_safe_writer_bounded_seq_vlbytes 0 (LSeqB.mk_seq_sizet 0 fits_u64_squash) 65535 (LSeqB.mk_seq_sizet 65535 fits_u64_squash) 2sz fits_u64_squash

let size_ftp_block_data = LSeqB.l2r_safe_size_bounded_seq_vlbytes 0 (LSeqB.mk_seq_sizet 0 fits_u64_squash) 65535 (LSeqB.mk_seq_sizet 65535 fits_u64_squash) 2sz fits_u64_squash

let ftp_block_data_bytesize_eqn x = LP.length_serialize_bounded_seq_vlbytes 0 65535 x

