module FTPBlock.Wire.Generated.Ftp_block

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LT = LowParse.TacLib
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBY = LowParse.PulseParse.Bytes
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPVCL = LowParse.PulseParse.VCList
module PPDER = LowParse.Pulse.DER
module PPVD = LowParse.PulseParse.VLData
module PPLS = LowParse.PulseParse.List
module PPAR = LowParse.PulseParse.Array
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse


#reset-options "--using_facts_from '* -FStar.Tactics -FStar.Reflection -Pulse -PulseCore' --z3rlimit 16 --z3cliopt smt.arith.nl=false --max_fuel 2 --max_ifuel 2"

(* Type of field data*)
open FTPBlock.Wire.Generated.Ftp_block_data

let synth_ftp_block_recip_inverse () : Lemma (LP.synth_inverse synth_ftp_block_recip synth_ftp_block) = ()

let synth_ftp_block_injective () : Lemma (LP.synth_injective synth_ftp_block) =
  LP.synth_inverse_synth_injective synth_ftp_block_recip synth_ftp_block;
  synth_ftp_block_recip_inverse ()

let synth_ftp_block_inverse () : Lemma (LP.synth_inverse synth_ftp_block synth_ftp_block_recip) =
  assert_norm (LP.synth_inverse synth_ftp_block synth_ftp_block_recip)

let synth_ftp_block_recip_injective () : Lemma (LP.synth_injective synth_ftp_block_recip) =
  synth_ftp_block_recip_inverse ();
  LP.synth_inverse_synth_injective synth_ftp_block synth_ftp_block_recip

noextract let ftp_block'_parser : LP.parser _ ftp_block' = (LPI.parse_u8 `LP.nondep_then` ftp_block_data_parser)

noextract let ftp_block'_parser_kind = LP.get_parser_kind ftp_block'_parser

let ftp_block_parser =
  synth_ftp_block_injective ();
  assert_norm (ftp_block_parser_kind == ftp_block'_parser_kind);
  ftp_block'_parser `LP.parse_synth` synth_ftp_block

noextract let ftp_block'_serializer : LP.serializer ftp_block'_parser = (LPI.serialize_u8 `LP.serialize_nondep_then` ftp_block_data_serializer)

let ftp_block_serializer =
  [@inline_let] let _ = synth_ftp_block_injective () in
  [@inline_let] let _ = synth_ftp_block_inverse () in
  [@inline_let] let _ = assert_norm (ftp_block_parser_kind == ftp_block'_parser_kind) in
  LP.serialize_synth _ synth_ftp_block ftp_block'_serializer synth_ftp_block_recip ()

let ftp_block_bytesize_eq x = ()

inline_for_extraction let ftp_block'_validator : LPS.validator ftp_block'_parser = (LPPI.validate_u8 `PPC.validate_nondep_then` ftp_block_data_validator)

let ftp_block_validator =
  [@inline_let] let _ = synth_ftp_block_injective () in
  [@inline_let] let _ = assert_norm (ftp_block_parser_kind == ftp_block'_parser_kind) in
  LPC.validate_synth ftp_block'_validator synth_ftp_block

inline_for_extraction let ftp_block'_jumper : LPS.jumper ftp_block'_parser = (LPPI.jump_u8 `LPC.jump_nondep_then` ftp_block_data_jumper)

let ftp_block_jumper =
  [@inline_let] let _ = synth_ftp_block_injective () in
  [@inline_let] let _ = assert_norm (ftp_block_parser_kind == ftp_block'_parser_kind) in
  LPC.jump_synth ftp_block'_jumper synth_ftp_block

let read_ftp_block : PPB.copyful_parse ftp_block_vmatch ftp_block_parser ftp_block_conv =
  synth_ftp_block_injective ();
  assert_norm (ftp_block_parser_kind == ftp_block'_parser_kind);
  PPC.copyful_parse_synth (PPC.copyful_parse_pair LPPI.jump_u8 (PPB.copyful_parse_leaf (PPB.leaf_reader_of_serialized (LPPI.read_u8' ()))) () read_ftp_block_data) synth_ftp_block synth_ftp_block_recip

let free_ftp_block : PPB.free_t ftp_block_vmatch = fun x #v -> ((PPC.free_pair (PPB.free_leaf #U8.t) free_ftp_block_data)) x #v

let write_ftp_block : PPB.l2r_safe_writer ftp_block_vmatch ftp_block_serializer ftp_block_conv =
  synth_ftp_block_injective ();
  assert_norm (ftp_block_parser_kind == ftp_block'_parser_kind);
  PPC.l2r_safe_writer_synth (PPC.l2r_safe_writer_pair (PPB.l2r_safe_writer_leaf LPI.serialize_u8 1sz (LPPI.l2r_leaf_write_u8 ())) () write_ftp_block_data) synth_ftp_block synth_ftp_block_recip

let size_ftp_block : PPB.l2r_safe_size ftp_block_vmatch ftp_block_serializer ftp_block_conv =
  synth_ftp_block_injective ();
  PPC.l2r_safe_size_synth (PPC.l2r_safe_size_pair (PPB.l2r_safe_size_leaf LPI.serialize_u8 1sz) () size_ftp_block_data) synth_ftp_block synth_ftp_block_recip

let ftp_block_bytesize_eqn x =
  [@inline_let] let _ = synth_ftp_block_injective () in
  [@inline_let] let _ = synth_ftp_block_inverse () in
  [@inline_let] let _ = assert_norm (ftp_block_parser_kind == ftp_block'_parser_kind) in
  LP.serialize_synth_eq _ synth_ftp_block ftp_block'_serializer synth_ftp_block_recip () x;
LP.length_serialize_nondep_then LPI.serialize_u8 ftp_block_data_serializer x.descriptor x.data;
  (assert (FStar.Seq.length (LP.serialize LP.serialize_u8 (x.descriptor)) == 1));
  (ftp_block_data_bytesize_eq (x.data));
  assert(ftp_block_bytesize x == Seq.length (LP.serialize LPI.serialize_u8 x.descriptor) + Seq.length (LP.serialize ftp_block_data_serializer x.data))

inline_for_extraction noextract let accessor'_ftp_block_descriptor : PPB.accessor ftp_block'_parser LPI.parse_u8 _ = (PPC.accessor_then_fst (PPC.accessor_id ftp_block'_parser) LPPI.jump_u8 () ())

inline_for_extraction noextract let accessor'_ftp_block_data : PPB.accessor ftp_block'_parser ftp_block_data_parser _ = (PPC.accessor_then_snd (PPC.accessor_id ftp_block'_parser) LPPI.jump_u8 () ())

noextract let clens_ftp_block_ftp_block' : LowParse.CLens.clens ftp_block ftp_block' = synth_ftp_block_recip_inverse (); synth_ftp_block_recip_injective (); { LowParse.CLens.clens_cond = (fun _ -> True); LowParse.CLens.clens_get = synth_ftp_block_recip }

inline_for_extraction noextract let accessor_ftp_block_ftp_block' : PPB.accessor ftp_block_parser ftp_block'_parser clens_ftp_block_ftp_block' = synth_ftp_block_inverse (); synth_ftp_block_injective (); synth_ftp_block_recip_inverse (); PPC.accessor_synth_inv synth_ftp_block synth_ftp_block_recip

let accessor_ftp_block_descriptor = PPC.accessor_ext (PPC.accessor_compose accessor_ftp_block_ftp_block' accessor'_ftp_block_descriptor ()) clens_ftp_block_descriptor ()

let accessor_ftp_block_data = PPC.accessor_ext (PPC.accessor_compose accessor_ftp_block_ftp_block' accessor'_ftp_block_data ()) clens_ftp_block_data ()

