module FTPBlock.Wire.Generated.Ftp_block

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LT = LowParse.TacLib
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPBY = LowParse.PulseParse.Bytes
module PPVD = LowParse.PulseParse.VLData
module PPAR = LowParse.PulseParse.Array
module PPVCL = LowParse.PulseParse.VCList
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPDER = LowParse.Pulse.DER
module PPLS = LowParse.PulseParse.List
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse


(* Type of field data*)
include FTPBlock.Wire.Generated.Ftp_block_data

noextract type ftp_block = {
  descriptor : U8.t;
  data : ftp_block_data;
}

noextract type ftp_block' = (U8.t & ftp_block_data)

inline_for_extraction noextract let synth_ftp_block (x: ftp_block') : ftp_block =
  match x with (descriptor,data) -> {
    descriptor = descriptor;
    data = data;
  }

inline_for_extraction noextract let synth_ftp_block_recip (x: ftp_block) : ftp_block' = (x.descriptor,x.data)

inline_for_extraction noextract let ftp_block_parser_kind = LP.strong_parser_kind 3 65538 None

noextract val ftp_block_parser: LP.parser ftp_block_parser_kind ftp_block

noextract val ftp_block_serializer: LP.serializer ftp_block_parser

noextract let ftp_block_bytesize (x:ftp_block) : GTot nat = Seq.length (LP.serialize ftp_block_serializer x)

noextract val ftp_block_bytesize_eq (x:ftp_block) : Lemma (ftp_block_bytesize x == Seq.length (LP.serialize ftp_block_serializer x))

val ftp_block_validator: LPS.validator ftp_block_parser

val ftp_block_jumper: LPS.jumper ftp_block_parser

let ftp_block_lowtype = (U8.t & ftp_block_data_lowtype)

noextract let ftp_block_mid = (U8.t & ftp_block_data_mid)

let ftp_block_vmatch : ftp_block_lowtype -> ftp_block_mid -> Pulse.Lib.Core.slprop = (LPC.vmatch_pair (LPS.eq_as_slprop U8.t) ftp_block_data_vmatch)

noextract let ftp_block_conv : ftp_block_mid -> GTot (FStar.Pervasives.Native.option ftp_block) = PPC.synth_conv (PPC.pair_conv (PPB.leaf_conv U8.t) ftp_block_data_conv) synth_ftp_block

val read_ftp_block : PPB.copyful_parse ftp_block_vmatch ftp_block_parser ftp_block_conv

val free_ftp_block : PPB.free_t ftp_block_vmatch

val write_ftp_block : PPB.l2r_safe_writer ftp_block_vmatch ftp_block_serializer ftp_block_conv

val size_ftp_block : PPB.l2r_safe_size ftp_block_vmatch ftp_block_serializer ftp_block_conv

val ftp_block_bytesize_eqn (x: ftp_block) : Lemma (ftp_block_bytesize x == 1 + (ftp_block_data_bytesize (x.data))) [SMTPat (ftp_block_bytesize x)]

noextract let clens_ftp_block_descriptor : LowParse.CLens.clens ftp_block U8.t = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.descriptor);
}

val accessor_ftp_block_descriptor : PPB.accessor ftp_block_parser LPI.parse_u8 clens_ftp_block_descriptor

noextract let clens_ftp_block_data : LowParse.CLens.clens ftp_block ftp_block_data = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.data);
}

val accessor_ftp_block_data : PPB.accessor ftp_block_parser ftp_block_data_parser clens_ftp_block_data

