module Calc.Spec

(** State machine specification for calculator.

    The request/response datatypes are the ones generated by QuackyDucky from
    calc.qd.rfc (the Calc.Wire.Generated modules): a request is { op; operand }
    and a response is { tag; value }, where op/tag are the closed enums and the
    payloads are U32.t. The stack therefore holds U32.t values and the
    arithmetic is native 32-bit (wrapping) arithmetic, matching both the wire
    payload type and the imperative implementation's U32 stack. **)

open Calc.Wire.Generated.OpType
open Calc.Wire.Generated.Request
open Calc.Wire.Generated.RespType
open Calc.Wire.Generated.Response
module L = FStar.List.Tot
module U32 = FStar.UInt32

type calc_stack = list U32.t

let max_stack_size = 10

(** State transition function **)
val step (s:calc_stack) (req:request) : calc_stack & response

let step s req =
  match req.op with
  | Push ->
      if L.length s >= max_stack_size
      then (s, { tag = Error; value = 0ul })   // Stack overflow - return error
      else (req.operand :: s, { tag = Ok; value = 0ul })

  | Peek ->
      begin match s with
      | [] -> (s, { tag = Error; value = 0ul })          // Stack underflow
      | x :: _ -> (s, { tag = Result; value = x })
      end

  | Add ->
      begin match s with
      | x :: y :: rest -> (U32.add_mod x y :: rest, { tag = Ok; value = 0ul })   // 32-bit wrapping add
      | _ -> (s, { tag = Error; value = 0ul })           // Stack underflow
      end

  | Sub ->
      begin match s with
      | x :: y :: rest -> (U32.sub_mod y x :: rest, { tag = Ok; value = 0ul })   // 32-bit wrapping sub
      | _ -> (s, { tag = Error; value = 0ul })
      end

  | Mul ->
      begin match s with
      | x :: y :: rest -> (U32.mul_mod x y :: rest, { tag = Ok; value = 0ul })   // 32-bit wrapping mul
      | _ -> (s, { tag = Error; value = 0ul })
      end

  | Div ->
      begin match s with
      | x :: y :: rest ->
          if U32.v x = 0
          then (s, { tag = Error; value = 0ul })         // Division by zero
          else (U32.div y x :: rest, { tag = Ok; value = 0ul })
      | _ -> (s, { tag = Error; value = 0ul })
      end

(** Run multiple operations **)
let rec run (s:calc_stack) (reqs:list request)
  : Tot (calc_stack & list response) (decreases reqs) =
  match reqs with
  | [] -> (s, [])
  | req :: rest ->
      let (s', resp) = step s req in
      let (s'', resps) = run s' rest in
      (s'', resp :: resps)
