#ifndef TLS13_GENERATED_SHIMS_H
#define TLS13_GENERATED_SHIMS_H

/* Force-included while compiling KaRaMeL-generated C.  It only keeps
 * compatibility aliases for generated constants whose extracted names carry
 * the [_sz] suffix. */

#if defined(__has_include)
#if __has_include("TLS13_Impl_ConnectionState_Bounds.h")
#include "TLS13_Impl_ConnectionState_Bounds.h"
#endif
#endif

#define TLS13_Impl_ConnectionState_Bounds_max_hostname_len \
  TLS13_Impl_ConnectionState_Bounds_max_hostname_len_sz
#define TLS13_Impl_ConnectionState_Bounds_max_public_key_len \
  TLS13_Impl_ConnectionState_Bounds_max_public_key_len_sz
#define TLS13_Impl_ConnectionState_Bounds_max_cipher_suites \
  TLS13_Impl_ConnectionState_Bounds_max_cipher_suites_sz
#define TLS13_Impl_ConnectionState_Bounds_max_signature_schemes \
  TLS13_Impl_ConnectionState_Bounds_max_signature_schemes_sz
#define TLS13_Impl_ConnectionState_Bounds_max_client_hello_len \
  TLS13_Impl_ConnectionState_Bounds_max_client_hello_len_sz
#define TLS13_Impl_ConnectionState_Bounds_max_server_hello_len \
  TLS13_Impl_ConnectionState_Bounds_max_server_hello_len_sz
#define TLS13_Impl_ConnectionState_Bounds_max_handshake_flight_len \
  TLS13_Impl_ConnectionState_Bounds_max_handshake_flight_len_sz
#define TLS13_Impl_ConnectionState_Bounds_max_transcript_len \
  TLS13_Impl_ConnectionState_Bounds_max_transcript_len_sz
#define TLS13_Impl_ConnectionState_Bounds_max_certificate_verify_input_len \
  TLS13_Impl_ConnectionState_Bounds_max_certificate_verify_input_len_sz
#define TLS13_Impl_ConnectionState_Bounds_max_trust_anchors_len \
  TLS13_Impl_ConnectionState_Bounds_max_trust_anchors_len_sz
#define TLS13_Impl_ConnectionState_Bounds_max_pending_plaintext_len \
  TLS13_Impl_ConnectionState_Bounds_max_pending_plaintext_len_sz
#define TLS13_Impl_ConnectionState_Bounds_max_pending_raw_len \
  TLS13_Impl_ConnectionState_Bounds_max_pending_raw_len_sz

#endif
