/* 
  This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
  KreMLin invocation: C:\cygwin64\home\aseemr\ev1\kremlin\_build\src\Kremlin.native -skip-compilation -silent -warn-error -9-7-6@4-14-15+11-20 -add-include "kremlin/internal/compat.h" -ccopts -Wno-type-limits,-Wno-unused,-Wno-uninitialized -ccopts -DDEBUGFLAGS_DEBUG,-DDEBUGFLAGS_DEBUG_CDH,-DDEBUGFLAGS_DEBUG_EPOCHS,-DDEBUGFLAGS_DEBUG_FFI,-DDEBUGFLAGS_DEBUG_HS,-DDEBUGFLAGS_DEBUG_HSL,-DDEBUGFLAGS_DEBUG_KS,-DDEBUGFLAGS_DEBUG_NGO,-DDEBUGFLAGS_DEBUG_QUIC,-DDEBUGFLAGS_DEBUG_RECORD,-DDEBUGFLAGS_DEBUG_TLS,-DDEBUGFLAGS_DEBUG_AEP -fnoanonymous-unions -fparentheses -fno-shadow -fcurly-braces -drop DebugFlags -library EverCrypt,EverCrypt.* -no-prefix MITLS.Init -add-early-include "log_to_choice.h" -bundle EverCrypt,EverCrypt.\*[rename=EverCrypt] -bundle Vale.*,Hacl.*[rename=Unused1] -bundle LowParse.\*,LowParseWrappers[rename=LowParse] -bundle Format.\* -bundle FStar.\*,LowStar.\*,C,C.\*[rename=Mitls_Kremlib] -bundle Parsers.ClientHello=Parsers.\*,ParsersAux.\*[rename=Parsers] -bundle Spec.\* -bundle Test.\* -bundle Lib.*[rename=Hacl_Lib] -bundle TLSConstants=QD.TLS_protocolVersion,List.Helpers -bundle Hashing=Hashing.Spec,Hashing,Hashing.CRF,HMAC,HKDF,HMAC.UFCMA -bundle HandshakeLog,TLS.Handshake.Send[rename=HandshakeLog] -bundle TLS.Handshake=TLS.Handshake.\*,Old.HMAC.UFCMA,Old.Epochs,Old.KeySchedule[rename=Handshake] -bundle StatefulLHAE=AEAD_GCM,LHAEPlain,StatefulPlain -bundle StreamPlain+StreamAE=[rename=StreamAE] -bundle TLS.Curve25519+DHGroup+ECGroup+CommonDH=[rename=CommonDH] -bundle Content=DataStream -bundle Record+StAE=Transport,StreamDeltas[rename=Record] -bundle PMS=RSAKey,TLSPRF -bundle MITLS.Repr.*[rename=Reprs] -bundle Buffer.Utils,Crypto.Indexing,Crypto.Plain,Crypto.Symmetric.Bytes[rename=Crypto_Plain] -bundle Flags,Flag,TLSInfoFlags[rename=Flags] -bundle Model,Model.\*[rename=Unused] -bundle Token.UF1CMA,AEAD,AEAD.Pkg @dist/compact/Makefile.basic.rsp -tmpdir dist/compact/ -o libmitls.a
  F* version: 387c3a3f
  KreMLin version: 2f843633
 */

#include "HSL_Receive.h"

bool HSL_Receive_uu___is_F_none(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_none:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_s_Idle(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_s_Idle:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_c_wait_ServerHello(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_c_wait_ServerHello:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_c13_wait_Finished1(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_c13_wait_Finished1:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_s13_wait_Finished2(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_s13_wait_Finished2:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_s13_wait_EOED(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_s13_wait_EOED:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_c13_Complete(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_c13_Complete:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_c12_wait_ServerHelloDone(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_c12_wait_ServerHelloDone:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_cs12_wait_Finished(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_cs12_wait_Finished:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_c12_wait_NST(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_c12_wait_NST:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool HSL_Receive_uu___is_F_s12_wait_CCS1(HSL_Receive_in_progress_flt_t projectee)
{
  switch (projectee)
  {
    case HSL_Receive_F_s12_wait_CCS1:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

MITLS_Repr_const_slice HSL_Receive___proj__Mkstate__item__buf(HSL_Receive_state projectee)
{
  return projectee.buf;
}

uint32_t HSL_Receive___proj__Mkstate__item__f_begin(HSL_Receive_state projectee)
{
  return projectee.f_begin;
}

uint32_t HSL_Receive___proj__Mkstate__item__f_end(HSL_Receive_state projectee)
{
  return projectee.f_end;
}

uint32_t HSL_Receive___proj__Mkstate__item__from_idx(HSL_Receive_state projectee)
{
  return projectee.from_idx;
}

static HSL_Receive_state HSL_Receive_reset()
{
  return
    (
      (HSL_Receive_state){
        .buf = MITLS_Repr_of_slice(((LowParse_Slice_slice){ .base = NULL, .len = (uint32_t)0U })),
        .f_begin = (uint32_t)0U,
        .f_end = (uint32_t)0U,
        .from_idx = (uint32_t)0U
      }
    );
}

HSL_Receive_state HSL_Receive_create()
{
  return HSL_Receive_reset();
}

K___Parsers_Alert_alert_Prims_string
HSL_Receive_parsing_error =
  {
    .fst = {
      .level = Parsers_AlertLevel_Fatal,
      .description = Parsers_AlertDescription_Unexpected_message
    },
    .snd = ""
  };

K___Parsers_Alert_alert_Prims_string
HSL_Receive_unexpected_flight_error =
  {
    .fst = {
      .level = Parsers_AlertLevel_Fatal,
      .description = Parsers_AlertDescription_Unexpected_message
    },
    .snd = ""
  };

K___Parsers_Alert_alert_Prims_string
HSL_Receive_unexpected_end_index_error =
  {
    .fst = {
      .level = Parsers_AlertLevel_Fatal,
      .description = Parsers_AlertDescription_Unexpected_message
    },
    .snd = ""
  };

MITLS_Repr_repr
HSL_Receive___proj__Mkc13_wait_Finished1__item__ee_msg(
  MITLS_Repr_const_slice b,
  HSL_Receive_c13_wait_Finished1 projectee
)
{
  return projectee.ee_msg;
}

MITLS_Repr_repr
HSL_Receive___proj__Mkc13_wait_Finished1__item__cr_msg(
  MITLS_Repr_const_slice b,
  HSL_Receive_c13_wait_Finished1 projectee
)
{
  return projectee.cr_msg;
}

MITLS_Repr_repr
HSL_Receive___proj__Mkc13_wait_Finished1__item__c_msg(
  MITLS_Repr_const_slice b,
  HSL_Receive_c13_wait_Finished1 projectee
)
{
  return projectee.c_msg;
}

MITLS_Repr_repr
HSL_Receive___proj__Mkc13_wait_Finished1__item__cv_msg(
  MITLS_Repr_const_slice b,
  HSL_Receive_c13_wait_Finished1 projectee
)
{
  return projectee.cv_msg;
}

MITLS_Repr_repr
HSL_Receive___proj__Mkc13_wait_Finished1__item__fin_msg(
  MITLS_Repr_const_slice b,
  HSL_Receive_c13_wait_Finished1 projectee
)
{
  return projectee.fin_msg;
}

typedef struct FStar_Pervasives_Native_option__MITLS_Repr_repr_s
{
  FStar_Pervasives_Native_option__Prims_string_tags tag;
  MITLS_Repr_repr v;
}
FStar_Pervasives_Native_option__MITLS_Repr_repr;

typedef struct K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state_s
{
  FStar_Pervasives_Native_option__MITLS_Repr_repr fst;
  HSL_Receive_state snd;
}
K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state;

typedef struct
FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state_s
{
  FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Bytes_bytes_FStar_Bytes_bytes_tags
  tag;
  union {
    K___Parsers_Alert_alert_Prims_string case_Error;
    K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state case_Correct;
  }
  val;
}
FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state;

typedef struct
FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_FStar_Pervasives_Native_option_____s
{
  FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Bytes_bytes_FStar_Bytes_bytes_tags
  tag;
  union {
    K___Parsers_Alert_alert_Prims_string case_Error;
    FStar_Pervasives_Native_option____ case_Correct;
  }
  val;
}
FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_FStar_Pervasives_Native_option____;

static FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state
HSL_Receive_err_or_insufficient_data_____MITLS_Repr_repr(
  FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_FStar_Pervasives_Native_option____
  parse_result,
  HSL_Receive_state st
)
{
  if (parse_result.tag == FStar_Error_Error)
  {
    K___Parsers_Alert_alert_Prims_string e = parse_result.val.case_Error;
    return
      (
        (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
          .tag = FStar_Error_Error,
          .val = { .case_Error = e }
        }
      );
  }
  else if
  (
    parse_result.tag
    == FStar_Error_Correct
    && parse_result.val.case_Correct == FStar_Pervasives_Native_None
  )
  {
    HSL_Receive_state uu____0 = st;
    return
      (
        (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
          .tag = FStar_Error_Correct,
          .val = {
            .case_Correct = {
              .fst = { .tag = FStar_Pervasives_Native_None },
              .snd = {
                .buf = uu____0.buf,
                .f_begin = uu____0.f_begin,
                .f_end = uu____0.f_end,
                .from_idx = uu____0.from_idx
              }
            }
          }
        }
      );
  }
  else
  {
    KRML_HOST_EPRINTF("KreMLin abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

typedef struct K___FStar_Pervasives_Native_option_____HSL_Receive_state_s
{
  FStar_Pervasives_Native_option____ fst;
  HSL_Receive_state snd;
}
K___FStar_Pervasives_Native_option_____HSL_Receive_state;

typedef struct
FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option_____HSL_Receive_state_s
{
  FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Bytes_bytes_FStar_Bytes_bytes_tags
  tag;
  union {
    K___Parsers_Alert_alert_Prims_string case_Error;
    K___FStar_Pervasives_Native_option_____HSL_Receive_state case_Correct;
  }
  val;
}
FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option_____HSL_Receive_state;

FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state
HSL_Receive_receive_c13_wait_Finished1(
  HSL_Receive_state st,
  MITLS_Repr_const_slice b,
  uint32_t f_begin,
  uint32_t f_end
)
{
  FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option_____HSL_Receive_state
  r0 =
    {
      .tag = FStar_Error_Correct,
      .val = {
        .case_Correct = {
          .fst = FStar_Pervasives_Native_Some,
          .snd = { .buf = b, .f_begin = f_begin, .f_end = f_end, .from_idx = f_begin }
        }
      }
    };
  FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state
  r;
  if (r0.tag == FStar_Error_Error)
  {
    K___Parsers_Alert_alert_Prims_string e = r0.val.case_Error;
    r =
      (
        (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
          .tag = FStar_Error_Error,
          .val = { .case_Error = e }
        }
      );
  }
  else if
  (r0.tag == FStar_Error_Correct && r0.val.case_Correct.fst == FStar_Pervasives_Native_None)
  {
    HSL_Receive_state st11 = r0.val.case_Correct.snd;
    r =
      (
        (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
          .tag = FStar_Error_Correct,
          .val = { .case_Correct = { .fst = { .tag = FStar_Pervasives_Native_None }, .snd = st11 } }
        }
      );
  }
  else if
  (r0.tag == FStar_Error_Correct && r0.val.case_Correct.fst == FStar_Pervasives_Native_Some)
  {
    HSL_Receive_state st11 = r0.val.case_Correct.snd;
    LowParse_Slice_slice lp_b0 = MITLS_Repr_to_slice(b);
    uint32_t pos0 = Parsers_Handshake13_handshake13_validator(lp_b0, st11.from_idx);
    FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state
    r1;
    if (pos0 <= LOWPARSE_LOW_BASE_VALIDATOR_MAX_LENGTH)
    {
      Parsers_HandshakeType_handshakeType
      parsed_tag = Parsers_HandshakeType_handshakeType_reader(lp_b0, st11.from_idx);
      if
      (
        __eq__Parsers_HandshakeType_handshakeType(parsed_tag,
          Parsers_HandshakeType_Encrypted_extensions)
      )
      {
        MITLS_Repr_repr
        r10 =
          MITLS_Repr_mk_from_const_slice(b,
            st11.from_idx,
            pos0,
            (
              (LowParse_Spec_Base_parser_kind_){
                .parser_kind_low = (krml_checked_int_t)4,
                .parser_kind_high = {
                  .tag = FStar_Pervasives_Native_Some,
                  .v = (krml_checked_int_t)16777219
                },
                .parser_kind_subkind = {
                  .tag = FStar_Pervasives_Native_Some,
                  .v = LowParse_Spec_Base_ParserStrong
                },
                .parser_kind_metadata = { .tag = FStar_Pervasives_Native_None }
              }
            ));
        r1 =
          (
            (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
              .tag = FStar_Error_Correct,
              .val = {
                .case_Correct = {
                  .fst = { .tag = FStar_Pervasives_Native_Some, .v = r10 },
                  .snd = {
                    .buf = st11.buf,
                    .f_begin = st11.f_begin,
                    .f_end = st11.f_end,
                    .from_idx = pos0
                  }
                }
              }
            }
          );
      }
      else
      {
        r1 =
          (
            (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
              .tag = FStar_Error_Error,
              .val = { .case_Error = HSL_Receive_unexpected_flight_error }
            }
          );
      }
    }
    else if (pos0 == LOWPARSE_LOW_BASE_VALIDATOR_ERROR_NOT_ENOUGH_DATA)
    {
      r1 =
        HSL_Receive_err_or_insufficient_data_____MITLS_Repr_repr((
            (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_FStar_Pervasives_Native_option____){
              .tag = FStar_Error_Correct,
              .val = { .case_Correct = FStar_Pervasives_Native_None }
            }
          ),
          st11);
    }
    else
    {
      r1 =
        (
          (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
            .tag = FStar_Error_Error,
            .val = { .case_Error = HSL_Receive_parsing_error }
          }
        );
    }
    if (r1.tag == FStar_Error_Error)
    {
      K___Parsers_Alert_alert_Prims_string e = r1.val.case_Error;
      r =
        (
          (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
            .tag = FStar_Error_Error,
            .val = { .case_Error = e }
          }
        );
    }
    else if
    (r1.tag == FStar_Error_Correct && r1.val.case_Correct.fst.tag == FStar_Pervasives_Native_None)
    {
      HSL_Receive_state st12 = r1.val.case_Correct.snd;
      r =
        (
          (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
            .tag = FStar_Error_Correct,
            .val = {
              .case_Correct = { .fst = { .tag = FStar_Pervasives_Native_None }, .snd = st12 }
            }
          }
        );
    }
    else if
    (r1.tag == FStar_Error_Correct && r1.val.case_Correct.fst.tag == FStar_Pervasives_Native_Some)
    {
      HSL_Receive_state st12 = r1.val.case_Correct.snd;
      MITLS_Repr_repr x1 = r1.val.case_Correct.fst.v;
      LowParse_Slice_slice lp_b1 = MITLS_Repr_to_slice(b);
      uint32_t pos1 = Parsers_Handshake13_handshake13_validator(lp_b1, st12.from_idx);
      FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state
      r2;
      if (pos1 <= LOWPARSE_LOW_BASE_VALIDATOR_MAX_LENGTH)
      {
        Parsers_HandshakeType_handshakeType
        parsed_tag = Parsers_HandshakeType_handshakeType_reader(lp_b1, st12.from_idx);
        if
        (
          __eq__Parsers_HandshakeType_handshakeType(parsed_tag,
            Parsers_HandshakeType_Certificate_request)
        )
        {
          MITLS_Repr_repr
          r20 =
            MITLS_Repr_mk_from_const_slice(b,
              st12.from_idx,
              pos1,
              (
                (LowParse_Spec_Base_parser_kind_){
                  .parser_kind_low = (krml_checked_int_t)4,
                  .parser_kind_high = {
                    .tag = FStar_Pervasives_Native_Some,
                    .v = (krml_checked_int_t)16777219
                  },
                  .parser_kind_subkind = {
                    .tag = FStar_Pervasives_Native_Some,
                    .v = LowParse_Spec_Base_ParserStrong
                  },
                  .parser_kind_metadata = { .tag = FStar_Pervasives_Native_None }
                }
              ));
          r2 =
            (
              (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                .tag = FStar_Error_Correct,
                .val = {
                  .case_Correct = {
                    .fst = { .tag = FStar_Pervasives_Native_Some, .v = r20 },
                    .snd = {
                      .buf = st12.buf,
                      .f_begin = st12.f_begin,
                      .f_end = st12.f_end,
                      .from_idx = pos1
                    }
                  }
                }
              }
            );
        }
        else
        {
          r2 =
            (
              (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                .tag = FStar_Error_Error,
                .val = { .case_Error = HSL_Receive_unexpected_flight_error }
              }
            );
        }
      }
      else if (pos1 == LOWPARSE_LOW_BASE_VALIDATOR_ERROR_NOT_ENOUGH_DATA)
      {
        r2 =
          HSL_Receive_err_or_insufficient_data_____MITLS_Repr_repr((
              (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_FStar_Pervasives_Native_option____){
                .tag = FStar_Error_Correct,
                .val = { .case_Correct = FStar_Pervasives_Native_None }
              }
            ),
            st12);
      }
      else
      {
        r2 =
          (
            (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
              .tag = FStar_Error_Error,
              .val = { .case_Error = HSL_Receive_parsing_error }
            }
          );
      }
      if (r2.tag == FStar_Error_Error)
      {
        K___Parsers_Alert_alert_Prims_string e = r2.val.case_Error;
        r =
          (
            (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
              .tag = FStar_Error_Error,
              .val = { .case_Error = e }
            }
          );
      }
      else if
      (r2.tag == FStar_Error_Correct && r2.val.case_Correct.fst.tag == FStar_Pervasives_Native_None)
      {
        HSL_Receive_state st13 = r2.val.case_Correct.snd;
        r =
          (
            (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
              .tag = FStar_Error_Correct,
              .val = {
                .case_Correct = { .fst = { .tag = FStar_Pervasives_Native_None }, .snd = st13 }
              }
            }
          );
      }
      else if
      (r2.tag == FStar_Error_Correct && r2.val.case_Correct.fst.tag == FStar_Pervasives_Native_Some)
      {
        HSL_Receive_state st13 = r2.val.case_Correct.snd;
        MITLS_Repr_repr x2 = r2.val.case_Correct.fst.v;
        LowParse_Slice_slice lp_b2 = MITLS_Repr_to_slice(b);
        uint32_t pos2 = Parsers_Handshake13_handshake13_validator(lp_b2, st13.from_idx);
        FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state
        r3;
        if (pos2 <= LOWPARSE_LOW_BASE_VALIDATOR_MAX_LENGTH)
        {
          Parsers_HandshakeType_handshakeType
          parsed_tag = Parsers_HandshakeType_handshakeType_reader(lp_b2, st13.from_idx);
          if
          (__eq__Parsers_HandshakeType_handshakeType(parsed_tag, Parsers_HandshakeType_Certificate))
          {
            MITLS_Repr_repr
            r30 =
              MITLS_Repr_mk_from_const_slice(b,
                st13.from_idx,
                pos2,
                (
                  (LowParse_Spec_Base_parser_kind_){
                    .parser_kind_low = (krml_checked_int_t)4,
                    .parser_kind_high = {
                      .tag = FStar_Pervasives_Native_Some,
                      .v = (krml_checked_int_t)16777219
                    },
                    .parser_kind_subkind = {
                      .tag = FStar_Pervasives_Native_Some,
                      .v = LowParse_Spec_Base_ParserStrong
                    },
                    .parser_kind_metadata = { .tag = FStar_Pervasives_Native_None }
                  }
                ));
            r3 =
              (
                (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                  .tag = FStar_Error_Correct,
                  .val = {
                    .case_Correct = {
                      .fst = { .tag = FStar_Pervasives_Native_Some, .v = r30 },
                      .snd = {
                        .buf = st13.buf,
                        .f_begin = st13.f_begin,
                        .f_end = st13.f_end,
                        .from_idx = pos2
                      }
                    }
                  }
                }
              );
          }
          else
          {
            r3 =
              (
                (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                  .tag = FStar_Error_Error,
                  .val = { .case_Error = HSL_Receive_unexpected_flight_error }
                }
              );
          }
        }
        else if (pos2 == LOWPARSE_LOW_BASE_VALIDATOR_ERROR_NOT_ENOUGH_DATA)
        {
          r3 =
            HSL_Receive_err_or_insufficient_data_____MITLS_Repr_repr((
                (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_FStar_Pervasives_Native_option____){
                  .tag = FStar_Error_Correct,
                  .val = { .case_Correct = FStar_Pervasives_Native_None }
                }
              ),
              st13);
        }
        else
        {
          r3 =
            (
              (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                .tag = FStar_Error_Error,
                .val = { .case_Error = HSL_Receive_parsing_error }
              }
            );
        }
        if (r3.tag == FStar_Error_Error)
        {
          K___Parsers_Alert_alert_Prims_string e = r3.val.case_Error;
          r =
            (
              (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
                .tag = FStar_Error_Error,
                .val = { .case_Error = e }
              }
            );
        }
        else if
        (
          r3.tag
          == FStar_Error_Correct
          && r3.val.case_Correct.fst.tag == FStar_Pervasives_Native_None
        )
        {
          HSL_Receive_state st14 = r3.val.case_Correct.snd;
          r =
            (
              (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
                .tag = FStar_Error_Correct,
                .val = {
                  .case_Correct = { .fst = { .tag = FStar_Pervasives_Native_None }, .snd = st14 }
                }
              }
            );
        }
        else if
        (
          r3.tag
          == FStar_Error_Correct
          && r3.val.case_Correct.fst.tag == FStar_Pervasives_Native_Some
        )
        {
          HSL_Receive_state st14 = r3.val.case_Correct.snd;
          MITLS_Repr_repr x3 = r3.val.case_Correct.fst.v;
          LowParse_Slice_slice lp_b3 = MITLS_Repr_to_slice(b);
          uint32_t pos3 = Parsers_Handshake13_handshake13_validator(lp_b3, st14.from_idx);
          FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state
          r4;
          if (pos3 <= LOWPARSE_LOW_BASE_VALIDATOR_MAX_LENGTH)
          {
            Parsers_HandshakeType_handshakeType
            parsed_tag = Parsers_HandshakeType_handshakeType_reader(lp_b3, st14.from_idx);
            if
            (
              __eq__Parsers_HandshakeType_handshakeType(parsed_tag,
                Parsers_HandshakeType_Certificate_verify)
            )
            {
              MITLS_Repr_repr
              r40 =
                MITLS_Repr_mk_from_const_slice(b,
                  st14.from_idx,
                  pos3,
                  (
                    (LowParse_Spec_Base_parser_kind_){
                      .parser_kind_low = (krml_checked_int_t)4,
                      .parser_kind_high = {
                        .tag = FStar_Pervasives_Native_Some,
                        .v = (krml_checked_int_t)16777219
                      },
                      .parser_kind_subkind = {
                        .tag = FStar_Pervasives_Native_Some,
                        .v = LowParse_Spec_Base_ParserStrong
                      },
                      .parser_kind_metadata = { .tag = FStar_Pervasives_Native_None }
                    }
                  ));
              r4 =
                (
                  (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                    .tag = FStar_Error_Correct,
                    .val = {
                      .case_Correct = {
                        .fst = { .tag = FStar_Pervasives_Native_Some, .v = r40 },
                        .snd = {
                          .buf = st14.buf,
                          .f_begin = st14.f_begin,
                          .f_end = st14.f_end,
                          .from_idx = pos3
                        }
                      }
                    }
                  }
                );
            }
            else
            {
              r4 =
                (
                  (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                    .tag = FStar_Error_Error,
                    .val = { .case_Error = HSL_Receive_unexpected_flight_error }
                  }
                );
            }
          }
          else if (pos3 == LOWPARSE_LOW_BASE_VALIDATOR_ERROR_NOT_ENOUGH_DATA)
          {
            r4 =
              HSL_Receive_err_or_insufficient_data_____MITLS_Repr_repr((
                  (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_FStar_Pervasives_Native_option____){
                    .tag = FStar_Error_Correct,
                    .val = { .case_Correct = FStar_Pervasives_Native_None }
                  }
                ),
                st14);
          }
          else
          {
            r4 =
              (
                (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                  .tag = FStar_Error_Error,
                  .val = { .case_Error = HSL_Receive_parsing_error }
                }
              );
          }
          if (r4.tag == FStar_Error_Error)
          {
            K___Parsers_Alert_alert_Prims_string e = r4.val.case_Error;
            r =
              (
                (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
                  .tag = FStar_Error_Error,
                  .val = { .case_Error = e }
                }
              );
          }
          else if
          (
            r4.tag
            == FStar_Error_Correct
            && r4.val.case_Correct.fst.tag == FStar_Pervasives_Native_None
          )
          {
            HSL_Receive_state st15 = r4.val.case_Correct.snd;
            r =
              (
                (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
                  .tag = FStar_Error_Correct,
                  .val = {
                    .case_Correct = { .fst = { .tag = FStar_Pervasives_Native_None }, .snd = st15 }
                  }
                }
              );
          }
          else if
          (
            r4.tag
            == FStar_Error_Correct
            && r4.val.case_Correct.fst.tag == FStar_Pervasives_Native_Some
          )
          {
            HSL_Receive_state st15 = r4.val.case_Correct.snd;
            MITLS_Repr_repr x4 = r4.val.case_Correct.fst.v;
            LowParse_Slice_slice lp_b = MITLS_Repr_to_slice(b);
            uint32_t pos = Parsers_Handshake13_handshake13_validator(lp_b, st15.from_idx);
            FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state
            r5;
            if (pos <= LOWPARSE_LOW_BASE_VALIDATOR_MAX_LENGTH)
            {
              Parsers_HandshakeType_handshakeType
              parsed_tag = Parsers_HandshakeType_handshakeType_reader(lp_b, st15.from_idx);
              if
              (
                __eq__Parsers_HandshakeType_handshakeType(parsed_tag,
                  Parsers_HandshakeType_Finished)
              )
              {
                MITLS_Repr_repr
                r50 =
                  MITLS_Repr_mk_from_const_slice(b,
                    st15.from_idx,
                    pos,
                    (
                      (LowParse_Spec_Base_parser_kind_){
                        .parser_kind_low = (krml_checked_int_t)4,
                        .parser_kind_high = {
                          .tag = FStar_Pervasives_Native_Some,
                          .v = (krml_checked_int_t)16777219
                        },
                        .parser_kind_subkind = {
                          .tag = FStar_Pervasives_Native_Some,
                          .v = LowParse_Spec_Base_ParserStrong
                        },
                        .parser_kind_metadata = { .tag = FStar_Pervasives_Native_None }
                      }
                    ));
                r5 =
                  (
                    (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                      .tag = FStar_Error_Correct,
                      .val = {
                        .case_Correct = {
                          .fst = { .tag = FStar_Pervasives_Native_Some, .v = r50 },
                          .snd = {
                            .buf = st15.buf,
                            .f_begin = st15.f_begin,
                            .f_end = st15.f_end,
                            .from_idx = pos
                          }
                        }
                      }
                    }
                  );
              }
              else
              {
                r5 =
                  (
                    (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                      .tag = FStar_Error_Error,
                      .val = { .case_Error = HSL_Receive_unexpected_flight_error }
                    }
                  );
              }
            }
            else if (pos == LOWPARSE_LOW_BASE_VALIDATOR_ERROR_NOT_ENOUGH_DATA)
            {
              r5 =
                HSL_Receive_err_or_insufficient_data_____MITLS_Repr_repr((
                    (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_FStar_Pervasives_Native_option____){
                      .tag = FStar_Error_Correct,
                      .val = { .case_Correct = FStar_Pervasives_Native_None }
                    }
                  ),
                  st15);
            }
            else
            {
              r5 =
                (
                  (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__MITLS_Repr_repr_HSL_Receive_state){
                    .tag = FStar_Error_Error,
                    .val = { .case_Error = HSL_Receive_parsing_error }
                  }
                );
            }
            if (r5.tag == FStar_Error_Error)
            {
              K___Parsers_Alert_alert_Prims_string e = r5.val.case_Error;
              r =
                (
                  (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
                    .tag = FStar_Error_Error,
                    .val = { .case_Error = e }
                  }
                );
            }
            else if
            (
              r5.tag
              == FStar_Error_Correct
              && r5.val.case_Correct.fst.tag == FStar_Pervasives_Native_None
            )
            {
              HSL_Receive_state st16 = r5.val.case_Correct.snd;
              r =
                (
                  (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
                    .tag = FStar_Error_Correct,
                    .val = {
                      .case_Correct = {
                        .fst = { .tag = FStar_Pervasives_Native_None },
                        .snd = st16
                      }
                    }
                  }
                );
            }
            else if
            (
              r5.tag
              == FStar_Error_Correct
              && r5.val.case_Correct.fst.tag == FStar_Pervasives_Native_Some
            )
            {
              HSL_Receive_state st16 = r5.val.case_Correct.snd;
              MITLS_Repr_repr x5 = r5.val.case_Correct.fst.v;
              r =
                (
                  (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
                    .tag = FStar_Error_Correct,
                    .val = {
                      .case_Correct = {
                        .fst = {
                          .tag = FStar_Pervasives_Native_Some,
                          .v = {
                            .ee_msg = x1, .cr_msg = x2, .c_msg = x3, .cv_msg = x4, .fin_msg = x5
                          }
                        },
                        .snd = st16
                      }
                    }
                  }
                );
            }
            else
            {
              r =
                KRML_EABORT(FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state,
                  "unreachable (pattern matches are exhaustive in F*)");
            }
          }
          else
          {
            r =
              KRML_EABORT(FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state,
                "unreachable (pattern matches are exhaustive in F*)");
          }
        }
        else
        {
          r =
            KRML_EABORT(FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state,
              "unreachable (pattern matches are exhaustive in F*)");
        }
      }
      else
      {
        r =
          KRML_EABORT(FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state,
            "unreachable (pattern matches are exhaustive in F*)");
      }
    }
    else
    {
      r =
        KRML_EABORT(FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state,
          "unreachable (pattern matches are exhaustive in F*)");
    }
  }
  else
  {
    r =
      KRML_EABORT(FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state,
        "unreachable (pattern matches are exhaustive in F*)");
  }
  if (r.tag == FStar_Error_Error)
  {
    return r;
  }
  else if
  (r.tag == FStar_Error_Correct && r.val.case_Correct.fst.tag == FStar_Pervasives_Native_None)
  {
    return r;
  }
  else if
  (r.tag == FStar_Error_Correct && r.val.case_Correct.fst.tag == FStar_Pervasives_Native_Some)
  {
    HSL_Receive_state rst = r.val.case_Correct.snd;
    HSL_Receive_c13_wait_Finished1 flt = r.val.case_Correct.fst.v;
    if (rst.from_idx != f_end)
    {
      return
        (
          (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
            .tag = FStar_Error_Error,
            .val = { .case_Error = HSL_Receive_unexpected_end_index_error }
          }
        );
    }
    else
    {
      return
        (
          (FStar_Error_optResult__K___Parsers_Alert_alert_Prims_string_K___FStar_Pervasives_Native_option__HSL_Receive_c13_wait_Finished1_HSL_Receive_state){
            .tag = FStar_Error_Correct,
            .val = {
              .case_Correct = {
                .fst = { .tag = FStar_Pervasives_Native_Some, .v = flt },
                .snd = HSL_Receive_reset()
              }
            }
          }
        );
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KreMLin abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

