PREFIX=Format.AutoGen_
QD_HOME?=../../../quackyducky

SOURCES=$(wildcard *.rfc)
TARGETS=$(addsuffix .fst,$(addprefix $(PREFIX),$(SOURCES:%.rfc=%)))

all: $(TARGETS)

$(PREFIX)%.fst: %.rfc
	$(QD_HOME)/qd -prefix $(PREFIX) $^

.PHONY: all
