PREFIX=Format.AutoGen_
QD_HOME?=../../../quackyducky

SOURCES=$(wildcard *.rfc)
TARGETS=$(addsuffix .fst,$(addprefix $(PREFIX),$(SOURCES:%.rfc=%)))

all:
	$(QD_HOME)/qd -prefix $(PREFIX) $(SOURCES)

clean:
	rm -rf $(PREFIX)*.fst*

.PHONY: all clean
