module MiTLS.Parsers.Ticket.Low
open MiTLS
include MiTLS.Parsers.Boolean
include MiTLS.Parsers.ProtocolVersion
include MiTLS.Parsers.CipherSuite
include MiTLS.Parsers.TicketContents12
include MiTLS.Parsers.TicketContents13
include MiTLS.Parsers.TicketContents
include MiTLS.Parsers.TicketContents12_master_secret.Low
