module TLSConstantsAux1

(* Start Hacks *)
// assume val empty_bytes : FStar.Bytes.lbytes 0
(* End Hacks *)
open FStar.String
open FStar.Seq
open FStar.Date
open FStar.Bytes
open FStar.Error
open TLSError
//open CoreCrypto // avoid?!

(* Protocol version negotiated values *)

// NOTE: SSL 3.0 is supported but with no security guarantees

(* BEGIN code generated by QuackyDucky *)

type protocolVersion' =
  | SSL_3p0
  | TLS_1p0
  | TLS_1p1
  | TLS_1p2
  | TLS_1p3
  | Unknown_protocolVersion of (v:UInt16.t{v <> 768us /\ v <> 769us /\ v <> 770us /\ v <> 771us /\ v <> 772us})

type protocolVersion = v:protocolVersion'{~(Unknown_protocolVersion? v)}

(* END code generated by QuackyDucky *)
