module NSL.Sample.DY.Invariant

(**
  The direct history interpretation of canonical NSL histories satisfies the
  genuine DY* core trace invariant [TI.trace_invariant #P.nsl_protocol_invariants].

  The auxiliary [model_invariant] additionally tracks only the endpoint- and
  network-local facts needed to discharge the DY* per-entry obligations
  ([SetState] state predicate, [MsgSent] publishability, [Event] event
  predicate); it contains no protocol transition relation.  Preservation is
  proved for every arbitrary [S.system_effect].
 *)

module E = Common.Protocol.Labelled
module S = Common.Protocol.System
module I = Common.Protocol.Interpretation
module SM = NSL.Sample.StateMachine
module D = NSL.Sample.DY.Terms
module P = NSL.Sample.DY.Profile
module M = NSL.Sample.DY.Model
module B = DY.Core.Bytes
module BT = DY.Core.Bytes.Type
module L = DY.Core.Label
module LT = DY.Core.Label.Type
module T = DY.Core.Trace.Type
module TB = DY.Core.Trace.Base
module TI = DY.Core.Trace.Invariant
module List = FStar.List.Tot
module Seq = FStar.Seq
module U8 = FStar.UInt8

open NSL.Sample.Types
open NSL.Sample.Wire

(*** Section 1: knowability predicates ***)

let publishable (trace:TB.trace) (value:BT.bytes) : prop =
  B.is_publishable #P.nsl_crypto_invariants trace value

/// A protocol nonce is a shared secret between the two roles: it must be
/// knowable by both endpoint state labels, i.e. knowable at the session label.
let both_knowable (trace:TB.trace) (value:BT.bytes) : prop =
  B.is_knowable_by #P.nsl_crypto_invariants D.session_label trace value

let knowable (who:E.endpoint_id) (trace:TB.trace) (value:BT.bytes) : prop =
  B.is_knowable_by #P.nsl_crypto_invariants (D.role_label who) trace value

(*** Section 2: shadow-field and network validity ***)

/// The endpoint long-term PKE key was generated by the initial trace.
let secret_key_recorded
  (who:E.endpoint_id)
  (trace:TB.trace)
  (value:BT.bytes)
  : prop
  =
  (who == SM.initiator_endpoint /\
    value == D.key_term 0 /\
    TB.entry_at trace 0
      (T.RandGen
        D.initiator_key_usage
        (D.role_label SM.initiator_endpoint)
        D.key_length)) \/
  (who == SM.responder_endpoint /\
    value == D.key_term 2 /\
    TB.entry_at trace 2
      (T.RandGen
        D.responder_key_usage
        (D.role_label SM.responder_endpoint)
        D.key_length))

/// The pending PKE randomness is a fresh PkeNonce generated at the endpoint.
let randomness_recorded
  (who:E.endpoint_id)
  (trace:TB.trace)
  (value:BT.bytes)
  : prop
  =
  exists (position:nat).
    value == D.encryption_nonce_term position /\
    TB.entry_at trace position
      (T.RandGen
        D.encryption_nonce_usage
        (D.role_label who)
        D.encryption_nonce_length)

let optional_both_knowable
  (trace:TB.trace)
  (value:option BT.bytes)
  : prop
  =
  match value with
  | None -> True
  | Some term -> both_knowable trace term

let optional_publishable
  (trace:TB.trace)
  (value:option BT.bytes)
  : prop
  =
  match value with
  | None -> True
  | Some term -> publishable trace term

let optional_randomness_recorded
  (who:E.endpoint_id)
  (trace:TB.trace)
  (value:option BT.bytes)
  : prop
  =
  match value with
  | None -> True
  | Some term -> randomness_recorded who trace term

/// Every byte component of a symbolic plaintext (nonces and identities) is
/// knowable by both roles.  Identities are public literals; nonces are shared
/// secrets.  This is exactly what makes the plaintext knowable to whichever
/// endpoint stores or decrypts it, and makes its label flow into the recipient
/// key and PKE nonce for the honest-encryption obligation.
let plaintext_material_valid
  (trace:TB.trace)
  (value:M.symbolic_plaintext)
  : prop
  =
  match value with
  | M.SymbolicPlaintext1 initiator_nonce initiator ->
    both_knowable trace initiator_nonce /\
    both_knowable trace initiator
  | M.SymbolicPlaintext2 initiator_nonce responder_nonce responder ->
    both_knowable trace initiator_nonce /\
    both_knowable trace responder_nonce /\
    both_knowable trace responder
  | M.SymbolicPlaintext3 responder_nonce ->
    both_knowable trace responder_nonce

let optional_plaintext_material_valid
  (trace:TB.trace)
  (value:option M.symbolic_plaintext)
  : prop
  =
  match value with
  | None -> True
  | Some plaintext -> plaintext_material_valid trace plaintext

/// A network packet / last-received message carries a publishable ciphertext
/// (it may be sent on the wire) and, when honest, a plaintext whose nonces are
/// knowable to both roles (they may be extracted upon acceptance).
let message_material_valid
  (trace:TB.trace)
  (value:M.symbolic_message)
  : prop
  =
  match value with
  | M.SymbolicEncrypted ciphertext plaintext ->
    publishable trace ciphertext /\
    optional_plaintext_material_valid trace plaintext

let optional_message_valid
  (trace:TB.trace)
  (value:option M.symbolic_message)
  : prop
  =
  match value with
  | None -> True
  | Some message -> message_material_valid trace message

let shadow_valid
  (who:E.endpoint_id)
  (trace:TB.trace)
  (shadow:M.endpoint_shadow)
  : prop
  =
  secret_key_recorded who trace shadow.M.secret_key /\
  optional_both_knowable trace shadow.M.pending_nonce /\
  optional_randomness_recorded who trace shadow.M.pending_randomness /\
  optional_both_knowable trace shadow.M.initiator_nonce /\
  optional_both_knowable trace shadow.M.responder_nonce /\
  optional_publishable trace shadow.M.pending_ciphertext /\
  optional_plaintext_material_valid trace shadow.M.pending_plaintext /\
  optional_message_valid trace shadow.M.last_received

let rec network_valid
  (trace:TB.trace)
  (network:list M.network_shadow)
  : prop
  =
  match network with
  | [] -> True
  | packet :: tail ->
    message_material_valid trace packet.M.symbolic_packet /\
    TB.entry_at trace packet.M.send_position
      (T.MsgSent (M.flatten_message packet.M.symbolic_packet)) /\
    network_valid trace tail

let model_invariant (state:M.model) : prop =
  TI.trace_invariant #P.nsl_protocol_invariants state.M.dy_trace /\
  (exists (initiator responder:M.endpoint_shadow).
    state.M.endpoints == [ initiator; responder ] /\
    shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
    shadow_valid SM.responder_endpoint state.M.dy_trace responder) /\
  network_valid state.M.dy_trace state.M.network

(*** Section 3: core crypto and label lemmas ***)

#push-options "--fuel 1 --ifuel 1 --z3rlimit 10"
let trace_invariant_snoc
  (trace:TB.trace)
  (entry:TB.trace_entry)
  : Lemma
      (requires
        TI.trace_invariant #P.nsl_protocol_invariants trace /\
        TI.trace_entry_invariant
          #P.nsl_protocol_invariants trace entry)
      (ensures
        TI.trace_invariant #P.nsl_protocol_invariants
          (TB.append_entry trace entry))
  =
  reveal_opaque
    (`%TI.trace_invariant)
    (TI.trace_invariant #P.nsl_protocol_invariants)
#pop-options

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
let join_flows_left (trace:TB.trace) (left right:LT.label)
  : Lemma (ensures L.can_flow trace (L.join left right) left)
  =
  L.intro_can_flow trace (L.join left right) left
    (fun later -> L.is_corrupt_join later left right)

let join_flows_right (trace:TB.trace) (left right:LT.label)
  : Lemma (ensures L.can_flow trace (L.join left right) right)
  =
  L.intro_can_flow trace (L.join left right) right
    (fun later -> L.is_corrupt_join later left right)

/// The session label flows to each of the two protocol endpoint labels.
let session_flows
  (trace:TB.trace)
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  : Lemma (L.can_flow trace D.session_label (D.role_label who))
  =
  if who = SM.initiator_endpoint
  then join_flows_left trace (D.role_label 0) (D.role_label 1)
  else join_flows_right trace (D.role_label 0) (D.role_label 1)
#pop-options

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
let rand_usage_and_label
  (trace:TB.trace)
  (usage:BT.usage)
  (label:LT.label)
  (length:nat{length <> 0})
  (position:nat)
  : Lemma
      (requires
        TB.entry_at trace position
          (T.RandGen usage label length))
      (ensures
        B.get_usage #P.nsl_crypto_usages trace
          (BT.Rand length position) == usage /\
        B.get_label #P.nsl_crypto_usages trace
          (BT.Rand length position) == label /\
        B.has_usage #P.nsl_crypto_usages trace
          (BT.Rand length position) usage)
  =
  reveal_opaque (`%B.get_usage) (B.get_usage #P.nsl_crypto_usages);
  reveal_opaque (`%B.get_label) (B.get_label #P.nsl_crypto_usages);
  reveal_opaque (`%B.has_usage) (B.has_usage #P.nsl_crypto_usages)

let rand_bytes_invariant
  (trace:TB.trace)
  (usage:BT.usage)
  (label:LT.label)
  (length:nat{length <> 0})
  (position:nat)
  : Lemma
      (requires
        TB.entry_at trace position
          (T.RandGen usage label length))
      (ensures
        B.bytes_invariant #P.nsl_crypto_invariants trace
          (BT.Rand length position))
  =
  reveal_opaque
    (`%B.bytes_invariant)
    (B.bytes_invariant #P.nsl_crypto_invariants);
  introduce
    exists (u:BT.usage) (l:LT.label).
      TB.entry_at trace position (T.RandGen u l length)
  with usage label and ()
#pop-options

#push-options "--fuel 2 --ifuel 1 --z3rlimit 10"
let publishable_later
  (trace0 trace1:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires
        publishable trace0 value /\
        trace0 `TB.grows` trace1)
      (ensures publishable trace1 value)
  =
  B.bytes_invariant_later
    #P.nsl_crypto_invariants trace0 trace1 value;
  B.bytes_invariant_implies_well_formed
    #P.nsl_crypto_invariants trace0 value;
  B.get_label_later #P.nsl_crypto_usages trace0 trace1 value;
  L.can_flow_later trace0 trace1
    (B.get_label #P.nsl_crypto_usages trace0 value)
    L.public

let both_knowable_later
  (trace0 trace1:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires
        both_knowable trace0 value /\
        trace0 `TB.grows` trace1)
      (ensures both_knowable trace1 value)
  =
  B.bytes_invariant_later
    #P.nsl_crypto_invariants trace0 trace1 value;
  B.bytes_invariant_implies_well_formed
    #P.nsl_crypto_invariants trace0 value;
  B.get_label_later #P.nsl_crypto_usages trace0 trace1 value;
  L.can_flow_later trace0 trace1
    (B.get_label #P.nsl_crypto_usages trace0 value)
    D.session_label

let publishable_implies_both_knowable
  (trace:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires publishable trace value)
      (ensures both_knowable trace value)
  =
  L.public_is_top trace D.session_label;
  L.can_flow_transitive trace
    (B.get_label #P.nsl_crypto_usages trace value)
    L.public
    D.session_label

let public_is_knowable
  (who:E.endpoint_id)
  (trace:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires publishable trace value)
      (ensures knowable who trace value)
  =
  L.public_is_top trace (D.role_label who);
  L.can_flow_transitive trace
    (B.get_label #P.nsl_crypto_usages trace value)
    L.public
    (D.role_label who)

let both_knowable_implies_knowable
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (trace:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires both_knowable trace value)
      (ensures knowable who trace value)
  =
  session_flows trace who;
  L.can_flow_transitive trace
    (B.get_label #P.nsl_crypto_usages trace value)
    D.session_label
    (D.role_label who)
#pop-options

(*** Section 4: field facts and monotonicity (later) ***)

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
let secret_key_facts
  (who:E.endpoint_id)
  (trace:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires secret_key_recorded who trace value)
      (ensures
        B.bytes_invariant #P.nsl_crypto_invariants trace value /\
        B.get_label #P.nsl_crypto_usages trace value == D.role_label who /\
        B.has_usage #P.nsl_crypto_usages trace value (D.key_usage who) /\
        BT.PkeKey? (D.key_usage who))
  =
  eliminate
    (who == SM.initiator_endpoint /\
      value == D.key_term 0 /\
      TB.entry_at trace 0
        (T.RandGen D.initiator_key_usage (D.role_label SM.initiator_endpoint) D.key_length)) \/
    (who == SM.responder_endpoint /\
      value == D.key_term 2 /\
      TB.entry_at trace 2
        (T.RandGen D.responder_key_usage (D.role_label SM.responder_endpoint) D.key_length))
  returns
    B.bytes_invariant #P.nsl_crypto_invariants trace value /\
    B.get_label #P.nsl_crypto_usages trace value == D.role_label who /\
    B.has_usage #P.nsl_crypto_usages trace value (D.key_usage who) /\
    BT.PkeKey? (D.key_usage who)
  with _.
    (rand_bytes_invariant trace D.initiator_key_usage (D.role_label 0) D.key_length 0;
     rand_usage_and_label trace D.initiator_key_usage (D.role_label 0) D.key_length 0)
  and _.
    (rand_bytes_invariant trace D.responder_key_usage (D.role_label 1) D.key_length 2;
     rand_usage_and_label trace D.responder_key_usage (D.role_label 1) D.key_length 2)

let randomness_facts
  (who:E.endpoint_id)
  (trace:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires randomness_recorded who trace value)
      (ensures
        B.bytes_invariant #P.nsl_crypto_invariants trace value /\
        B.get_label #P.nsl_crypto_usages trace value == D.role_label who /\
        B.has_usage #P.nsl_crypto_usages trace value BT.PkeNonce)
  =
  eliminate
    exists (position:nat).
      value == D.encryption_nonce_term position /\
      TB.entry_at trace position
        (T.RandGen D.encryption_nonce_usage (D.role_label who) D.encryption_nonce_length)
  returns
    B.bytes_invariant #P.nsl_crypto_invariants trace value /\
    B.get_label #P.nsl_crypto_usages trace value == D.role_label who /\
    B.has_usage #P.nsl_crypto_usages trace value BT.PkeNonce
  with _.
    (rand_bytes_invariant trace D.encryption_nonce_usage (D.role_label who) D.encryption_nonce_length position;
     rand_usage_and_label trace D.encryption_nonce_usage (D.role_label who) D.encryption_nonce_length position)

/// The two configured recipient public keys are well formed PKE keys.
let recipient_key_facts
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (trace:TB.trace)
  (secret:BT.bytes)
  : Lemma
      (requires secret_key_recorded who trace secret)
      (ensures (
        let pk = D.role_public_key who in
        B.bytes_invariant #P.nsl_crypto_invariants trace pk /\
        B.get_sk_label #P.nsl_crypto_usages trace pk == D.role_label who /\
        B.has_sk_usage #P.nsl_crypto_usages trace pk (D.key_usage who) /\
        BT.PkeKey? (D.key_usage who)))
  =
  secret_key_facts who trace secret
#pop-options

#push-options "--fuel 2 --ifuel 1 --z3rlimit 10"
let secret_key_recorded_later
  (who:E.endpoint_id)
  (trace0 trace1:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires secret_key_recorded who trace0 value /\ trace0 `TB.grows` trace1)
      (ensures secret_key_recorded who trace1 value)
  =
  eliminate
    (who == SM.initiator_endpoint /\
      value == D.key_term 0 /\
      TB.entry_at trace0 0
        (T.RandGen D.initiator_key_usage (D.role_label SM.initiator_endpoint) D.key_length)) \/
    (who == SM.responder_endpoint /\
      value == D.key_term 2 /\
      TB.entry_at trace0 2
        (T.RandGen D.responder_key_usage (D.role_label SM.responder_endpoint) D.key_length))
  returns secret_key_recorded who trace1 value
  with _.
    TB.entry_at_grows trace0 trace1 0
      (T.RandGen D.initiator_key_usage (D.role_label SM.initiator_endpoint) D.key_length)
  and _.
    TB.entry_at_grows trace0 trace1 2
      (T.RandGen D.responder_key_usage (D.role_label SM.responder_endpoint) D.key_length)

let randomness_recorded_later
  (who:E.endpoint_id)
  (trace0 trace1:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires randomness_recorded who trace0 value /\ trace0 `TB.grows` trace1)
      (ensures randomness_recorded who trace1 value)
  =
  eliminate
    exists (position:nat).
      value == D.encryption_nonce_term position /\
      TB.entry_at trace0 position
        (T.RandGen D.encryption_nonce_usage (D.role_label who) D.encryption_nonce_length)
  returns randomness_recorded who trace1 value
  with _.
    (TB.entry_at_grows trace0 trace1 position
       (T.RandGen D.encryption_nonce_usage (D.role_label who) D.encryption_nonce_length);
     introduce
       exists (later:nat).
         value == D.encryption_nonce_term later /\
         TB.entry_at trace1 later
           (T.RandGen D.encryption_nonce_usage (D.role_label who) D.encryption_nonce_length)
     with position and ())

let optional_both_knowable_later
  (trace0 trace1:TB.trace)
  (value:option BT.bytes)
  : Lemma
      (requires optional_both_knowable trace0 value /\ trace0 `TB.grows` trace1)
      (ensures optional_both_knowable trace1 value)
  =
  match value with
  | None -> ()
  | Some term -> both_knowable_later trace0 trace1 term

let optional_publishable_later
  (trace0 trace1:TB.trace)
  (value:option BT.bytes)
  : Lemma
      (requires optional_publishable trace0 value /\ trace0 `TB.grows` trace1)
      (ensures optional_publishable trace1 value)
  =
  match value with
  | None -> ()
  | Some term -> publishable_later trace0 trace1 term

let optional_randomness_recorded_later
  (who:E.endpoint_id)
  (trace0 trace1:TB.trace)
  (value:option BT.bytes)
  : Lemma
      (requires optional_randomness_recorded who trace0 value /\ trace0 `TB.grows` trace1)
      (ensures optional_randomness_recorded who trace1 value)
  =
  match value with
  | None -> ()
  | Some term -> randomness_recorded_later who trace0 trace1 term

let plaintext_material_valid_later
  (trace0 trace1:TB.trace)
  (value:M.symbolic_plaintext)
  : Lemma
      (requires plaintext_material_valid trace0 value /\ trace0 `TB.grows` trace1)
      (ensures plaintext_material_valid trace1 value)
  =
  match value with
  | M.SymbolicPlaintext1 initiator_nonce initiator ->
    both_knowable_later trace0 trace1 initiator_nonce;
    both_knowable_later trace0 trace1 initiator
  | M.SymbolicPlaintext2 initiator_nonce responder_nonce responder ->
    both_knowable_later trace0 trace1 initiator_nonce;
    both_knowable_later trace0 trace1 responder_nonce;
    both_knowable_later trace0 trace1 responder
  | M.SymbolicPlaintext3 responder_nonce ->
    both_knowable_later trace0 trace1 responder_nonce

let optional_plaintext_material_valid_later
  (trace0 trace1:TB.trace)
  (value:option M.symbolic_plaintext)
  : Lemma
      (requires optional_plaintext_material_valid trace0 value /\ trace0 `TB.grows` trace1)
      (ensures optional_plaintext_material_valid trace1 value)
  =
  match value with
  | None -> ()
  | Some plaintext -> plaintext_material_valid_later trace0 trace1 plaintext

let message_material_valid_later
  (trace0 trace1:TB.trace)
  (value:M.symbolic_message)
  : Lemma
      (requires message_material_valid trace0 value /\ trace0 `TB.grows` trace1)
      (ensures message_material_valid trace1 value)
  =
  match value with
  | M.SymbolicEncrypted ciphertext plaintext ->
    publishable_later trace0 trace1 ciphertext;
    optional_plaintext_material_valid_later trace0 trace1 plaintext

let optional_message_valid_later
  (trace0 trace1:TB.trace)
  (value:option M.symbolic_message)
  : Lemma
      (requires optional_message_valid trace0 value /\ trace0 `TB.grows` trace1)
      (ensures optional_message_valid trace1 value)
  =
  match value with
  | None -> ()
  | Some message -> message_material_valid_later trace0 trace1 message

let shadow_valid_later
  (who:E.endpoint_id)
  (trace0 trace1:TB.trace)
  (shadow:M.endpoint_shadow)
  : Lemma
      (requires shadow_valid who trace0 shadow /\ trace0 `TB.grows` trace1)
      (ensures shadow_valid who trace1 shadow)
  =
  secret_key_recorded_later who trace0 trace1 shadow.M.secret_key;
  optional_both_knowable_later trace0 trace1 shadow.M.pending_nonce;
  optional_randomness_recorded_later who trace0 trace1 shadow.M.pending_randomness;
  optional_both_knowable_later trace0 trace1 shadow.M.initiator_nonce;
  optional_both_knowable_later trace0 trace1 shadow.M.responder_nonce;
  optional_publishable_later trace0 trace1 shadow.M.pending_ciphertext;
  optional_plaintext_material_valid_later trace0 trace1 shadow.M.pending_plaintext;
  optional_message_valid_later trace0 trace1 shadow.M.last_received

let rec network_valid_later
  (trace0 trace1:TB.trace)
  (network:list M.network_shadow)
  : Lemma
      (requires network_valid trace0 network /\ trace0 `TB.grows` trace1)
      (ensures network_valid trace1 network)
      (decreases network)
  =
  match network with
  | [] -> ()
  | packet :: tail ->
    message_material_valid_later trace0 trace1 packet.M.symbolic_packet;
    TB.entry_at_grows trace0 trace1 packet.M.send_position
      (T.MsgSent (M.flatten_message packet.M.symbolic_packet));
    network_valid_later trace0 trace1 tail
#pop-options

#push-options "--fuel 3 --ifuel 1 --z3rlimit 10"
let rec network_valid_append
  (trace:TB.trace)
  (network:list M.network_shadow)
  (packet:M.network_shadow)
  : Lemma
      (requires
        network_valid trace network /\
        message_material_valid trace packet.M.symbolic_packet /\
        TB.entry_at trace packet.M.send_position
          (T.MsgSent (M.flatten_message packet.M.symbolic_packet)))
      (ensures network_valid trace (List.append network [ packet ]))
      (decreases network)
  =
  match network with
  | [] -> ()
  | head :: tail -> network_valid_append trace tail packet
#pop-options

(*** Section 5: snapshot knowability (SetState obligation) ***)

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
let empty_data_publishable (trace:TB.trace)
  : Lemma (publishable trace D.empty_data)
  =
  B.literal_to_bytes_is_publishable
    #P.nsl_crypto_invariants trace (Seq.empty #U8.t)

let optional_term_knowable_both
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (trace:TB.trace)
  (value:option BT.bytes)
  : Lemma
      (requires optional_both_knowable trace value)
      (ensures knowable who trace (D.optional_term value))
  =
  match value with
  | None -> empty_data_publishable trace; public_is_knowable who trace D.empty_data
  | Some term -> both_knowable_implies_knowable who trace term

let optional_term_knowable_rand
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (trace:TB.trace)
  (value:option BT.bytes)
  : Lemma
      (requires optional_randomness_recorded who trace value)
      (ensures knowable who trace (D.optional_term value))
  =
  match value with
  | None -> empty_data_publishable trace; public_is_knowable who trace D.empty_data
  | Some term -> randomness_facts who trace term

let snapshot_knowable
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (trace:TB.trace)
  (shadow:M.endpoint_shadow)
  : Lemma
      (requires shadow_valid who trace shadow)
      (ensures
        P.state_predicate trace
          (D.role_principal who)
          (D.role_state_id who)
          (M.endpoint_snapshot shadow))
  =
  secret_key_facts who trace shadow.M.secret_key;
  optional_term_knowable_both who trace shadow.M.pending_nonce;
  optional_term_knowable_rand who trace shadow.M.pending_randomness;
  optional_term_knowable_both who trace shadow.M.initiator_nonce;
  optional_term_knowable_both who trace shadow.M.responder_nonce
#pop-options

(*** Section 6: event-entry obligations ***)

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
/// An honest ciphertext-creation event satisfies the event predicate when the
/// creator is the canonical author of the message type it encrypts.
let message_event_entry
  (trace:TB.trace)
  (who:E.endpoint_id)
  (sp:M.symbolic_plaintext)
  : Lemma
      (requires
        (M.SymbolicPlaintext1? sp ==> who == SM.initiator_endpoint) /\
        (M.SymbolicPlaintext2? sp ==> who == SM.responder_endpoint) /\
        (M.SymbolicPlaintext3? sp ==> who == SM.initiator_endpoint))
      (ensures
        TI.trace_entry_invariant #P.nsl_protocol_invariants trace
          (T.Event
            (D.role_principal who)
            (M.encryption_tag sp)
            (M.flatten_plaintext sp)))
  =
  match sp with
  | M.SymbolicPlaintext1 initiator_nonce initiator ->
    introduce
      exists (n i:BT.bytes). M.flatten_plaintext sp == D.plaintext1_term n i
    with initiator_nonce initiator and ()
  | M.SymbolicPlaintext2 initiator_nonce responder_nonce responder ->
    introduce
      exists (n1 n2 r:BT.bytes).
        M.flatten_plaintext sp == D.plaintext2_term n1 n2 r
    with initiator_nonce responder_nonce responder and ()
  | M.SymbolicPlaintext3 responder_nonce ->
    introduce
      exists (n:BT.bytes). M.flatten_plaintext sp == D.plaintext3_term n
    with responder_nonce and ()

let accepted_event_entry
  (trace:TB.trace)
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (ciphertext plaintext:BT.bytes)
  : Lemma
      (ensures
        TI.trace_entry_invariant #P.nsl_protocol_invariants trace
          (T.Event
            (D.role_principal who)
            D.tag_accepted
            (D.accepted_content ciphertext plaintext)))
  =
  introduce
    exists (c p:BT.bytes).
      D.accepted_content ciphertext plaintext == D.accepted_content c p
  with ciphertext plaintext and ()

let completion_event_entry
  (trace:TB.trace)
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (peer initiator_nonce responder_nonce:BT.bytes)
  : Lemma
      (ensures
        TI.trace_entry_invariant #P.nsl_protocol_invariants trace
          (T.Event
            (D.role_principal who)
            D.tag_complete
            (D.session_content peer initiator_nonce responder_nonce)))
  =
  introduce
    exists (p n1 n2:BT.bytes).
      D.session_content peer initiator_nonce responder_nonce ==
        D.session_content p n1 n2
  with peer initiator_nonce responder_nonce and ()
#pop-options

(*** Section 7: honest ciphertext publishability (send obligation) ***)

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
let plaintext_material_flows_session
  (trace:TB.trace)
  (sp:M.symbolic_plaintext)
  : Lemma
      (requires plaintext_material_valid trace sp)
      (ensures
        B.bytes_invariant #P.nsl_crypto_invariants trace (M.flatten_plaintext sp) /\
        L.can_flow trace
          (B.get_label #P.nsl_crypto_usages trace (M.flatten_plaintext sp))
          D.session_label)
  =
  match sp with
  | M.SymbolicPlaintext1 _ _ -> ()
  | M.SymbolicPlaintext2 _ _ _ -> ()
  | M.SymbolicPlaintext3 _ -> ()
#pop-options

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
/// The crux: an honest configured-recipient ciphertext is a genuine PkeEnc term
/// carrying a protocol authorization event, and it is publishable.
let genuine_ciphertext_publishable
  (trace:TB.trace)
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (recipient:E.endpoint_id{recipient == SM.initiator_endpoint \/ recipient == SM.responder_endpoint})
  (sp:M.symbolic_plaintext)
  (randomness:BT.bytes)
  : Lemma
      (requires
        secret_key_recorded recipient trace (D.role_secret_key recipient) /\
        randomness_recorded who trace randomness /\
        plaintext_material_valid trace sp /\
        P.pke_authorized (D.role_public_key recipient) (D.role_principal who) (M.encryption_tag sp) /\
        TB.event_triggered trace
          (D.role_principal who) (M.encryption_tag sp) (M.flatten_plaintext sp))
      (ensures
        publishable trace
          (D.ciphertext_term (D.role_public_key recipient) randomness (M.flatten_plaintext sp)))
  =
  let pk = D.role_public_key recipient in
  let msg = M.flatten_plaintext sp in
  recipient_key_facts recipient trace (D.role_secret_key recipient);
  randomness_facts who trace randomness;
  plaintext_material_flows_session trace sp;
  session_flows trace who;
  session_flows trace recipient;
  L.can_flow_transitive trace
    (B.get_label #P.nsl_crypto_usages trace msg)
    D.session_label
    (D.role_label recipient);
  L.can_flow_transitive trace
    (B.get_label #P.nsl_crypto_usages trace msg)
    D.session_label
    (D.role_label who);
  introduce
    exists (principal:T.principal) (tag:string).
      P.pke_authorized pk principal tag /\
      TB.event_triggered trace principal tag msg
  with (D.role_principal who) (M.encryption_tag sp) and ();
  assert (P.pke_predicate trace (D.key_usage recipient) pk msg);
  B.bytes_invariant_pke_enc #P.nsl_crypto_invariants trace
    pk (D.key_usage recipient) randomness msg
#pop-options

(*** Section 8: plaintext_term and honest_message validity ***)

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
let nonce_literal_both_knowable (trace:TB.trace) (value:nonce)
  : Lemma (both_knowable trace (D.nonce_literal value))
  =
  B.literal_to_bytes_is_publishable #P.nsl_crypto_invariants trace value;
  publishable_implies_both_knowable trace (D.nonce_literal value)

let principal_term_both_knowable (trace:TB.trace) (value:principal)
  : Lemma (both_knowable trace (D.principal_term value))
  =
  B.literal_to_bytes_is_publishable #P.nsl_crypto_invariants trace value;
  publishable_implies_both_knowable trace (D.principal_term value)

let ciphertext_literal_publishable (trace:TB.trace) (value:ciphertext)
  : Lemma (publishable trace (D.ciphertext_literal value))
  =
  B.literal_to_bytes_is_publishable #P.nsl_crypto_invariants trace value

let received_plaintext_valid
  (trace:TB.trace)
  (shadow:M.endpoint_shadow)
  : Lemma
      (requires optional_message_valid trace shadow.M.last_received)
      (ensures optional_plaintext_material_valid trace (M.received_plaintext shadow))
  =
  match shadow.M.last_received with
  | None -> ()
  | Some (M.SymbolicEncrypted _ _) -> ()

let nonce_from_received_both_knowable
  (trace:TB.trace)
  (shadow:M.endpoint_shadow)
  (fallback:nonce)
  : Lemma
      (requires optional_plaintext_material_valid trace (M.received_plaintext shadow))
      (ensures both_knowable trace (M.nonce_from_received shadow fallback))
  =
  match M.received_plaintext shadow with
  | Some (M.SymbolicPlaintext1 _ _) -> ()
  | Some (M.SymbolicPlaintext2 _ _ _) -> ()
  | Some (M.SymbolicPlaintext3 _) -> ()
  | None -> nonce_literal_both_knowable trace fallback

let plaintext_term_valid
  (who:E.endpoint_id)
  (trace:TB.trace)
  (shadow:M.endpoint_shadow)
  (plaintext:plaintext)
  : Lemma
      (requires shadow_valid who trace shadow)
      (ensures plaintext_material_valid trace (M.plaintext_term shadow plaintext))
  =
  received_plaintext_valid trace shadow;
  match plaintext with
  | PlainMessage1 initiator_nonce initiator ->
    (match shadow.M.pending_nonce with
     | Some _ -> ()
     | None -> nonce_literal_both_knowable trace initiator_nonce);
    principal_term_both_knowable trace initiator
  | PlainMessage2 initiator_nonce responder_nonce responder ->
    (match shadow.M.initiator_nonce with
     | Some _ -> ()
     | None ->
       (match M.received_plaintext shadow with
        | Some (M.SymbolicPlaintext1 _ _) -> ()
        | _ -> nonce_literal_both_knowable trace initiator_nonce));
    (match shadow.M.pending_nonce with
     | Some _ -> ()
     | None -> nonce_literal_both_knowable trace responder_nonce);
    principal_term_both_knowable trace responder
  | PlainMessage3 responder_nonce ->
    (match shadow.M.responder_nonce with
     | Some _ -> ()
     | None ->
       nonce_from_received_both_knowable trace shadow responder_nonce)

let accepted_plaintext_term_valid
  (who:E.endpoint_id)
  (trace:TB.trace)
  (shadow:M.endpoint_shadow)
  (plaintext:plaintext)
  : Lemma
      (requires shadow_valid who trace shadow)
      (ensures
        plaintext_material_valid trace
          (M.accepted_plaintext_term shadow plaintext))
  =
  match plaintext with
  | PlainMessage1 initiator_nonce initiator ->
    nonce_literal_both_knowable trace initiator_nonce;
    principal_term_both_knowable trace initiator
  | PlainMessage2 initiator_nonce responder_nonce responder ->
    (match shadow.M.initiator_nonce with
     | Some _ -> ()
     | None -> nonce_literal_both_knowable trace initiator_nonce);
    nonce_literal_both_knowable trace responder_nonce;
    principal_term_both_knowable trace responder
  | PlainMessage3 responder_nonce ->
    (match shadow.M.responder_nonce with
     | Some _ -> ()
     | None -> nonce_literal_both_knowable trace responder_nonce)

let message_valid_implies_flatten_publishable
  (trace:TB.trace)
  (message:M.symbolic_message)
  : Lemma
      (requires message_material_valid trace message)
      (ensures publishable trace (M.flatten_message message))
  =
  match message with
  | M.SymbolicEncrypted _ _ -> ()
#pop-options

#push-options "--fuel 3 --ifuel 2 --z3rlimit 10"
let honest_message_valid
  (state:M.model)
  (who:E.endpoint_id)
  (message:message)
  : Lemma
      (requires model_invariant state)
      (ensures
        message_material_valid state.M.dy_trace
          (M.honest_message state who message))
  =
  eliminate
    exists (initiator responder:M.endpoint_shadow).
      state.M.endpoints == [ initiator; responder ] /\
      shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
      shadow_valid SM.responder_endpoint state.M.dy_trace responder
  returns
    message_material_valid state.M.dy_trace
      (M.honest_message state who message)
  with _.
    (match message with
     | Encrypted concrete ->
       ciphertext_literal_publishable state.M.dy_trace concrete;
       if who = SM.initiator_endpoint
       then assert (M.lookup state.M.endpoints who == Some initiator)
       else if who = SM.responder_endpoint
       then assert (M.lookup state.M.endpoints who == Some responder)
       else assert (M.lookup state.M.endpoints who == None))
#pop-options

(*** Section 9: single-entry model step and network lookup ***)

#push-options "--fuel 2 --ifuel 1 --z3rlimit 10"
let model_trace_snoc
  (state:M.model)
  (entry:TB.trace_entry)
  : Lemma
      (requires
        model_invariant state /\
        TI.trace_entry_invariant
          #P.nsl_protocol_invariants state.M.dy_trace entry)
      (ensures
        model_invariant
          { state with M.dy_trace = TB.append_entry state.M.dy_trace entry })
  =
  eliminate
    exists (initiator responder:M.endpoint_shadow).
      state.M.endpoints == [ initiator; responder ] /\
      shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
      shadow_valid SM.responder_endpoint state.M.dy_trace responder
  returns
    model_invariant
      { state with M.dy_trace = TB.append_entry state.M.dy_trace entry }
  with _.
    (let trace1 = TB.append_entry state.M.dy_trace entry in
     trace_invariant_snoc state.M.dy_trace entry;
     TB.grows_snoc state.M.dy_trace entry;
     shadow_valid_later SM.initiator_endpoint state.M.dy_trace trace1 initiator;
     shadow_valid_later SM.responder_endpoint state.M.dy_trace trace1 responder;
     network_valid_later state.M.dy_trace trace1 state.M.network;
     introduce
       exists (i r:M.endpoint_shadow).
         state.M.endpoints == [ i; r ] /\
         shadow_valid SM.initiator_endpoint trace1 i /\
         shadow_valid SM.responder_endpoint trace1 r
     with initiator responder and ())

let rec network_lookup_valid
  (trace:TB.trace)
  (network:list M.network_shadow)
  (index:nat)
  (packet:M.network_shadow)
  : Lemma
      (requires
        network_valid trace network /\
        M.lookup network index == Some packet)
      (ensures message_material_valid trace packet.M.symbolic_packet)
      (decreases network)
  =
  match network with
  | [] -> ()
  | head :: tail ->
    if index = 0 then () else network_lookup_valid trace tail (index - 1) packet
#pop-options

(*** Section 10: per-effect preservation ***)

#push-options "--fuel 3 --ifuel 2 --z3rlimit 10"
let compromised_preserves
  (state:M.model)
  (who:E.endpoint_id)
  : Lemma
      (requires model_invariant state)
      (ensures model_invariant (M.record_compromise state who))
  =
  eliminate
    exists (initiator responder:M.endpoint_shadow).
      state.M.endpoints == [ initiator; responder ] /\
      shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
      shadow_valid SM.responder_endpoint state.M.dy_trace responder
  returns model_invariant (M.record_compromise state who)
  with _.
    (if who = SM.initiator_endpoint
     then model_trace_snoc state (T.Corrupt initiator.M.state_position)
     else if who = SM.responder_endpoint
     then model_trace_snoc state (T.Corrupt responder.M.state_position)
     else assert (M.lookup state.M.endpoints who == None))

let received_preserves
  (state:M.model)
  (who:E.endpoint_id)
  (index:nat)
  : Lemma
      (requires model_invariant state)
      (ensures model_invariant (M.record_receive state who index))
  =
  eliminate
    exists (initiator responder:M.endpoint_shadow).
      state.M.endpoints == [ initiator; responder ] /\
      shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
      shadow_valid SM.responder_endpoint state.M.dy_trace responder
  returns model_invariant (M.record_receive state who index)
  with _.
    (match M.lookup state.M.network index with
     | None -> ()
     | Some packet ->
       network_lookup_valid state.M.dy_trace state.M.network index packet;
       if who = SM.initiator_endpoint
       then
         introduce
           exists (i r:M.endpoint_shadow).
             (M.record_receive state who index).M.endpoints == [ i; r ] /\
             shadow_valid SM.initiator_endpoint state.M.dy_trace i /\
             shadow_valid SM.responder_endpoint state.M.dy_trace r
         with
           ({ initiator with M.last_received = Some packet.M.symbolic_packet })
           responder
         and ()
       else if who = SM.responder_endpoint
       then
         introduce
           exists (i r:M.endpoint_shadow).
             (M.record_receive state who index).M.endpoints == [ i; r ] /\
             shadow_valid SM.initiator_endpoint state.M.dy_trace i /\
             shadow_valid SM.responder_endpoint state.M.dy_trace r
         with
           initiator
           ({ responder with M.last_received = Some packet.M.symbolic_packet })
         and ()
       else assert (M.lookup state.M.endpoints who == None))
#pop-options

#push-options "--fuel 3 --ifuel 2 --z3rlimit 10"
let sent_preserves
  (state:M.model)
  (who:E.endpoint_id)
  (index:nat)
  (message:message)
  : Lemma
      (requires model_invariant state)
      (ensures model_invariant (M.record_send state who index message))
  =
  let symbolic_packet = M.honest_message state who message in
  honest_message_valid state who message;
  message_valid_implies_flatten_publishable state.M.dy_trace symbolic_packet;
  let entry = T.MsgSent (M.flatten_message symbolic_packet) in
  let trace1 = TB.append_entry state.M.dy_trace entry in
  eliminate
    exists (initiator responder:M.endpoint_shadow).
      state.M.endpoints == [ initiator; responder ] /\
      shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
      shadow_valid SM.responder_endpoint state.M.dy_trace responder
  returns model_invariant (M.record_send state who index message)
  with _.
    (trace_invariant_snoc state.M.dy_trace entry;
     TB.grows_snoc state.M.dy_trace entry;
     shadow_valid_later SM.initiator_endpoint state.M.dy_trace trace1 initiator;
     shadow_valid_later SM.responder_endpoint state.M.dy_trace trace1 responder;
     message_material_valid_later state.M.dy_trace trace1 symbolic_packet;
     network_valid_later state.M.dy_trace trace1 state.M.network;
     network_valid_append trace1 state.M.network
       { M.symbolic_packet = symbolic_packet;
         M.send_position = TB.trace_length state.M.dy_trace };
     introduce
       exists (i r:M.endpoint_shadow).
         (M.record_send state who index message).M.endpoints == [ i; r ] /\
         shadow_valid SM.initiator_endpoint trace1 i /\
         shadow_valid SM.responder_endpoint trace1 r
     with initiator responder and ())

let injected_preserves
  (state:M.model)
  (index:nat)
  (message:message)
  : Lemma
      (requires model_invariant state)
      (ensures model_invariant (M.record_injection state index message))
  =
  match message with
  | Encrypted concrete ->
    let symbolic_packet = M.SymbolicEncrypted (D.ciphertext_literal concrete) None in
    ciphertext_literal_publishable state.M.dy_trace concrete;
    let entry = T.MsgSent (M.flatten_message symbolic_packet) in
    let trace1 = TB.append_entry state.M.dy_trace entry in
    eliminate
      exists (initiator responder:M.endpoint_shadow).
        state.M.endpoints == [ initiator; responder ] /\
        shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
        shadow_valid SM.responder_endpoint state.M.dy_trace responder
    returns model_invariant (M.record_injection state index message)
    with _.
      (trace_invariant_snoc state.M.dy_trace entry;
       TB.grows_snoc state.M.dy_trace entry;
       shadow_valid_later SM.initiator_endpoint state.M.dy_trace trace1 initiator;
       shadow_valid_later SM.responder_endpoint state.M.dy_trace trace1 responder;
       message_material_valid_later state.M.dy_trace trace1 symbolic_packet;
       network_valid_later state.M.dy_trace trace1 state.M.network;
       network_valid_append trace1 state.M.network
         { M.symbolic_packet = symbolic_packet;
           M.send_position = TB.trace_length state.M.dy_trace };
       introduce
         exists (i r:M.endpoint_shadow).
           (M.record_injection state index message).M.endpoints == [ i; r ] /\
           shadow_valid SM.initiator_endpoint trace1 i /\
           shadow_valid SM.responder_endpoint trace1 r
       with initiator responder and ())
#pop-options

#push-options "--fuel 3 --ifuel 2 --z3rlimit 10"
let completion_preserves
  (state:M.model)
  (who:E.endpoint_id)
  (peer:principal)
  : Lemma
      (requires model_invariant state)
      (ensures model_invariant (M.record_completion state who peer))
  =
  eliminate
    exists (initiator responder:M.endpoint_shadow).
      state.M.endpoints == [ initiator; responder ] /\
      shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
      shadow_valid SM.responder_endpoint state.M.dy_trace responder
  returns model_invariant (M.record_completion state who peer)
  with _.
    (if who = SM.initiator_endpoint
     then
       (match initiator.M.initiator_nonce, initiator.M.responder_nonce with
        | Some in_nonce, Some rn ->
          completion_event_entry state.M.dy_trace who (D.principal_term peer) in_nonce rn;
          model_trace_snoc state
            (T.Event (D.role_principal who) D.tag_complete
              (D.session_content (D.principal_term peer) in_nonce rn))
        | _, _ -> ())
     else if who = SM.responder_endpoint
     then
       (match responder.M.initiator_nonce, responder.M.responder_nonce with
        | Some in_nonce, Some rn ->
          completion_event_entry state.M.dy_trace who (D.principal_term peer) in_nonce rn;
          model_trace_snoc state
            (T.Event (D.role_principal who) D.tag_complete
              (D.session_content (D.principal_term peer) in_nonce rn))
        | _, _ -> ())
     else assert (M.lookup state.M.endpoints who == None))
#pop-options

#push-options "--fuel 3 --ifuel 2 --z3rlimit 10"
let accept_symbolic_plaintext_valid
  (who:E.endpoint_id)
  (trace:TB.trace)
  (shadow:M.endpoint_shadow)
  (plaintext:plaintext)
  : Lemma
      (requires shadow_valid who trace shadow)
      (ensures
        plaintext_material_valid trace
          (match M.received_plaintext shadow with
           | Some value -> value
           | None -> M.accepted_plaintext_term shadow plaintext))
  =
  received_plaintext_valid trace shadow;
  match M.received_plaintext shadow with
  | Some _ -> ()
  | None -> accepted_plaintext_term_valid who trace shadow plaintext

let accept_shadow_valid
  (who:E.endpoint_id)
  (trace:TB.trace)
  (shadow:M.endpoint_shadow)
  (sp:M.symbolic_plaintext)
  : Lemma
      (requires
        shadow_valid who trace shadow /\
        plaintext_material_valid trace sp)
      (ensures
        shadow_valid who trace
          (match sp with
           | M.SymbolicPlaintext1 initiator_nonce initiator ->
             { shadow with M.initiator_nonce = Some initiator_nonce; M.peer = Some initiator }
           | M.SymbolicPlaintext2 initiator_nonce responder_nonce responder ->
             { shadow with
                 M.initiator_nonce = Some initiator_nonce;
                 M.responder_nonce = Some responder_nonce;
                 M.peer = Some responder }
           | M.SymbolicPlaintext3 responder_nonce ->
             { shadow with M.responder_nonce = Some responder_nonce }))
  =
  match sp with
  | M.SymbolicPlaintext1 _ _ -> ()
  | M.SymbolicPlaintext2 _ _ _ -> ()
  | M.SymbolicPlaintext3 _ -> ()

let remember_created_plaintext_valid
  (who:E.endpoint_id)
  (trace:TB.trace)
  (shadow:M.endpoint_shadow)
  (sp:M.symbolic_plaintext)
  : Lemma
      (requires
        shadow_valid who trace shadow /\
        plaintext_material_valid trace sp)
      (ensures
        shadow_valid who trace
          (M.remember_created_plaintext shadow sp))
  =
  match sp with
  | M.SymbolicPlaintext1 _ _ -> ()
  | M.SymbolicPlaintext2 _ _ _ -> ()
  | M.SymbolicPlaintext3 _ -> ()
#pop-options

#push-options "--fuel 4 --ifuel 3 --z3rlimit 10"
let replace_two
  (a b c:M.endpoint_shadow)
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  : Lemma
      (ensures
        M.replace (if who = SM.initiator_endpoint then [ a; b ] else [ b; a ]) who c ==
          (if who = SM.initiator_endpoint then [ c; b ] else [ b; c ]))
  =
  if who = SM.initiator_endpoint then () else ()

/// Model invariant is preserved by updating the endpoint at [who] to a valid
/// [shadow2] over a trace where both endpoints (and the network) are valid.
let endpoint_update_valid
  (state:M.model)
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (old other shadow2:M.endpoint_shadow)
  (trace2:TB.trace)
  : Lemma
      (requires
        TI.trace_invariant #P.nsl_protocol_invariants trace2 /\
        network_valid trace2 state.M.network /\
        shadow_valid who trace2 shadow2 /\
        shadow_valid (1 - who) trace2 other /\
        state.M.endpoints ==
          (if who = SM.initiator_endpoint then [ old; other ] else [ other; old ]))
      (ensures
        model_invariant
          (M.put_endpoint { state with M.dy_trace = trace2 } who shadow2))
  =
  replace_two old other shadow2 who;
  introduce
    exists (i r:M.endpoint_shadow).
      (M.put_endpoint { state with M.dy_trace = trace2 } who shadow2).M.endpoints == [ i; r ] /\
      shadow_valid SM.initiator_endpoint trace2 i /\
      shadow_valid SM.responder_endpoint trace2 r
  with
    (if who = SM.initiator_endpoint then shadow2 else other)
    (if who = SM.initiator_endpoint then other else shadow2)
  and ()
#pop-options

#push-options "--fuel 4 --ifuel 3 --z3rlimit 10 --split_queries always"
let accept_preserves_shadow
  (state:M.model)
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (shadow other:M.endpoint_shadow)
  (plaintext:plaintext)
  : Lemma
      (requires
        TI.trace_invariant #P.nsl_protocol_invariants state.M.dy_trace /\
        network_valid state.M.dy_trace state.M.network /\
        M.lookup state.M.endpoints who == Some shadow /\
        M.lookup state.M.endpoints (1 - who) == Some other /\
        shadow_valid who state.M.dy_trace shadow /\
        shadow_valid (1 - who) state.M.dy_trace other /\
        state.M.endpoints ==
          (if who = SM.initiator_endpoint then [ shadow; other ] else [ other; shadow ]))
      (ensures model_invariant (M.accept_ciphertext state who plaintext))
  =
  accept_symbolic_plaintext_valid who state.M.dy_trace shadow plaintext;
  let sp =
    (match M.received_plaintext shadow with
     | Some value -> value
     | None -> M.accepted_plaintext_term shadow plaintext)
  in
  match M.accepted_ciphertext shadow with
  | None ->
    introduce
      exists (i r:M.endpoint_shadow).
        (M.accept_ciphertext state who plaintext).M.endpoints == [ i; r ] /\
        shadow_valid SM.initiator_endpoint state.M.dy_trace i /\
        shadow_valid SM.responder_endpoint state.M.dy_trace r
    with
      (if who = SM.initiator_endpoint then shadow else other)
      (if who = SM.initiator_endpoint then other else shadow)
    and ()
  | Some ciphertext ->
    accept_shadow_valid who state.M.dy_trace shadow sp;
    let shadow1 =
      (match sp with
       | M.SymbolicPlaintext1 n i -> { shadow with M.initiator_nonce = Some n; M.peer = Some i }
       | M.SymbolicPlaintext2 n1 n2 r -> { shadow with M.initiator_nonce = Some n1; M.responder_nonce = Some n2; M.peer = Some r }
       | M.SymbolicPlaintext3 n2 -> { shadow with M.responder_nonce = Some n2 })
    in
    let event_position = TB.trace_length state.M.dy_trace in
    let entry1 =
      T.Event (D.role_principal who) D.tag_accepted
        (D.accepted_content ciphertext (M.flatten_plaintext sp))
    in
    let trace1 = TB.append_entry state.M.dy_trace entry1 in
    let shadow2 = { shadow1 with M.state_position = event_position + 1 } in
    let entry2 =
      T.SetState (D.role_principal who) (D.role_state_id who) (M.endpoint_snapshot shadow2)
    in
    let trace2 = TB.append_entry trace1 entry2 in
    accepted_event_entry state.M.dy_trace who ciphertext (M.flatten_plaintext sp);
    trace_invariant_snoc state.M.dy_trace entry1;
    TB.grows_snoc state.M.dy_trace entry1;
    shadow_valid_later who state.M.dy_trace trace1 shadow1;
    snapshot_knowable who trace1 shadow2;
    trace_invariant_snoc trace1 entry2;
    TB.grows_snoc trace1 entry2;
    TB.grows_transitive state.M.dy_trace trace1 trace2;
    shadow_valid_later who trace1 trace2 shadow2;
    shadow_valid_later (1 - who) state.M.dy_trace trace2 other;
    network_valid_later state.M.dy_trace trace2 state.M.network;
    endpoint_update_valid state who shadow other shadow2 trace2;
    assert (M.accept_ciphertext state who plaintext ==
            M.put_endpoint { state with M.dy_trace = trace2 } who shadow2)

let accept_preserves
  (state:M.model)
  (who:E.endpoint_id)
  (plaintext:plaintext)
  : Lemma
      (requires model_invariant state)
      (ensures model_invariant (M.accept_ciphertext state who plaintext))
  =
  eliminate
    exists (initiator responder:M.endpoint_shadow).
      state.M.endpoints == [ initiator; responder ] /\
      shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
      shadow_valid SM.responder_endpoint state.M.dy_trace responder
  returns model_invariant (M.accept_ciphertext state who plaintext)
  with _.
    (if who = SM.initiator_endpoint
     then accept_preserves_shadow state who initiator responder plaintext
     else if who = SM.responder_endpoint
     then accept_preserves_shadow state who responder initiator plaintext
     else assert (M.lookup state.M.endpoints who == None))
#pop-options

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
let fresh_nonce_facts (trace:TB.trace) (position:nat)
  : Lemma
      (requires
        TB.entry_at trace position
          (T.RandGen D.protocol_nonce_usage D.session_label D.protocol_nonce_length))
      (ensures both_knowable trace (D.protocol_nonce_term position))
  =
  rand_bytes_invariant trace D.protocol_nonce_usage D.session_label D.protocol_nonce_length position;
  rand_usage_and_label trace D.protocol_nonce_usage D.session_label D.protocol_nonce_length position

let fresh_randomness_facts
  (who:E.endpoint_id) (trace:TB.trace) (position:nat)
  : Lemma
      (requires
        TB.entry_at trace position
          (T.RandGen D.encryption_nonce_usage (D.role_label who) D.encryption_nonce_length))
      (ensures randomness_recorded who trace (D.encryption_nonce_term position))
  =
  introduce
    exists (p:nat).
      D.encryption_nonce_term position == D.encryption_nonce_term p /\
      TB.entry_at trace p
        (T.RandGen D.encryption_nonce_usage (D.role_label who) D.encryption_nonce_length)
  with position and ()
#pop-options

#push-options "--fuel 4 --ifuel 3 --z3rlimit 10"
let generated_preserves_shadow
  (state:M.model)
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (value:fresh_value)
  (shadow other:M.endpoint_shadow)
  : Lemma
      (requires
        TI.trace_invariant #P.nsl_protocol_invariants state.M.dy_trace /\
        network_valid state.M.dy_trace state.M.network /\
        M.lookup state.M.endpoints who == Some shadow /\
        M.lookup state.M.endpoints (1 - who) == Some other /\
        shadow_valid who state.M.dy_trace shadow /\
        shadow_valid (1 - who) state.M.dy_trace other /\
        state.M.endpoints ==
          (if who = SM.initiator_endpoint then [ shadow; other ] else [ other; shadow ]))
      (ensures model_invariant (M.fresh_generated state who value))
  =
  let fresh_position = TB.trace_length state.M.dy_trace in
  match value with
  | FreshNonce _ ->
    let gt = D.protocol_nonce_term fresh_position in
    let entry1 = T.RandGen D.protocol_nonce_usage D.session_label D.protocol_nonce_length in
    let generated_trace = TB.append_entry state.M.dy_trace entry1 in
    let shadow1 = { shadow with M.pending_nonce = Some gt; M.state_position = fresh_position + 1 } in
    let entry2 = T.SetState (D.role_principal who) (D.role_state_id who) (M.endpoint_snapshot shadow1) in
    let trace1 = TB.append_entry generated_trace entry2 in
    trace_invariant_snoc state.M.dy_trace entry1;
    TB.grows_snoc state.M.dy_trace entry1;
    fresh_nonce_facts generated_trace fresh_position;
    shadow_valid_later who state.M.dy_trace generated_trace shadow;
    snapshot_knowable who generated_trace shadow1;
    trace_invariant_snoc generated_trace entry2;
    TB.grows_snoc generated_trace entry2;
    TB.grows_transitive state.M.dy_trace generated_trace trace1;
    shadow_valid_later who generated_trace trace1 shadow1;
    shadow_valid_later (1 - who) state.M.dy_trace trace1 other;
    network_valid_later state.M.dy_trace trace1 state.M.network;
    endpoint_update_valid state who shadow other shadow1 trace1;
    assert (M.fresh_generated state who value ==
            M.put_endpoint { state with M.dy_trace = trace1 } who shadow1)
  | FreshRandomness _ ->
    let gt = D.encryption_nonce_term fresh_position in
    let entry1 = T.RandGen D.encryption_nonce_usage (D.role_label who) D.encryption_nonce_length in
    let generated_trace = TB.append_entry state.M.dy_trace entry1 in
    let shadow1 = { shadow with M.pending_randomness = Some gt; M.state_position = fresh_position + 1 } in
    let entry2 = T.SetState (D.role_principal who) (D.role_state_id who) (M.endpoint_snapshot shadow1) in
    let trace1 = TB.append_entry generated_trace entry2 in
    trace_invariant_snoc state.M.dy_trace entry1;
    TB.grows_snoc state.M.dy_trace entry1;
    fresh_randomness_facts who generated_trace fresh_position;
    shadow_valid_later who state.M.dy_trace generated_trace shadow;
    snapshot_knowable who generated_trace shadow1;
    trace_invariant_snoc generated_trace entry2;
    TB.grows_snoc generated_trace entry2;
    TB.grows_transitive state.M.dy_trace generated_trace trace1;
    shadow_valid_later who generated_trace trace1 shadow1;
    shadow_valid_later (1 - who) state.M.dy_trace trace1 other;
    network_valid_later state.M.dy_trace trace1 state.M.network;
    endpoint_update_valid state who shadow other shadow1 trace1;
    assert (M.fresh_generated state who value ==
            M.put_endpoint { state with M.dy_trace = trace1 } who shadow1)

let generated_preserves
  (state:M.model)
  (who:E.endpoint_id)
  (value:fresh_value)
  : Lemma
      (requires model_invariant state)
      (ensures model_invariant (M.fresh_generated state who value))
  =
  eliminate
    exists (initiator responder:M.endpoint_shadow).
      state.M.endpoints == [ initiator; responder ] /\
      shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
      shadow_valid SM.responder_endpoint state.M.dy_trace responder
  returns model_invariant (M.fresh_generated state who value)
  with _.
    (if who = SM.initiator_endpoint
     then generated_preserves_shadow state who value initiator responder
     else if who = SM.responder_endpoint
     then generated_preserves_shadow state who value responder initiator
     else assert (M.lookup state.M.endpoints who == None))
#pop-options

(*** Section 10b: ciphertext creation preservation ***)

#push-options "--fuel 4 --ifuel 3 --z3rlimit 10"
/// The authorization guard exactly captures the honest configured-recipient
/// triples permitted by [Profile.pke_authorized].
let guard_facts
  (who:E.endpoint_id)
  (recipient:SM.recipient_key)
  (plaintext:plaintext)
  (shadow:M.endpoint_shadow)
  (recipient_key:BT.bytes)
  : Lemma
      (requires M.authorized_recipient_key who recipient plaintext == Some recipient_key)
      (ensures
        (who == SM.initiator_endpoint \/ who == SM.responder_endpoint) /\
        (recipient_key == D.role_public_key SM.initiator_endpoint \/
         recipient_key == D.role_public_key SM.responder_endpoint) /\
        P.pke_authorized recipient_key (D.role_principal who)
          (M.encryption_tag (M.plaintext_term shadow plaintext)) /\
        (M.SymbolicPlaintext1? (M.plaintext_term shadow plaintext) ==> who == SM.initiator_endpoint) /\
        (M.SymbolicPlaintext2? (M.plaintext_term shadow plaintext) ==> who == SM.responder_endpoint) /\
        (M.SymbolicPlaintext3? (M.plaintext_term shadow plaintext) ==> who == SM.initiator_endpoint))
  =
  match recipient, plaintext with
  | SM.EndpointKey _, PlainMessage1 _ _ -> ()
  | SM.EndpointKey _, PlainMessage2 _ _ _ -> ()
  | SM.EndpointKey _, PlainMessage3 _ -> ()
  | _, _ -> ()
#pop-options

#push-options "--fuel 4 --ifuel 3 --z3rlimit 10 --split_queries always"
let created_preserves_shadow
  (state:M.model)
  (who:E.endpoint_id{who == SM.initiator_endpoint \/ who == SM.responder_endpoint})
  (recipient:SM.recipient_key)
  (plaintext:plaintext)
  (concrete:ciphertext)
  (shadow other:M.endpoint_shadow)
  : Lemma
      (requires
        TI.trace_invariant #P.nsl_protocol_invariants state.M.dy_trace /\
        network_valid state.M.dy_trace state.M.network /\
        M.lookup state.M.endpoints who == Some shadow /\
        M.lookup state.M.endpoints (1 - who) == Some other /\
        shadow_valid who state.M.dy_trace shadow /\
        shadow_valid (1 - who) state.M.dy_trace other /\
        state.M.endpoints ==
          (if who = SM.initiator_endpoint then [ shadow; other ] else [ other; shadow ]) /\
        secret_key_recorded SM.initiator_endpoint state.M.dy_trace (D.role_secret_key SM.initiator_endpoint) /\
        secret_key_recorded SM.responder_endpoint state.M.dy_trace (D.role_secret_key SM.responder_endpoint))
      (ensures model_invariant (M.create_ciphertext state who recipient plaintext concrete))
  =
  plaintext_term_valid who state.M.dy_trace shadow plaintext;
  let sp = M.plaintext_term shadow plaintext in
  let flat = M.flatten_plaintext sp in
  remember_created_plaintext_valid who state.M.dy_trace shadow sp;
  let remembered = M.remember_created_plaintext shadow sp in
  match M.authorized_recipient_key who recipient plaintext, shadow.M.pending_randomness with
  | Some recipient_key, Some randomness ->
    guard_facts who recipient plaintext shadow recipient_key;
    message_event_entry state.M.dy_trace who sp;
    let entry1 = T.Event (D.role_principal who) (M.encryption_tag sp) flat in
    let trace1 = TB.append_entry state.M.dy_trace entry1 in
    let ct = D.ciphertext_term recipient_key randomness flat in
    let shadow1 = {
      remembered with
        M.pending_ciphertext = Some ct;
        M.pending_plaintext = Some sp;
    } in
    trace_invariant_snoc state.M.dy_trace entry1;
    TB.grows_snoc state.M.dy_trace entry1;
    plaintext_material_valid_later state.M.dy_trace trace1 sp;
    randomness_recorded_later who state.M.dy_trace trace1 randomness;
    secret_key_recorded_later SM.initiator_endpoint state.M.dy_trace trace1 (D.role_secret_key SM.initiator_endpoint);
    secret_key_recorded_later SM.responder_endpoint state.M.dy_trace trace1 (D.role_secret_key SM.responder_endpoint);
    introduce
      exists (i:nat). TB.event_triggered_at trace1 i (D.role_principal who) (M.encryption_tag sp) flat
    with (TB.trace_length state.M.dy_trace) and ();
    eliminate
      recipient_key == D.role_public_key SM.initiator_endpoint \/
      recipient_key == D.role_public_key SM.responder_endpoint
    returns publishable trace1 ct
    with _.
      genuine_ciphertext_publishable trace1 who SM.initiator_endpoint sp randomness
    and _.
      genuine_ciphertext_publishable trace1 who SM.responder_endpoint sp randomness;
    shadow_valid_later who state.M.dy_trace trace1 remembered;
    shadow_valid_later (1 - who) state.M.dy_trace trace1 other;
    network_valid_later state.M.dy_trace trace1 state.M.network;
    endpoint_update_valid state who shadow other shadow1 trace1;
    assert (M.create_ciphertext state who recipient plaintext concrete ==
            M.put_endpoint { state with M.dy_trace = trace1 } who shadow1)
  | _, _ ->
    let ct = D.ciphertext_literal concrete in
    let shadow1 = {
      remembered with
        M.pending_ciphertext = Some ct;
        M.pending_plaintext = Some sp;
    } in
    ciphertext_literal_publishable state.M.dy_trace concrete;
    endpoint_update_valid state who shadow other shadow1 state.M.dy_trace;
    assert (M.create_ciphertext state who recipient plaintext concrete ==
            M.put_endpoint { state with M.dy_trace = state.M.dy_trace } who shadow1)

let created_preserves
  (state:M.model)
  (who:E.endpoint_id)
  (recipient:SM.recipient_key)
  (plaintext:plaintext)
  (concrete:ciphertext)
  : Lemma
      (requires model_invariant state)
      (ensures model_invariant (M.create_ciphertext state who recipient plaintext concrete))
  =
  eliminate
    exists (initiator responder:M.endpoint_shadow).
      state.M.endpoints == [ initiator; responder ] /\
      shadow_valid SM.initiator_endpoint state.M.dy_trace initiator /\
      shadow_valid SM.responder_endpoint state.M.dy_trace responder
  returns model_invariant (M.create_ciphertext state who recipient plaintext concrete)
  with _.
    (if who = SM.initiator_endpoint
     then created_preserves_shadow state who recipient plaintext concrete initiator responder
     else if who = SM.responder_endpoint
     then created_preserves_shadow state who recipient plaintext concrete responder initiator
     else assert (M.lookup state.M.endpoints who == None))
#pop-options

(*** Section 11: effect dispatch, initial validity, history theorems ***)

#push-options "--fuel 4 --ifuel 2 --z3rlimit 10"
let protocol_effect_preserves
  (state:M.model)
  (who:E.endpoint_id)
  (event:SM.semantic_event)
  : Lemma
      (requires model_invariant state)
      (ensures model_invariant (M.protocol_effect state who event))
  =
  match event with
  | SM.CiphertextCreated _ _ recipient plaintext _ result ->
    created_preserves state who recipient plaintext result
  | SM.CiphertextAccepted _ plaintext _ ->
    accept_preserves state who plaintext
  | SM.Completed peer _ _ ->
    completion_preserves state who peer

let effect_preserves
  (state:M.model)
  (history_event:(S.system_effect message fresh_value SM.semantic_event))
  : Lemma
      (requires model_invariant state)
      (ensures
        model_invariant
          (I.interpret_one M.history_interpreter state history_event))
  =
  match history_event with
  | S.Generated who value ->
    generated_preserves state who value
  | S.ObservedReceive who index _ ->
    received_preserves state who index
  | S.ProtocolEffect who event ->
    protocol_effect_preserves state who event
  | S.ObservedSend who index message ->
    sent_preserves state who index message
  | S.AttackerInjected index message ->
    injected_preserves state index message
  | S.Compromised who ->
    compromised_preserves state who
#pop-options

#push-options "--fuel 6 --ifuel 2 --z3rlimit 10 --split_queries always"
let initial_model_invariant ()
  : Lemma (ensures model_invariant M.initial_model)
  =
  let e0 =
    T.RandGen D.initiator_key_usage (D.role_label SM.initiator_endpoint) D.key_length
  in
  let tr0 = TB.empty_trace in
  let tr1 = TB.append_entry tr0 e0 in
  reveal_opaque (`%TI.trace_invariant) (TI.trace_invariant #P.nsl_protocol_invariants);
  assert (TI.trace_invariant #P.nsl_protocol_invariants tr1);
  let initiator = M.initial_shadow (D.key_term 0) 1 in
  assert (secret_key_recorded SM.initiator_endpoint tr1 initiator.M.secret_key);
  snapshot_knowable SM.initiator_endpoint tr1 initiator;
  let e1 =
    T.SetState D.initiator_dy_principal (D.role_state_id SM.initiator_endpoint)
      (M.endpoint_snapshot initiator)
  in
  trace_invariant_snoc tr1 e1;
  let tr2 = TB.append_entry tr1 e1 in
  assert (shadow_valid SM.initiator_endpoint tr2 initiator);
  let e2 =
    T.RandGen D.responder_key_usage (D.role_label SM.responder_endpoint) D.key_length
  in
  trace_invariant_snoc tr2 e2;
  let tr3 = TB.append_entry tr2 e2 in
  let responder = M.initial_shadow (D.key_term 2) 3 in
  assert (secret_key_recorded SM.responder_endpoint tr3 responder.M.secret_key);
  snapshot_knowable SM.responder_endpoint tr3 responder;
  let e3 =
    T.SetState D.responder_dy_principal (D.role_state_id SM.responder_endpoint)
      (M.endpoint_snapshot responder)
  in
  trace_invariant_snoc tr3 e3;
  let tr4 = TB.append_entry tr3 e3 in
  assert (shadow_valid SM.responder_endpoint tr4 responder);
  TB.grows_snoc tr0 e0;
  TB.grows_snoc tr1 e1;
  TB.grows_snoc tr2 e2;
  TB.grows_snoc tr3 e3;
  TB.grows_transitive tr2 tr3 tr4;
  shadow_valid_later SM.initiator_endpoint tr2 tr4 initiator;
  introduce
    exists (i r:M.endpoint_shadow).
      M.initial_model.M.endpoints == [ i; r ] /\
      shadow_valid SM.initiator_endpoint M.initial_model.M.dy_trace i /\
      shadow_valid SM.responder_endpoint M.initial_model.M.dy_trace r
  with initiator responder and ()
#pop-options

noextract
let verified_history_interpreter
  : I.verified_interpreter
      message fresh_value SM.semantic_event M.model
      M.history_interpreter
  =
  {
    I.model_invariant = model_invariant;
    I.initial_valid = initial_model_invariant;
    I.effect_preserves = effect_preserves;
  }

let history_model_invariant
  (history:list (S.system_effect message fresh_value SM.semantic_event))
  : Lemma
      (ensures model_invariant (M.interpret_history history))
  =
  I.lemma_interpret_history_valid
    M.history_interpreter
    verified_history_interpreter
    history

let history_trace_invariant
  (history:list (S.system_effect message fresh_value SM.semantic_event))
  : Lemma
      (ensures
        TI.trace_invariant
          #P.nsl_protocol_invariants
          (M.dy_trace_of_history history))
  =
  history_model_invariant history

(*** Section 6: public DY-style honest-material fact API ***)

(**
  Stable public names for downstream (Security) proofs, mirroring the DH
  sample's [key_recorded]/[key_facts] and [nonce_recorded]/[nonce_facts]
  vocabulary.  Each [_recorded] predicate names the canonical RandGen entry
  that produced an honest ingredient; each [_facts] lemma exposes its
  [bytes_invariant], its honest [get_label], and its [has_usage].

  NSL has two different fresh-random ingredients at different labels:

    * PKE encryption randomness ([D.encryption_nonce_usage] = [BT.PkeNonce]) is
      generated at [D.role_label who].  Its public fact API remains
      [randomness_recorded]/[randomness_facts].

    * The protocol nonce Na/Nb ([D.protocol_nonce_usage] = [BT.NoUsage]) is a
      shared secret generated at the *session* label
      [D.session_label = L.join (role_label 0) (role_label 1)].  Its honest
      fact API is [nonce_recorded]/[nonce_facts]; being shared, it is
      additionally [both_knowable].
 *)

/// Public alias of [secret_key_recorded]: the long-term PKE secret key of role
/// [who] was produced by the canonical initial RandGen at [D.role_label who].
let key_recorded
  (who:E.endpoint_id)
  (trace:TB.trace)
  (value:BT.bytes)
  : prop
  =
  secret_key_recorded who trace value

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
/// Honest facts about a role key: it satisfies the bytes invariant, is labelled
/// with the single-role label [D.role_label who], and carries the role's PKE
/// key usage [D.key_usage who] (which is a [BT.PkeKey]).
let key_facts
  (who:E.endpoint_id)
  (trace:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires key_recorded who trace value)
      (ensures
        B.bytes_invariant #P.nsl_crypto_invariants trace value /\
        B.get_label #P.nsl_crypto_usages trace value == D.role_label who /\
        B.has_usage #P.nsl_crypto_usages trace value (D.key_usage who) /\
        BT.PkeKey? (D.key_usage who))
  =
  secret_key_facts who trace value
#pop-options

/// [value] is a fresh NSL protocol nonce (Na/Nb), produced by a RandGen at the
/// shared session label with protocol-nonce usage.
let nonce_recorded
  (trace:TB.trace)
  (value:BT.bytes)
  : prop
  =
  exists (position:nat).
    value == D.protocol_nonce_term position /\
    TB.entry_at trace position
      (T.RandGen
        D.protocol_nonce_usage
        D.session_label
        D.protocol_nonce_length)

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
/// Honest facts about a shared NSL protocol nonce.
let nonce_facts
  (trace:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires nonce_recorded trace value)
      (ensures
        B.bytes_invariant #P.nsl_crypto_invariants trace value /\
        B.get_label #P.nsl_crypto_usages trace value == D.session_label /\
        B.has_usage #P.nsl_crypto_usages trace value D.protocol_nonce_usage /\
        both_knowable trace value)
  =
  eliminate
    exists (position:nat).
      value == D.protocol_nonce_term position /\
      TB.entry_at trace position
        (T.RandGen D.protocol_nonce_usage D.session_label D.protocol_nonce_length)
  returns
    B.bytes_invariant #P.nsl_crypto_invariants trace value /\
    B.get_label #P.nsl_crypto_usages trace value == D.session_label /\
    B.has_usage #P.nsl_crypto_usages trace value D.protocol_nonce_usage /\
    both_knowable trace value
  with _.
    (rand_bytes_invariant trace
       D.protocol_nonce_usage D.session_label D.protocol_nonce_length position;
     rand_usage_and_label trace
       D.protocol_nonce_usage D.session_label D.protocol_nonce_length position)
#pop-options

/// Compatibility alias spelling out that [nonce_recorded] concerns Na/Nb.
let protocol_nonce_recorded
  (trace:TB.trace)
  (value:BT.bytes)
  : prop
  =
  nonce_recorded trace value

#push-options "--fuel 2 --ifuel 2 --z3rlimit 10"
/// Compatibility alias for [nonce_facts].
let protocol_nonce_facts
  (trace:TB.trace)
  (value:BT.bytes)
  : Lemma
      (requires protocol_nonce_recorded trace value)
      (ensures
        B.bytes_invariant #P.nsl_crypto_invariants trace value /\
        B.get_label #P.nsl_crypto_usages trace value == D.session_label /\
        B.has_usage #P.nsl_crypto_usages trace value D.protocol_nonce_usage /\
        both_knowable trace value)
  =
  nonce_facts trace value
#pop-options
