module YModem.Wire.Generated.Ymodem_empty

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LT = LowParse.TacLib
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBY = LowParse.PulseParse.Bytes
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPVCL = LowParse.PulseParse.VCList
module PPDER = LowParse.Pulse.DER
module PPVD = LowParse.PulseParse.VLData
module PPLS = LowParse.PulseParse.List
module PPAR = LowParse.PulseParse.Array
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse

#reset-options "--using_facts_from '* -FStar.Tactics -FStar.Reflection -Pulse -PulseCore' --z3rlimit 16 --z3cliopt smt.arith.nl=false --max_fuel 2 --max_ifuel 2"

noextract let ymodem_empty_parser = LP.parse_empty

noextract let ymodem_empty_serializer = LP.serialize_empty

let ymodem_empty_bytesize_eq x = ()

let ymodem_empty_reader = fun input #pm #v -> (PPC.leaf_read_empty) input #pm #v

let ymodem_empty_writer = fun x out offset #v -> (LPC.l2r_leaf_write_empty) x out offset #v

let ymodem_empty_leaf_size = fun x -> (LPC.leaf_size_empty) x

let read_ymodem_empty : PPB.copyful_parse ymodem_empty_vmatch ymodem_empty_parser ymodem_empty_conv = fun input #pm #v -> ((PPB.copyful_parse_leaf PPC.leaf_read_empty)) input #pm #v

let free_ymodem_empty : PPB.free_t ymodem_empty_vmatch = fun x #v -> ((PPB.free_leaf #unit)) x #v

let write_ymodem_empty : PPB.l2r_safe_writer ymodem_empty_vmatch ymodem_empty_serializer ymodem_empty_conv = fun x #y out #v perr -> ((PPB.l2r_safe_writer_leaf LP.serialize_empty 0sz LPC.l2r_leaf_write_empty)) x #y out #v perr

let ymodem_empty_bytesize_eqn x = (assert (FStar.Seq.length (LP.serialize LP.serialize_empty (x)) == 0))

