module YModem.Wire.Generated.Ymodem_tag

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LT = LowParse.TacLib
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBY = LowParse.PulseParse.Bytes
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPVCL = LowParse.PulseParse.VCList
module PPDER = LowParse.Pulse.DER
module PPVD = LowParse.PulseParse.VLData
module PPLS = LowParse.PulseParse.List
module PPAR = LowParse.PulseParse.Array
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse

#reset-options "--using_facts_from '* -FStar.Tactics -FStar.Reflection -Pulse -PulseCore' --z3rlimit 16 --z3cliopt smt.arith.nl=false --max_fuel 2 --max_ifuel 2"

assume val fits_u64_squash : squash FStar.SizeT.fits_u64

noextract let ymodem_tag_repr_parser = LPI.parse_u8

noextract let ymodem_tag_repr_serializer = LPI.serialize_u8

inline_for_extraction noextract let ymodem_tag_repr_validator = LPPI.validate_u8

inline_for_extraction noextract let ymodem_tag_repr_jumper = LPPI.jump_u8

inline_for_extraction noextract let ymodem_tag_repr_reader = (PPB.leaf_reader_of_serialized (LPPI.read_u8' ()))

inline_for_extraction noextract let ymodem_tag_repr_writer = (LPPI.l2r_leaf_write_u8 ())

inline_for_extraction let synth_ymodem_tag (x: LP.enum_key ymodem_tag_enum) : Tot ymodem_tag = x

inline_for_extraction let synth_ymodem_tag_inv (x: ymodem_tag) : Tot (LP.enum_key ymodem_tag_enum) =
  [@inline_let] let _ : squash (LP.list_mem x (LP.list_map fst ymodem_tag_enum)) =
    _ by (LP.synth_maybe_enum_key_inv_unknown_tac x)
  in
  x

let lemma_synth_ymodem_tag_inj () : Lemma
  (LP.synth_injective synth_ymodem_tag) = ()

let lemma_synth_ymodem_tag_inv () : Lemma
  (LP.synth_inverse synth_ymodem_tag synth_ymodem_tag_inv) = ()

noextract let parse_ymodem_tag_key : LP.parser _ (LP.enum_key ymodem_tag_enum) =
  LP.parse_enum_key ymodem_tag_repr_parser ymodem_tag_enum

noextract let serialize_ymodem_tag_key : LP.serializer parse_ymodem_tag_key =
  LP.serialize_enum_key ymodem_tag_repr_parser ymodem_tag_repr_serializer ymodem_tag_enum

noextract let ymodem_tag_parser : LP.parser _ ymodem_tag =
  lemma_synth_ymodem_tag_inj ();
  parse_ymodem_tag_key `LP.parse_synth` synth_ymodem_tag

noextract let ymodem_tag_serializer : LP.serializer ymodem_tag_parser =
  lemma_synth_ymodem_tag_inj ();
  lemma_synth_ymodem_tag_inv ();
  LP.serialize_synth _ synth_ymodem_tag serialize_ymodem_tag_key synth_ymodem_tag_inv ()

let ymodem_tag_bytesize_eq x = ()

[@@ (LT.postprocess_with LT.pp_norm_tac)]
inline_for_extraction let validate_ymodem_tag_key : LPS.validator parse_ymodem_tag_key =
    PPE.mk_validate_enum_key ymodem_tag_repr_validator ymodem_tag_repr_reader ymodem_tag_enum ()

let ymodem_tag_validator =
  lemma_synth_ymodem_tag_inj ();
  LPC.validate_synth validate_ymodem_tag_key synth_ymodem_tag

[@@ (LT.postprocess_with LT.pp_norm_tac)]
inline_for_extraction let read_ymodem_tag_key : PPB.leaf_reader parse_ymodem_tag_key =
  PPE.mk_read_enum_key ymodem_tag_repr_reader ymodem_tag_enum ()

let ymodem_tag_reader =
 lemma_synth_ymodem_tag_inj ();
 PPB.leaf_reader_of_reader (PPC.read_synth' (PPB.reader_of_leaf_reader read_ymodem_tag_key) synth_ymodem_tag synth_ymodem_tag_inv)

inline_for_extraction let write_ymodem_tag_key : LPS.l2r_leaf_writer (serialize_ymodem_tag_key) =
  LPPS.l2r_leaf_write_enum_key ymodem_tag_repr_writer ymodem_tag_enum (_ by (LP.enum_repr_of_key_tac ymodem_tag_enum))

let ymodem_tag_writer =
  [@inline_let] let _ = lemma_synth_ymodem_tag_inj (); lemma_synth_ymodem_tag_inv () in
  LPC.l2r_leaf_write_synth write_ymodem_tag_key synth_ymodem_tag synth_ymodem_tag_inv (fun x -> synth_ymodem_tag_inv x)

inline_for_extraction let size_ymodem_tag_key : LPS.leaf_size (serialize_ymodem_tag_key) =
  LPS.leaf_size_constant_size serialize_ymodem_tag_key 1sz (_ by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.smt ()))

let ymodem_tag_leaf_size =
  [@inline_let] let _ = lemma_synth_ymodem_tag_inj (); lemma_synth_ymodem_tag_inv () in
  LPC.leaf_size_synth size_ymodem_tag_key synth_ymodem_tag synth_ymodem_tag_inv (fun x -> synth_ymodem_tag_inv x)

let read_ymodem_tag = PPB.copyful_parse_leaf ymodem_tag_reader

let free_ymodem_tag = PPB.free_leaf

let write_ymodem_tag = PPB.l2r_safe_writer_leaf ymodem_tag_serializer 1sz ymodem_tag_writer

let size_ymodem_tag = PPB.l2r_safe_size_leaf ymodem_tag_serializer 1sz

