module YModem.Wire.Generated.Ymodem_message

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LT = LowParse.TacLib
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPBY = LowParse.PulseParse.Bytes
module PPVD = LowParse.PulseParse.VLData
module PPAR = LowParse.PulseParse.Array
module PPVCL = LowParse.PulseParse.VCList
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPDER = LowParse.Pulse.DER
module PPLS = LowParse.PulseParse.List
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse

open YModem.Wire.Generated.Ymodem_tag
open YModem.Wire.Generated.Ymodem_soh_body
open YModem.Wire.Generated.Ymodem_empty

noextract type ymodem_message =
  | Body_soh of ymodem_soh_body
  | Body_eot of ymodem_empty
  | Body_ack of ymodem_empty
  | Body_nak of ymodem_empty
  | Body_can of ymodem_empty
  | Body_crc_c of ymodem_empty

inline_for_extraction noextract let tag_of_ymodem_message (x:ymodem_message) : ymodem_tag = match x with
  | Body_soh _ -> Soh
  | Body_eot _ -> Eot
  | Body_ack _ -> Ack
  | Body_nak _ -> Nak
  | Body_can _ -> Can
  | Body_crc_c _ -> Crc_c

inline_for_extraction unfold let ymodem_tag_as_enum_key (x:ymodem_tag) : Pure (LP.enum_key ymodem_tag_enum)
  (requires norm [delta; zeta; iota; primops] (LP.list_mem x (LP.list_map fst ymodem_tag_enum)) == true) (ensures fun _ -> True) =
  [@inline_let] let _ = norm_spec [delta; zeta; iota; primops] (LP.list_mem x (LP.list_map fst ymodem_tag_enum)) in x

inline_for_extraction noextract let ymodem_message_parser_kind = LP.strong_parser_kind 1 133 None

noextract val ymodem_message_parser: LP.parser ymodem_message_parser_kind ymodem_message

noextract val ymodem_message_serializer: LP.serializer ymodem_message_parser

noextract let ymodem_message_bytesize (x:ymodem_message) : GTot nat = Seq.length (LP.serialize ymodem_message_serializer x)

noextract val ymodem_message_bytesize_eq (x:ymodem_message) : Lemma (ymodem_message_bytesize x == Seq.length (LP.serialize ymodem_message_serializer x))

val ymodem_message_validator: LPS.validator ymodem_message_parser

val ymodem_message_jumper: LPS.jumper ymodem_message_parser

noeq type ymodem_message_low =
  | Body_soh_low of ymodem_soh_body_lowtype
  | Body_eot_low of ymodem_empty_lowtype
  | Body_ack_low of ymodem_empty_lowtype
  | Body_nak_low of ymodem_empty_lowtype
  | Body_can_low of ymodem_empty_lowtype
  | Body_crc_c_low of ymodem_empty_lowtype

let ymodem_message_lowtype = ymodem_message_low

noextract noeq type ymodem_message_mid =
  | Body_soh_mid of ymodem_soh_body_mid
  | Body_eot_mid of ymodem_empty_mid
  | Body_ack_mid of ymodem_empty_mid
  | Body_nak_mid of ymodem_empty_mid
  | Body_can_mid of ymodem_empty_mid
  | Body_crc_c_mid of ymodem_empty_mid

let ymodem_message_low_tag (xl: ymodem_message_low) : LP.enum_key ymodem_tag_enum =
  match xl with
  | Body_soh_low _ -> ymodem_tag_as_enum_key Soh
  | Body_eot_low _ -> ymodem_tag_as_enum_key Eot
  | Body_ack_low _ -> ymodem_tag_as_enum_key Ack
  | Body_nak_low _ -> ymodem_tag_as_enum_key Nak
  | Body_can_low _ -> ymodem_tag_as_enum_key Can
  | Body_crc_c_low _ -> ymodem_tag_as_enum_key Crc_c

noextract let ymodem_message_mid_tag (m: ymodem_message_mid) : LP.enum_key ymodem_tag_enum =
  match m with
  | Body_soh_mid _ -> ymodem_tag_as_enum_key Soh
  | Body_eot_mid _ -> ymodem_tag_as_enum_key Eot
  | Body_ack_mid _ -> ymodem_tag_as_enum_key Ack
  | Body_nak_mid _ -> ymodem_tag_as_enum_key Nak
  | Body_can_mid _ -> ymodem_tag_as_enum_key Can
  | Body_crc_c_mid _ -> ymodem_tag_as_enum_key Crc_c

let ymodem_message_vmatch (xl: ymodem_message_low) (m: ymodem_message_mid) : Pulse.Lib.Core.slprop =
  Pulse.Lib.Core.op_Star_Star
    (Pulse.Lib.Core.pure (ymodem_message_low_tag xl == ymodem_message_mid_tag m))
    (match m with
     | Body_soh_mid cm -> (match xl with | Body_soh_low v -> ymodem_soh_body_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
     | Body_eot_mid cm -> (match xl with | Body_eot_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
     | Body_ack_mid cm -> (match xl with | Body_ack_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
     | Body_nak_mid cm -> (match xl with | Body_nak_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
     | Body_can_mid cm -> (match xl with | Body_can_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
     | Body_crc_c_mid cm -> (match xl with | Body_crc_c_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
    )

noextract let ymodem_message_conv (m: ymodem_message_mid) : GTot (FStar.Pervasives.Native.option ymodem_message) =
  match m with
  | Body_soh_mid cm -> (match ymodem_soh_body_conv cm with | FStar.Pervasives.Native.Some y -> FStar.Pervasives.Native.Some (Body_soh y) | FStar.Pervasives.Native.None -> FStar.Pervasives.Native.None)
  | Body_eot_mid cm -> (match ymodem_empty_conv cm with | FStar.Pervasives.Native.Some y -> FStar.Pervasives.Native.Some (Body_eot y) | FStar.Pervasives.Native.None -> FStar.Pervasives.Native.None)
  | Body_ack_mid cm -> (match ymodem_empty_conv cm with | FStar.Pervasives.Native.Some y -> FStar.Pervasives.Native.Some (Body_ack y) | FStar.Pervasives.Native.None -> FStar.Pervasives.Native.None)
  | Body_nak_mid cm -> (match ymodem_empty_conv cm with | FStar.Pervasives.Native.Some y -> FStar.Pervasives.Native.Some (Body_nak y) | FStar.Pervasives.Native.None -> FStar.Pervasives.Native.None)
  | Body_can_mid cm -> (match ymodem_empty_conv cm with | FStar.Pervasives.Native.Some y -> FStar.Pervasives.Native.Some (Body_can y) | FStar.Pervasives.Native.None -> FStar.Pervasives.Native.None)
  | Body_crc_c_mid cm -> (match ymodem_empty_conv cm with | FStar.Pervasives.Native.Some y -> FStar.Pervasives.Native.Some (Body_crc_c y) | FStar.Pervasives.Native.None -> FStar.Pervasives.Native.None)

val read_ymodem_message : PPB.copyful_parse ymodem_message_vmatch ymodem_message_parser ymodem_message_conv

val free_ymodem_message : PPB.free_t ymodem_message_vmatch

val write_ymodem_message : PPB.l2r_safe_writer ymodem_message_vmatch ymodem_message_serializer ymodem_message_conv

noextract let ymodem_message_clens_tag : LowParse.CLens.clens ymodem_message ymodem_tag = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun (x: ymodem_message) -> tag_of_ymodem_message x);
}

val ymodem_message_accessor_tag : PPB.accessor ymodem_message_parser ymodem_tag_parser ymodem_message_clens_tag

val ymodem_message_bytesize_eqn_soh (x: ymodem_soh_body) : Lemma (ymodem_message_bytesize (Body_soh x) == 1 + (ymodem_soh_body_bytesize (x))) [SMTPat (ymodem_message_bytesize (Body_soh x))]

val ymodem_message_bytesize_eqn_eot (x: ymodem_empty) : Lemma (ymodem_message_bytesize (Body_eot x) == 1 + (ymodem_empty_bytesize (x))) [SMTPat (ymodem_message_bytesize (Body_eot x))]

val ymodem_message_bytesize_eqn_ack (x: ymodem_empty) : Lemma (ymodem_message_bytesize (Body_ack x) == 1 + (ymodem_empty_bytesize (x))) [SMTPat (ymodem_message_bytesize (Body_ack x))]

val ymodem_message_bytesize_eqn_nak (x: ymodem_empty) : Lemma (ymodem_message_bytesize (Body_nak x) == 1 + (ymodem_empty_bytesize (x))) [SMTPat (ymodem_message_bytesize (Body_nak x))]

val ymodem_message_bytesize_eqn_can (x: ymodem_empty) : Lemma (ymodem_message_bytesize (Body_can x) == 1 + (ymodem_empty_bytesize (x))) [SMTPat (ymodem_message_bytesize (Body_can x))]

val ymodem_message_bytesize_eqn_crc_c (x: ymodem_empty) : Lemma (ymodem_message_bytesize (Body_crc_c x) == 1 + (ymodem_empty_bytesize (x))) [SMTPat (ymodem_message_bytesize (Body_crc_c x))]

noextract let ymodem_message_clens_soh : LowParse.CLens.clens ymodem_message ymodem_soh_body = {
  LowParse.CLens.clens_cond = (fun (x: ymodem_message) -> tag_of_ymodem_message x == Soh);
  LowParse.CLens.clens_get = (fun (x: ymodem_message) -> (match x with Body_soh y -> y) <: (Ghost ymodem_soh_body (requires (tag_of_ymodem_message x == Soh)) (ensures (fun y -> True))));
}

val ymodem_message_accessor_soh : PPB.accessor ymodem_message_parser ymodem_soh_body_parser ymodem_message_clens_soh

noextract let ymodem_message_clens_eot : LowParse.CLens.clens ymodem_message ymodem_empty = {
  LowParse.CLens.clens_cond = (fun (x: ymodem_message) -> tag_of_ymodem_message x == Eot);
  LowParse.CLens.clens_get = (fun (x: ymodem_message) -> (match x with Body_eot y -> y) <: (Ghost ymodem_empty (requires (tag_of_ymodem_message x == Eot)) (ensures (fun y -> True))));
}

val ymodem_message_accessor_eot : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_eot

noextract let ymodem_message_clens_ack : LowParse.CLens.clens ymodem_message ymodem_empty = {
  LowParse.CLens.clens_cond = (fun (x: ymodem_message) -> tag_of_ymodem_message x == Ack);
  LowParse.CLens.clens_get = (fun (x: ymodem_message) -> (match x with Body_ack y -> y) <: (Ghost ymodem_empty (requires (tag_of_ymodem_message x == Ack)) (ensures (fun y -> True))));
}

val ymodem_message_accessor_ack : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_ack

noextract let ymodem_message_clens_nak : LowParse.CLens.clens ymodem_message ymodem_empty = {
  LowParse.CLens.clens_cond = (fun (x: ymodem_message) -> tag_of_ymodem_message x == Nak);
  LowParse.CLens.clens_get = (fun (x: ymodem_message) -> (match x with Body_nak y -> y) <: (Ghost ymodem_empty (requires (tag_of_ymodem_message x == Nak)) (ensures (fun y -> True))));
}

val ymodem_message_accessor_nak : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_nak

noextract let ymodem_message_clens_can : LowParse.CLens.clens ymodem_message ymodem_empty = {
  LowParse.CLens.clens_cond = (fun (x: ymodem_message) -> tag_of_ymodem_message x == Can);
  LowParse.CLens.clens_get = (fun (x: ymodem_message) -> (match x with Body_can y -> y) <: (Ghost ymodem_empty (requires (tag_of_ymodem_message x == Can)) (ensures (fun y -> True))));
}

val ymodem_message_accessor_can : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_can

noextract let ymodem_message_clens_crc_c : LowParse.CLens.clens ymodem_message ymodem_empty = {
  LowParse.CLens.clens_cond = (fun (x: ymodem_message) -> tag_of_ymodem_message x == Crc_c);
  LowParse.CLens.clens_get = (fun (x: ymodem_message) -> (match x with Body_crc_c y -> y) <: (Ghost ymodem_empty (requires (tag_of_ymodem_message x == Crc_c)) (ensures (fun y -> True))));
}

val ymodem_message_accessor_crc_c : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_crc_c

