module YModem.Wire.Generated.Ymodem_packet

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LT = LowParse.TacLib
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBY = LowParse.PulseParse.Bytes
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPVCL = LowParse.PulseParse.VCList
module PPDER = LowParse.Pulse.DER
module PPVD = LowParse.PulseParse.VLData
module PPLS = LowParse.PulseParse.List
module PPAR = LowParse.PulseParse.Array
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse

#reset-options "--using_facts_from '* -FStar.Tactics -FStar.Reflection -Pulse -PulseCore' --z3rlimit 16 --z3cliopt smt.arith.nl=false --max_fuel 2 --max_ifuel 2"

assume val fits_u64_squash : squash FStar.SizeT.fits_u64

(* Type of field data*)
open YModem.Wire.Generated.Ymodem_packet_data

#push-options "--max_ifuel 10"
let synth_ymodem_packet_recip_inverse () : Lemma (LP.synth_inverse synth_ymodem_packet_recip synth_ymodem_packet) = ()

#pop-options

let synth_ymodem_packet_injective () : Lemma (LP.synth_injective synth_ymodem_packet) =
  LP.synth_inverse_synth_injective synth_ymodem_packet_recip synth_ymodem_packet;
  synth_ymodem_packet_recip_inverse ()

let synth_ymodem_packet_inverse () : Lemma (LP.synth_inverse synth_ymodem_packet synth_ymodem_packet_recip) =
  assert_norm (LP.synth_inverse synth_ymodem_packet synth_ymodem_packet_recip)

let synth_ymodem_packet_recip_injective () : Lemma (LP.synth_injective synth_ymodem_packet_recip) =
  synth_ymodem_packet_recip_inverse ();
  LP.synth_inverse_synth_injective synth_ymodem_packet synth_ymodem_packet_recip

noextract let ymodem_packet'_parser : LP.parser _ ymodem_packet' = (((LPI.parse_u8 `LP.nondep_then` LPI.parse_u8) `LP.nondep_then` (LPI.parse_u8 `LP.nondep_then` ymodem_packet_data_parser)) `LP.nondep_then` LPI.parse_u16)

noextract let ymodem_packet'_parser_kind = LP.get_parser_kind ymodem_packet'_parser

let ymodem_packet_parser =
  synth_ymodem_packet_injective ();
  assert_norm (ymodem_packet_parser_kind == ymodem_packet'_parser_kind);
  ymodem_packet'_parser `LP.parse_synth` synth_ymodem_packet

noextract let ymodem_packet'_serializer : LP.serializer ymodem_packet'_parser = (((LPI.serialize_u8 `LP.serialize_nondep_then` LPI.serialize_u8) `LP.serialize_nondep_then` (LPI.serialize_u8 `LP.serialize_nondep_then` ymodem_packet_data_serializer)) `LP.serialize_nondep_then` LPI.serialize_u16)

let ymodem_packet_serializer =
  [@inline_let] let _ = synth_ymodem_packet_injective () in
  [@inline_let] let _ = synth_ymodem_packet_inverse () in
  [@inline_let] let _ = assert_norm (ymodem_packet_parser_kind == ymodem_packet'_parser_kind) in
  LP.serialize_synth _ synth_ymodem_packet ymodem_packet'_serializer synth_ymodem_packet_recip ()

let ymodem_packet_bytesize_eq x = ()

let read_ymodem_packet : PPB.copyful_parse ymodem_packet_vmatch ymodem_packet_parser ymodem_packet_conv =
  synth_ymodem_packet_injective ();
  assert_norm (ymodem_packet_parser_kind == ymodem_packet'_parser_kind);
  PPC.copyful_parse_synth (PPC.copyful_parse_pair (LPC.jump_nondep_then (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) (LPC.jump_nondep_then LPPI.jump_u8 ymodem_packet_data_jumper)) (PPC.copyful_parse_pair (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) (PPC.copyful_parse_pair LPPI.jump_u8 (PPB.copyful_parse_leaf (PPB.leaf_reader_of_serialized (LPPI.read_u8' ()))) () (PPB.copyful_parse_leaf (PPB.leaf_reader_of_serialized (LPPI.read_u8' ())))) () (PPC.copyful_parse_pair LPPI.jump_u8 (PPB.copyful_parse_leaf (PPB.leaf_reader_of_serialized (LPPI.read_u8' ()))) () read_ymodem_packet_data)) () (PPB.copyful_parse_leaf (PPB.leaf_reader_of_serialized (LPPI.read_u16' ())))) synth_ymodem_packet synth_ymodem_packet_recip

let free_ymodem_packet : PPB.free_t ymodem_packet_vmatch = (PPC.free_pair (PPC.free_pair (PPC.free_pair (PPB.free_leaf #U8.t) (PPB.free_leaf #U8.t)) (PPC.free_pair (PPB.free_leaf #U8.t) free_ymodem_packet_data)) (PPB.free_leaf #U16.t))

let write_ymodem_packet : PPB.l2r_safe_writer ymodem_packet_vmatch ymodem_packet_serializer ymodem_packet_conv =
  synth_ymodem_packet_injective ();
  assert_norm (ymodem_packet_parser_kind == ymodem_packet'_parser_kind);
  PPC.l2r_safe_writer_synth (PPC.l2r_safe_writer_pair (PPC.l2r_safe_writer_pair (PPC.l2r_safe_writer_pair (PPB.l2r_safe_writer_leaf LPI.serialize_u8 1sz (LPPI.l2r_leaf_write_u8 ())) () (PPB.l2r_safe_writer_leaf LPI.serialize_u8 1sz (LPPI.l2r_leaf_write_u8 ()))) () (PPC.l2r_safe_writer_pair (PPB.l2r_safe_writer_leaf LPI.serialize_u8 1sz (LPPI.l2r_leaf_write_u8 ())) () write_ymodem_packet_data)) () (PPB.l2r_safe_writer_leaf LPI.serialize_u16 2sz (LPPI.l2r_leaf_write_u16 ()))) synth_ymodem_packet synth_ymodem_packet_recip

let size_ymodem_packet : PPB.l2r_safe_size ymodem_packet_vmatch ymodem_packet_serializer ymodem_packet_conv =
  synth_ymodem_packet_injective ();
  PPC.l2r_safe_size_synth (PPC.l2r_safe_size_pair fits_u64_squash (PPC.l2r_safe_size_pair fits_u64_squash (PPC.l2r_safe_size_pair fits_u64_squash (PPB.l2r_safe_size_leaf LPI.serialize_u8 1sz) () (PPB.l2r_safe_size_leaf LPI.serialize_u8 1sz)) () (PPC.l2r_safe_size_pair fits_u64_squash (PPB.l2r_safe_size_leaf LPI.serialize_u8 1sz) () size_ymodem_packet_data)) () (PPB.l2r_safe_size_leaf LPI.serialize_u16 2sz)) synth_ymodem_packet synth_ymodem_packet_recip

let ymodem_packet_bytesize_eqn x =
  [@inline_let] let _ = synth_ymodem_packet_injective () in
  [@inline_let] let _ = synth_ymodem_packet_inverse () in
  [@inline_let] let _ = assert_norm (ymodem_packet_parser_kind == ymodem_packet'_parser_kind) in
  LP.serialize_synth_eq _ synth_ymodem_packet ymodem_packet'_serializer synth_ymodem_packet_recip () x;
LP.length_serialize_nondep_then LPI.serialize_u8 LPI.serialize_u8 x.soh x.blk;
LP.length_serialize_nondep_then LPI.serialize_u8 ymodem_packet_data_serializer x.blk_complement x.data;
LP.length_serialize_nondep_then (LPI.serialize_u8 `LP.serialize_nondep_then` LPI.serialize_u8) (LPI.serialize_u8 `LP.serialize_nondep_then` ymodem_packet_data_serializer) (x.soh, x.blk) (x.blk_complement, x.data);
LP.length_serialize_nondep_then ((LPI.serialize_u8 `LP.serialize_nondep_then` LPI.serialize_u8) `LP.serialize_nondep_then` (LPI.serialize_u8 `LP.serialize_nondep_then` ymodem_packet_data_serializer)) LPI.serialize_u16 ((x.soh, x.blk), (x.blk_complement, x.data)) x.crc;
  (assert (FStar.Seq.length (LP.serialize LP.serialize_u8 (x.soh)) == 1));
  (assert (FStar.Seq.length (LP.serialize LP.serialize_u8 (x.blk)) == 1));
  (assert (FStar.Seq.length (LP.serialize LP.serialize_u8 (x.blk_complement)) == 1));
  (ymodem_packet_data_bytesize_eq (x.data));
  (assert (FStar.Seq.length (LP.serialize LP.serialize_u16 (x.crc)) == 2));
  assert(ymodem_packet_bytesize x == Seq.length (LP.serialize LPI.serialize_u8 x.soh) + Seq.length (LP.serialize LPI.serialize_u8 x.blk) + Seq.length (LP.serialize LPI.serialize_u8 x.blk_complement) + Seq.length (LP.serialize ymodem_packet_data_serializer x.data) + Seq.length (LP.serialize LPI.serialize_u16 x.crc))

inline_for_extraction noextract let accessor'_ymodem_packet_soh : PPB.accessor ymodem_packet'_parser LPI.parse_u8 _ = (PPC.accessor_then_fst (PPC.accessor_then_fst (PPC.accessor_then_fst (PPC.accessor_id ymodem_packet'_parser) (LPC.jump_nondep_then (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) (LPC.jump_nondep_then LPPI.jump_u8 ymodem_packet_data_jumper)) () ()) (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) () ()) LPPI.jump_u8 () ())

inline_for_extraction noextract let accessor'_ymodem_packet_blk : PPB.accessor ymodem_packet'_parser LPI.parse_u8 _ = (PPC.accessor_then_snd (PPC.accessor_then_fst (PPC.accessor_then_fst (PPC.accessor_id ymodem_packet'_parser) (LPC.jump_nondep_then (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) (LPC.jump_nondep_then LPPI.jump_u8 ymodem_packet_data_jumper)) () ()) (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) () ()) LPPI.jump_u8 () ())

inline_for_extraction noextract let accessor'_ymodem_packet_blk_complement : PPB.accessor ymodem_packet'_parser LPI.parse_u8 _ = (PPC.accessor_then_fst (PPC.accessor_then_snd (PPC.accessor_then_fst (PPC.accessor_id ymodem_packet'_parser) (LPC.jump_nondep_then (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) (LPC.jump_nondep_then LPPI.jump_u8 ymodem_packet_data_jumper)) () ()) (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) () ()) LPPI.jump_u8 () ())

inline_for_extraction noextract let accessor'_ymodem_packet_data : PPB.accessor ymodem_packet'_parser ymodem_packet_data_parser _ = (PPC.accessor_then_snd (PPC.accessor_then_snd (PPC.accessor_then_fst (PPC.accessor_id ymodem_packet'_parser) (LPC.jump_nondep_then (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) (LPC.jump_nondep_then LPPI.jump_u8 ymodem_packet_data_jumper)) () ()) (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) () ()) LPPI.jump_u8 () ())

inline_for_extraction noextract let accessor'_ymodem_packet_crc : PPB.accessor ymodem_packet'_parser LPI.parse_u16 _ = (PPC.accessor_then_snd (PPC.accessor_id ymodem_packet'_parser) (LPC.jump_nondep_then (LPC.jump_nondep_then LPPI.jump_u8 LPPI.jump_u8) (LPC.jump_nondep_then LPPI.jump_u8 ymodem_packet_data_jumper)) () ())

noextract let clens_ymodem_packet_ymodem_packet' : LowParse.CLens.clens ymodem_packet ymodem_packet' = synth_ymodem_packet_recip_inverse (); synth_ymodem_packet_recip_injective (); { LowParse.CLens.clens_cond = (fun _ -> True); LowParse.CLens.clens_get = synth_ymodem_packet_recip }

inline_for_extraction noextract let accessor_ymodem_packet_ymodem_packet' : PPB.accessor ymodem_packet_parser ymodem_packet'_parser clens_ymodem_packet_ymodem_packet' = synth_ymodem_packet_inverse (); synth_ymodem_packet_injective (); synth_ymodem_packet_recip_inverse (); PPC.accessor_synth_inv synth_ymodem_packet synth_ymodem_packet_recip

let accessor_ymodem_packet_soh = PPC.accessor_ext (PPC.accessor_compose accessor_ymodem_packet_ymodem_packet' accessor'_ymodem_packet_soh ()) clens_ymodem_packet_soh ()

let accessor_ymodem_packet_blk = PPC.accessor_ext (PPC.accessor_compose accessor_ymodem_packet_ymodem_packet' accessor'_ymodem_packet_blk ()) clens_ymodem_packet_blk ()

let accessor_ymodem_packet_blk_complement = PPC.accessor_ext (PPC.accessor_compose accessor_ymodem_packet_ymodem_packet' accessor'_ymodem_packet_blk_complement ()) clens_ymodem_packet_blk_complement ()

let accessor_ymodem_packet_data = PPC.accessor_ext (PPC.accessor_compose accessor_ymodem_packet_ymodem_packet' accessor'_ymodem_packet_data ()) clens_ymodem_packet_data ()

let accessor_ymodem_packet_crc = PPC.accessor_ext (PPC.accessor_compose accessor_ymodem_packet_ymodem_packet' accessor'_ymodem_packet_crc ()) clens_ymodem_packet_crc ()

