module YModem.Wire.Generated.Ymodem_soh_body

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LT = LowParse.TacLib
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPBY = LowParse.PulseParse.Bytes
module PPVD = LowParse.PulseParse.VLData
module PPAR = LowParse.PulseParse.Array
module PPVCL = LowParse.PulseParse.VCList
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPDER = LowParse.Pulse.DER
module PPLS = LowParse.PulseParse.List
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse


(* Type of field data*)
include YModem.Wire.Generated.Ymodem_soh_body_data

noextract type ymodem_soh_body = {
  blk : U8.t;
  blk_complement : U8.t;
  data : ymodem_soh_body_data;
  crc : U16.t;
}

noextract type ymodem_soh_body' = ((U8.t & U8.t) & (ymodem_soh_body_data & U16.t))

inline_for_extraction noextract let synth_ymodem_soh_body (x: ymodem_soh_body') : ymodem_soh_body =
  match x with ((blk,blk_complement),(data,crc)) -> {
    blk = blk;
    blk_complement = blk_complement;
    data = data;
    crc = crc;
  }

inline_for_extraction noextract let synth_ymodem_soh_body_recip (x: ymodem_soh_body) : ymodem_soh_body' = ((x.blk,x.blk_complement),(x.data,x.crc))

inline_for_extraction noextract let ymodem_soh_body_parser_kind = LP.strong_parser_kind 132 132 (Some LP.ParserKindMetadataTotal)

noextract val ymodem_soh_body_parser: LP.parser ymodem_soh_body_parser_kind ymodem_soh_body

noextract val ymodem_soh_body_serializer: LP.serializer ymodem_soh_body_parser

noextract let ymodem_soh_body_bytesize (x:ymodem_soh_body) : GTot nat = Seq.length (LP.serialize ymodem_soh_body_serializer x)

noextract val ymodem_soh_body_bytesize_eq (x:ymodem_soh_body) : Lemma (ymodem_soh_body_bytesize x == Seq.length (LP.serialize ymodem_soh_body_serializer x))

let ymodem_soh_body_validator: LPS.validator ymodem_soh_body_parser = LPS.validate_total_constant_size ymodem_soh_body_parser 132sz

let ymodem_soh_body_jumper: LPS.jumper ymodem_soh_body_parser = LPS.jump_constant_size ymodem_soh_body_parser 132sz

let ymodem_soh_body_lowtype = ((U8.t & U8.t) & (ymodem_soh_body_data_lowtype & U16.t))

noextract let ymodem_soh_body_mid = ((U8.t & U8.t) & (ymodem_soh_body_data_mid & U16.t))

let ymodem_soh_body_vmatch : ymodem_soh_body_lowtype -> ymodem_soh_body_mid -> Pulse.Lib.Core.slprop = (LPC.vmatch_pair (LPC.vmatch_pair (LPS.eq_as_slprop U8.t) (LPS.eq_as_slprop U8.t)) (LPC.vmatch_pair ymodem_soh_body_data_vmatch (LPS.eq_as_slprop U16.t)))

noextract let ymodem_soh_body_conv : ymodem_soh_body_mid -> GTot (FStar.Pervasives.Native.option ymodem_soh_body) = PPC.synth_conv (PPC.pair_conv (PPC.pair_conv (PPB.leaf_conv U8.t) (PPB.leaf_conv U8.t)) (PPC.pair_conv ymodem_soh_body_data_conv (PPB.leaf_conv U16.t))) synth_ymodem_soh_body

val read_ymodem_soh_body : PPB.copyful_parse ymodem_soh_body_vmatch ymodem_soh_body_parser ymodem_soh_body_conv

val free_ymodem_soh_body : PPB.free_t ymodem_soh_body_vmatch

val write_ymodem_soh_body : PPB.l2r_safe_writer ymodem_soh_body_vmatch ymodem_soh_body_serializer ymodem_soh_body_conv

val size_ymodem_soh_body : PPB.l2r_safe_size ymodem_soh_body_vmatch ymodem_soh_body_serializer ymodem_soh_body_conv

val ymodem_soh_body_bytesize_eqn (x: ymodem_soh_body) : Lemma (ymodem_soh_body_bytesize x == 1 + 1 + (ymodem_soh_body_data_bytesize (x.data)) + 2) [SMTPat (ymodem_soh_body_bytesize x)]

noextract let clens_ymodem_soh_body_blk : LowParse.CLens.clens ymodem_soh_body U8.t = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.blk);
}

val accessor_ymodem_soh_body_blk : PPB.accessor ymodem_soh_body_parser LPI.parse_u8 clens_ymodem_soh_body_blk

noextract let clens_ymodem_soh_body_blk_complement : LowParse.CLens.clens ymodem_soh_body U8.t = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.blk_complement);
}

val accessor_ymodem_soh_body_blk_complement : PPB.accessor ymodem_soh_body_parser LPI.parse_u8 clens_ymodem_soh_body_blk_complement

noextract let clens_ymodem_soh_body_data : LowParse.CLens.clens ymodem_soh_body ymodem_soh_body_data = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.data);
}

val accessor_ymodem_soh_body_data : PPB.accessor ymodem_soh_body_parser ymodem_soh_body_data_parser clens_ymodem_soh_body_data

noextract let clens_ymodem_soh_body_crc : LowParse.CLens.clens ymodem_soh_body U16.t = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.crc);
}

val accessor_ymodem_soh_body_crc : PPB.accessor ymodem_soh_body_parser LPI.parse_u16 clens_ymodem_soh_body_crc

