module YModem.Wire.Generated.Ymodem_empty

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LT = LowParse.TacLib
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPBY = LowParse.PulseParse.Bytes
module PPVD = LowParse.PulseParse.VLData
module PPAR = LowParse.PulseParse.Array
module PPVCL = LowParse.PulseParse.VCList
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPDER = LowParse.Pulse.DER
module PPLS = LowParse.PulseParse.List
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse


type ymodem_empty = unit

inline_for_extraction noextract let ymodem_empty_parser_kind = LP.strong_parser_kind 0 0 (Some LP.ParserKindMetadataTotal)

noextract val ymodem_empty_parser: LP.parser ymodem_empty_parser_kind ymodem_empty

noextract val ymodem_empty_serializer: LP.serializer ymodem_empty_parser

noextract let ymodem_empty_bytesize (x:ymodem_empty) : GTot nat = Seq.length (LP.serialize ymodem_empty_serializer x)

noextract val ymodem_empty_bytesize_eq (x:ymodem_empty) : Lemma (ymodem_empty_bytesize x == Seq.length (LP.serialize ymodem_empty_serializer x))

let ymodem_empty_validator: LPS.validator ymodem_empty_parser = LPS.validate_total_constant_size ymodem_empty_parser 0sz

let ymodem_empty_jumper: LPS.jumper ymodem_empty_parser = LPS.jump_constant_size ymodem_empty_parser 0sz

val ymodem_empty_reader : PPB.leaf_reader ymodem_empty_parser

val ymodem_empty_writer : LPS.l2r_leaf_writer ymodem_empty_serializer

val ymodem_empty_leaf_size : LPS.leaf_size ymodem_empty_serializer

let ymodem_empty_lowtype = unit

noextract let ymodem_empty_mid = unit

let ymodem_empty_vmatch = (LPS.eq_as_slprop unit)

noextract let ymodem_empty_conv = (PPB.leaf_conv unit)

val read_ymodem_empty : PPB.copyful_parse ymodem_empty_vmatch ymodem_empty_parser ymodem_empty_conv

val free_ymodem_empty : PPB.free_t ymodem_empty_vmatch

val write_ymodem_empty : PPB.l2r_safe_writer ymodem_empty_vmatch ymodem_empty_serializer ymodem_empty_conv

val ymodem_empty_bytesize_eqn (x: ymodem_empty) : Lemma (ymodem_empty_bytesize x == 0) [SMTPat (ymodem_empty_bytesize x)]

