module YModem.Wire.Generated.Ymodem_message

friend YModem.Wire.Generated.Ymodem_tag

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LT = LowParse.TacLib
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBY = LowParse.PulseParse.Bytes
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPVCL = LowParse.PulseParse.VCList
module PPDER = LowParse.Pulse.DER
module PPVD = LowParse.PulseParse.VLData
module PPLS = LowParse.PulseParse.List
module PPAR = LowParse.PulseParse.Array
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse

open YModem.Wire.Generated.Ymodem_tag
open YModem.Wire.Generated.Ymodem_soh_body
open YModem.Wire.Generated.Ymodem_empty

#reset-options "--using_facts_from '* -FStar.Tactics -FStar.Reflection -Pulse -PulseCore' --z3rlimit 16 --z3cliopt smt.arith.nl=false --max_fuel 2 --max_ifuel 2"

// Need high Z3 limits for large sum types
#set-options "--z3rlimit 360"

inline_for_extraction let key_of_ymodem_message (x:ymodem_message) : LP.enum_key ymodem_tag_enum =
  match x with
  | Body_soh _ -> ymodem_tag_as_enum_key Soh
  | Body_eot _ -> ymodem_tag_as_enum_key Eot
  | Body_ack _ -> ymodem_tag_as_enum_key Ack
  | Body_nak _ -> ymodem_tag_as_enum_key Nak
  | Body_can _ -> ymodem_tag_as_enum_key Can
  | Body_crc_c _ -> ymodem_tag_as_enum_key Crc_c

inline_for_extraction let ymodem_message_case_of_ymodem_tag (x:ymodem_tag) : Type0 =
  match x with
  | Soh -> ymodem_soh_body
  | Eot -> ymodem_empty
  | Ack -> ymodem_empty
  | Nak -> ymodem_empty
  | Can -> ymodem_empty
  | Crc_c -> ymodem_empty

unfold inline_for_extraction let to_ymodem_message_case_of_ymodem_tag (x:ymodem_tag) (#x':ymodem_tag) (y:ymodem_message_case_of_ymodem_tag x')  : Pure (norm [delta_only [(`%ymodem_message_case_of_ymodem_tag)]; iota] (ymodem_message_case_of_ymodem_tag x))
  (requires (x == x')) (ensures (fun y' -> y' == y)) =
  [@inline_let] let _ = norm_spec [delta_only [(`%ymodem_message_case_of_ymodem_tag)] ; iota] (ymodem_message_case_of_ymodem_tag x) in y

unfold inline_for_extraction let ymodem_message_refine (k:LP.enum_key ymodem_tag_enum) (x:ymodem_message)
  : Pure (LP.refine_with_tag key_of_ymodem_message k)  (requires norm [delta; iota; zeta] (key_of_ymodem_message x) == k) (ensures (fun y -> y == x)) =
  [@inline_let] let _ = norm_spec [delta; iota; zeta] (key_of_ymodem_message x) in x

noextract inline_for_extraction let synth_ymodem_message_cases (x:LP.enum_key ymodem_tag_enum) (y:ymodem_message_case_of_ymodem_tag x)
  : LP.refine_with_tag key_of_ymodem_message x =
  match x with
  | Soh -> ymodem_message_refine x (Body_soh (to_ymodem_message_case_of_ymodem_tag Soh y))
  | Eot -> ymodem_message_refine x (Body_eot (to_ymodem_message_case_of_ymodem_tag Eot y))
  | Ack -> ymodem_message_refine x (Body_ack (to_ymodem_message_case_of_ymodem_tag Ack y))
  | Nak -> ymodem_message_refine x (Body_nak (to_ymodem_message_case_of_ymodem_tag Nak y))
  | Can -> ymodem_message_refine x (Body_can (to_ymodem_message_case_of_ymodem_tag Can y))
  | Crc_c -> ymodem_message_refine x (Body_crc_c (to_ymodem_message_case_of_ymodem_tag Crc_c y))

unfold inline_for_extraction let from_ymodem_message_case_of_ymodem_tag (#x':ymodem_tag) (x:ymodem_tag)
  (y: norm [delta_only [(`%ymodem_message_case_of_ymodem_tag)]; iota] (ymodem_message_case_of_ymodem_tag x))
  : Pure (ymodem_message_case_of_ymodem_tag x') (requires (x == x')) (ensures (fun y' -> y' == y)) =
  [@inline_let] let _ = norm_spec [delta_only [(`%ymodem_message_case_of_ymodem_tag)] ; iota] (ymodem_message_case_of_ymodem_tag x) in y

let synth_ymodem_message_cases_recip_pre (k:LP.enum_key ymodem_tag_enum)
  (x:LP.refine_with_tag key_of_ymodem_message k) : GTot bool =
  match k with
  | Soh -> Body_soh? x
  | Eot -> Body_eot? x
  | Ack -> Body_ack? x
  | Nak -> Body_nak? x
  | Can -> Body_can? x
  | Crc_c -> Body_crc_c? x

let synth_ymodem_message_cases_recip_pre_intro (k:LP.enum_key ymodem_tag_enum) (x:LP.refine_with_tag key_of_ymodem_message k)
  : Lemma (synth_ymodem_message_cases_recip_pre k x == true) =
  norm_spec [delta; iota] (synth_ymodem_message_cases_recip_pre k x)

noextract inline_for_extraction let synth_ymodem_message_cases_recip (k:LP.enum_key ymodem_tag_enum)
  (x:LP.refine_with_tag key_of_ymodem_message k) : (ymodem_message_case_of_ymodem_tag k) =
  match k with
  | Soh -> [@inline_let] let _ = synth_ymodem_message_cases_recip_pre_intro Soh x in
    (match x with Body_soh y -> (from_ymodem_message_case_of_ymodem_tag Soh y))
  | Eot -> [@inline_let] let _ = synth_ymodem_message_cases_recip_pre_intro Eot x in
    (match x with Body_eot y -> (from_ymodem_message_case_of_ymodem_tag Eot y))
  | Ack -> [@inline_let] let _ = synth_ymodem_message_cases_recip_pre_intro Ack x in
    (match x with Body_ack y -> (from_ymodem_message_case_of_ymodem_tag Ack y))
  | Nak -> [@inline_let] let _ = synth_ymodem_message_cases_recip_pre_intro Nak x in
    (match x with Body_nak y -> (from_ymodem_message_case_of_ymodem_tag Nak y))
  | Can -> [@inline_let] let _ = synth_ymodem_message_cases_recip_pre_intro Can x in
    (match x with Body_can y -> (from_ymodem_message_case_of_ymodem_tag Can y))
  | Crc_c -> [@inline_let] let _ = synth_ymodem_message_cases_recip_pre_intro Crc_c x in
    (match x with Body_crc_c y -> (from_ymodem_message_case_of_ymodem_tag Crc_c y))

inline_for_extraction noextract let ymodem_message_sum = LP.make_sum' ymodem_tag_enum key_of_ymodem_message
  ymodem_message_case_of_ymodem_tag synth_ymodem_message_cases synth_ymodem_message_cases_recip
  (_ by (LP.make_sum_synth_case_recip_synth_case_tac ()))
  (_ by (LP.synth_case_synth_case_recip_tac ()))

noextract inline_for_extraction let parse_ymodem_message_cases (x:LP.sum_key ymodem_message_sum)
  : k:LP.parser_kind & LP.parser k (ymodem_message_case_of_ymodem_tag x) =
  match x with
  | Soh -> [@inline_let] let u : (k: LP.parser_kind & LP.parser k (ymodem_message_case_of_ymodem_tag Soh)) = (| _, ymodem_soh_body_parser |) in u
  | Eot -> [@inline_let] let u : (k: LP.parser_kind & LP.parser k (ymodem_message_case_of_ymodem_tag Eot)) = (| _, ymodem_empty_parser |) in u
  | Ack -> [@inline_let] let u : (k: LP.parser_kind & LP.parser k (ymodem_message_case_of_ymodem_tag Ack)) = (| _, ymodem_empty_parser |) in u
  | Nak -> [@inline_let] let u : (k: LP.parser_kind & LP.parser k (ymodem_message_case_of_ymodem_tag Nak)) = (| _, ymodem_empty_parser |) in u
  | Can -> [@inline_let] let u : (k: LP.parser_kind & LP.parser k (ymodem_message_case_of_ymodem_tag Can)) = (| _, ymodem_empty_parser |) in u
  | Crc_c -> [@inline_let] let u : (k: LP.parser_kind & LP.parser k (ymodem_message_case_of_ymodem_tag Crc_c)) = (| _, ymodem_empty_parser |) in u
  | _ -> (| _, LP.parse_false |)

noextract let serialize_ymodem_message_cases (x:LP.sum_key ymodem_message_sum)
  : LP.serializer (dsnd (parse_ymodem_message_cases x)) =
  match x with
  | Soh -> [@inline_let] let u : LP.serializer (dsnd (parse_ymodem_message_cases Soh)) = ymodem_soh_body_serializer in u
  | Eot -> [@inline_let] let u : LP.serializer (dsnd (parse_ymodem_message_cases Eot)) = ymodem_empty_serializer in u
  | Ack -> [@inline_let] let u : LP.serializer (dsnd (parse_ymodem_message_cases Ack)) = ymodem_empty_serializer in u
  | Nak -> [@inline_let] let u : LP.serializer (dsnd (parse_ymodem_message_cases Nak)) = ymodem_empty_serializer in u
  | Can -> [@inline_let] let u : LP.serializer (dsnd (parse_ymodem_message_cases Can)) = ymodem_empty_serializer in u
  | Crc_c -> [@inline_let] let u : LP.serializer (dsnd (parse_ymodem_message_cases Crc_c)) = ymodem_empty_serializer in u
  | _ -> LP.serialize_false

inline_for_extraction noextract let validate_ymodem_message_cases (x:LP.sum_key ymodem_message_sum)
  : LPS.validator (dsnd (parse_ymodem_message_cases x)) =
  match x with
  | Soh -> [@inline_let] let u : LPS.validator (dsnd (parse_ymodem_message_cases Soh)) = ymodem_soh_body_validator in u
  | Eot -> [@inline_let] let u : LPS.validator (dsnd (parse_ymodem_message_cases Eot)) = ymodem_empty_validator in u
  | Ack -> [@inline_let] let u : LPS.validator (dsnd (parse_ymodem_message_cases Ack)) = ymodem_empty_validator in u
  | Nak -> [@inline_let] let u : LPS.validator (dsnd (parse_ymodem_message_cases Nak)) = ymodem_empty_validator in u
  | Can -> [@inline_let] let u : LPS.validator (dsnd (parse_ymodem_message_cases Can)) = ymodem_empty_validator in u
  | Crc_c -> [@inline_let] let u : LPS.validator (dsnd (parse_ymodem_message_cases Crc_c)) = ymodem_empty_validator in u
  | _ -> PPC.validate_false ()

inline_for_extraction noextract let jump_ymodem_message_cases (x:LP.sum_key ymodem_message_sum)
  : LPS.jumper (dsnd (parse_ymodem_message_cases x)) =
  match x with
  | Soh -> [@inline_let] let u : LPS.jumper (dsnd (parse_ymodem_message_cases Soh)) = ymodem_soh_body_jumper in u
  | Eot -> [@inline_let] let u : LPS.jumper (dsnd (parse_ymodem_message_cases Eot)) = ymodem_empty_jumper in u
  | Ack -> [@inline_let] let u : LPS.jumper (dsnd (parse_ymodem_message_cases Ack)) = ymodem_empty_jumper in u
  | Nak -> [@inline_let] let u : LPS.jumper (dsnd (parse_ymodem_message_cases Nak)) = ymodem_empty_jumper in u
  | Can -> [@inline_let] let u : LPS.jumper (dsnd (parse_ymodem_message_cases Can)) = ymodem_empty_jumper in u
  | Crc_c -> [@inline_let] let u : LPS.jumper (dsnd (parse_ymodem_message_cases Crc_c)) = ymodem_empty_jumper in u
  | _ -> (LPS.jump_constant_size LP.parse_false 0sz)

let ymodem_message_parser =
  assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);
  LP.parse_sum ymodem_message_sum ymodem_tag_repr_parser parse_ymodem_message_cases

let ymodem_message_serializer =
  assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);
  LP.serialize_sum ymodem_message_sum ymodem_tag_repr_serializer serialize_ymodem_message_cases

let ymodem_message_bytesize_eq x = ()

let ymodem_message_validator =
  assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);
  PPS.validate_sum ymodem_message_sum ymodem_tag_repr_validator ymodem_tag_repr_reader parse_ymodem_message_cases validate_ymodem_message_cases (_ by (LP.dep_maybe_enum_destr_t_tac ())) ()

let ymodem_message_jumper =
  assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);
  PPS.jump_sum ymodem_message_sum ymodem_tag_repr_jumper ymodem_tag_repr_reader parse_ymodem_message_cases jump_ymodem_message_cases (_ by (LP.dep_maybe_enum_destr_t_tac ())) ()

inline_for_extraction
let ymodem_message_tag_of_low (xl: ymodem_message_low) : LP.sum_key ymodem_message_sum =
  match xl with
  | Body_soh_low _ -> ymodem_tag_as_enum_key Soh
  | Body_eot_low _ -> ymodem_tag_as_enum_key Eot
  | Body_ack_low _ -> ymodem_tag_as_enum_key Ack
  | Body_nak_low _ -> ymodem_tag_as_enum_key Nak
  | Body_can_low _ -> ymodem_tag_as_enum_key Can
  | Body_crc_c_low _ -> ymodem_tag_as_enum_key Crc_c

noextract let ymodem_message_mid_of_tag (k: LP.sum_key ymodem_message_sum) : Type0 =
  match k with
  | Soh -> ymodem_soh_body_mid
  | Eot -> ymodem_empty_mid
  | Ack -> ymodem_empty_mid
  | Nak -> ymodem_empty_mid
  | Can -> ymodem_empty_mid
  | Crc_c -> ymodem_empty_mid

noextract let ymodem_message_conv_of_tag (k: LP.sum_key ymodem_message_sum) : ymodem_message_mid_of_tag k -> GTot (FStar.Pervasives.Native.option (LP.sum_type_of_tag ymodem_message_sum k)) =
  match k with
  | Soh -> ymodem_soh_body_conv
  | Eot -> ymodem_empty_conv
  | Ack -> ymodem_empty_conv
  | Nak -> ymodem_empty_conv
  | Can -> ymodem_empty_conv
  | Crc_c -> ymodem_empty_conv

let ymodem_message_casevmatch (k: LP.sum_key ymodem_message_sum) (xl: ymodem_message_low) (cm: ymodem_message_mid_of_tag k) : Pulse.Lib.Core.slprop =
  match k with
  | Soh -> (match xl with | Body_soh_low v -> ymodem_soh_body_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
  | Eot -> (match xl with | Body_eot_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
  | Ack -> (match xl with | Body_ack_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
  | Nak -> (match xl with | Body_nak_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
  | Can -> (match xl with | Body_can_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)
  | Crc_c -> (match xl with | Body_crc_c_low v -> ymodem_empty_vmatch v cm | _ -> Pulse.Lib.Core.pure False)

let ymodem_message_fg (m: PPS.sum_mid ymodem_message_sum ymodem_message_mid_of_tag) : ymodem_message_mid =
  match m with
  | (| k, cm |) ->
    (match k with
     | Soh -> Body_soh_mid cm
     | Eot -> Body_eot_mid cm
     | Ack -> Body_ack_mid cm
     | Nak -> Body_nak_mid cm
     | Can -> Body_can_mid cm
     | Crc_c -> Body_crc_c_mid cm
    )

let ymodem_message_gf (m: ymodem_message_mid) : PPS.sum_mid ymodem_message_sum ymodem_message_mid_of_tag =
  match m with
  | Body_soh_mid cm -> (| ymodem_tag_as_enum_key Soh, cm |)
  | Body_eot_mid cm -> (| ymodem_tag_as_enum_key Eot, cm |)
  | Body_ack_mid cm -> (| ymodem_tag_as_enum_key Ack, cm |)
  | Body_nak_mid cm -> (| ymodem_tag_as_enum_key Nak, cm |)
  | Body_can_mid cm -> (| ymodem_tag_as_enum_key Can, cm |)
  | Body_crc_c_mid cm -> (| ymodem_tag_as_enum_key Crc_c, cm |)

inline_for_extraction
let copyful_ymodem_message_cases (k: LP.sum_key ymodem_message_sum)
  : PPS.copyful_parse_sum_payload_t ymodem_message_sum parse_ymodem_message_cases ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag k =
  match k with
  | Soh -> PPS.copyful_parse_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Soh
      read_ymodem_soh_body Body_soh_low () ()
  | Eot -> PPS.copyful_parse_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Eot
      read_ymodem_empty Body_eot_low () ()
  | Ack -> PPS.copyful_parse_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Ack
      read_ymodem_empty Body_ack_low () ()
  | Nak -> PPS.copyful_parse_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Nak
      read_ymodem_empty Body_nak_low () ()
  | Can -> PPS.copyful_parse_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Can
      read_ymodem_empty Body_can_low () ()
  | Crc_c -> PPS.copyful_parse_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Crc_c
      read_ymodem_empty Body_crc_c_low () ()

let read_ymodem_message_sum
  : PPB.copyful_parse (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch) ymodem_message_parser (PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag) =
  PPS.copyful_parse_sum ymodem_message_sum ymodem_tag_repr_reader ymodem_tag_repr_jumper parse_ymodem_message_cases
    ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag copyful_ymodem_message_cases (_ by (LP.dep_enum_destr_tac ())) (_ by (LP.dep_maybe_enum_destr_t_tac ())) () ()

let ymodem_message_coerce_vmatch_eq (xl: ymodem_message_low) (m1: PPS.sum_mid ymodem_message_sum ymodem_message_mid_of_tag)
  : Lemma (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch xl m1 == ymodem_message_vmatch xl (ymodem_message_fg m1))
  = match m1 with
  | (| k, cm |) ->
    (match k with
     | Soh -> (match xl with
       | Body_soh_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (| Soh, cm |) == ymodem_message_vmatch (Body_soh_low vp) (ymodem_message_fg (| Soh, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_eot_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (| Soh, cm |) == ymodem_message_vmatch (Body_eot_low vp) (ymodem_message_fg (| Soh, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_ack_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (| Soh, cm |) == ymodem_message_vmatch (Body_ack_low vp) (ymodem_message_fg (| Soh, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_nak_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (| Soh, cm |) == ymodem_message_vmatch (Body_nak_low vp) (ymodem_message_fg (| Soh, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_can_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (| Soh, cm |) == ymodem_message_vmatch (Body_can_low vp) (ymodem_message_fg (| Soh, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_crc_c_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (| Soh, cm |) == ymodem_message_vmatch (Body_crc_c_low vp) (ymodem_message_fg (| Soh, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
      )
     | Eot -> (match xl with
       | Body_soh_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (| Eot, cm |) == ymodem_message_vmatch (Body_soh_low vp) (ymodem_message_fg (| Eot, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_eot_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (| Eot, cm |) == ymodem_message_vmatch (Body_eot_low vp) (ymodem_message_fg (| Eot, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_ack_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (| Eot, cm |) == ymodem_message_vmatch (Body_ack_low vp) (ymodem_message_fg (| Eot, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_nak_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (| Eot, cm |) == ymodem_message_vmatch (Body_nak_low vp) (ymodem_message_fg (| Eot, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_can_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (| Eot, cm |) == ymodem_message_vmatch (Body_can_low vp) (ymodem_message_fg (| Eot, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_crc_c_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (| Eot, cm |) == ymodem_message_vmatch (Body_crc_c_low vp) (ymodem_message_fg (| Eot, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
      )
     | Ack -> (match xl with
       | Body_soh_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (| Ack, cm |) == ymodem_message_vmatch (Body_soh_low vp) (ymodem_message_fg (| Ack, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_eot_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (| Ack, cm |) == ymodem_message_vmatch (Body_eot_low vp) (ymodem_message_fg (| Ack, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_ack_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (| Ack, cm |) == ymodem_message_vmatch (Body_ack_low vp) (ymodem_message_fg (| Ack, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_nak_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (| Ack, cm |) == ymodem_message_vmatch (Body_nak_low vp) (ymodem_message_fg (| Ack, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_can_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (| Ack, cm |) == ymodem_message_vmatch (Body_can_low vp) (ymodem_message_fg (| Ack, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_crc_c_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (| Ack, cm |) == ymodem_message_vmatch (Body_crc_c_low vp) (ymodem_message_fg (| Ack, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
      )
     | Nak -> (match xl with
       | Body_soh_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (| Nak, cm |) == ymodem_message_vmatch (Body_soh_low vp) (ymodem_message_fg (| Nak, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_eot_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (| Nak, cm |) == ymodem_message_vmatch (Body_eot_low vp) (ymodem_message_fg (| Nak, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_ack_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (| Nak, cm |) == ymodem_message_vmatch (Body_ack_low vp) (ymodem_message_fg (| Nak, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_nak_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (| Nak, cm |) == ymodem_message_vmatch (Body_nak_low vp) (ymodem_message_fg (| Nak, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_can_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (| Nak, cm |) == ymodem_message_vmatch (Body_can_low vp) (ymodem_message_fg (| Nak, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_crc_c_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (| Nak, cm |) == ymodem_message_vmatch (Body_crc_c_low vp) (ymodem_message_fg (| Nak, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
      )
     | Can -> (match xl with
       | Body_soh_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (| Can, cm |) == ymodem_message_vmatch (Body_soh_low vp) (ymodem_message_fg (| Can, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_eot_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (| Can, cm |) == ymodem_message_vmatch (Body_eot_low vp) (ymodem_message_fg (| Can, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_ack_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (| Can, cm |) == ymodem_message_vmatch (Body_ack_low vp) (ymodem_message_fg (| Can, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_nak_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (| Can, cm |) == ymodem_message_vmatch (Body_nak_low vp) (ymodem_message_fg (| Can, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_can_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (| Can, cm |) == ymodem_message_vmatch (Body_can_low vp) (ymodem_message_fg (| Can, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_crc_c_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (| Can, cm |) == ymodem_message_vmatch (Body_crc_c_low vp) (ymodem_message_fg (| Can, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
      )
     | Crc_c -> (match xl with
       | Body_soh_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (| Crc_c, cm |) == ymodem_message_vmatch (Body_soh_low vp) (ymodem_message_fg (| Crc_c, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_eot_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (| Crc_c, cm |) == ymodem_message_vmatch (Body_eot_low vp) (ymodem_message_fg (| Crc_c, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_ack_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (| Crc_c, cm |) == ymodem_message_vmatch (Body_ack_low vp) (ymodem_message_fg (| Crc_c, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_nak_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (| Crc_c, cm |) == ymodem_message_vmatch (Body_nak_low vp) (ymodem_message_fg (| Crc_c, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_can_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (| Crc_c, cm |) == ymodem_message_vmatch (Body_can_low vp) (ymodem_message_fg (| Crc_c, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
       | Body_crc_c_low vp -> assert (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (| Crc_c, cm |) == ymodem_message_vmatch (Body_crc_c_low vp) (ymodem_message_fg (| Crc_c, cm |))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
      )
    )

let ymodem_message_coerce_conv_eq (m1: PPS.sum_mid ymodem_message_sum ymodem_message_mid_of_tag)
  : Lemma (ymodem_message_conv (ymodem_message_fg m1) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag m1)
  = match m1 with
  | (| k, cm |) ->
    (match k with
     | Soh -> assert (ymodem_message_conv (ymodem_message_fg (| Soh, cm |)) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (| Soh, cm |)) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
     | Eot -> assert (ymodem_message_conv (ymodem_message_fg (| Eot, cm |)) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (| Eot, cm |)) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
     | Ack -> assert (ymodem_message_conv (ymodem_message_fg (| Ack, cm |)) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (| Ack, cm |)) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
     | Nak -> assert (ymodem_message_conv (ymodem_message_fg (| Nak, cm |)) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (| Nak, cm |)) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
     | Can -> assert (ymodem_message_conv (ymodem_message_fg (| Can, cm |)) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (| Can, cm |)) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
     | Crc_c -> assert (ymodem_message_conv (ymodem_message_fg (| Crc_c, cm |)) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (| Crc_c, cm |)) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
    )

let ymodem_message_coerce_eq ()
  : Lemma (
      (forall (xl: ymodem_message_low) (m1: PPS.sum_mid ymodem_message_sum ymodem_message_mid_of_tag) .
        PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch xl m1 == ymodem_message_vmatch xl (ymodem_message_fg m1)) /\
      (forall (m1: PPS.sum_mid ymodem_message_sum ymodem_message_mid_of_tag) .
        ymodem_message_conv (ymodem_message_fg m1) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag m1)
    )
  = FStar.Classical.forall_intro_2 ymodem_message_coerce_vmatch_eq;
    FStar.Classical.forall_intro ymodem_message_coerce_conv_eq

let read_ymodem_message : PPB.copyful_parse ymodem_message_vmatch ymodem_message_parser ymodem_message_conv =
  PPB.copyful_parse_coerce_mid read_ymodem_message_sum ymodem_message_vmatch ymodem_message_conv ymodem_message_fg (ymodem_message_coerce_eq ())

inline_for_extraction
let free_ymodem_message_cases (k: LP.sum_key ymodem_message_sum)
  : PPB.free_t (ymodem_message_casevmatch k) =
  match k with
  | Soh -> PPS.free_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch Soh
      free_ymodem_soh_body (fun xl -> match xl with | Body_soh_low v -> Some v | _ -> None) ()
  | Eot -> PPS.free_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch Eot
      free_ymodem_empty (fun xl -> match xl with | Body_eot_low v -> Some v | _ -> None) ()
  | Ack -> PPS.free_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch Ack
      free_ymodem_empty (fun xl -> match xl with | Body_ack_low v -> Some v | _ -> None) ()
  | Nak -> PPS.free_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch Nak
      free_ymodem_empty (fun xl -> match xl with | Body_nak_low v -> Some v | _ -> None) ()
  | Can -> PPS.free_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch Can
      free_ymodem_empty (fun xl -> match xl with | Body_can_low v -> Some v | _ -> None) ()
  | Crc_c -> PPS.free_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch Crc_c
      free_ymodem_empty (fun xl -> match xl with | Body_crc_c_low v -> Some v | _ -> None) ()

let free_ymodem_message_sum : PPB.free_t (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch) =
  PPS.free_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch free_ymodem_message_cases (_ by (LP.dep_enum_destr_tac ()))

let ymodem_message_free_vmatch_eq (xl: ymodem_message_low) (m: ymodem_message_mid)
  : Lemma (ymodem_message_vmatch xl m == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch xl (ymodem_message_gf m))
  = match m with
  | Body_soh_mid cm -> (match xl with
    | Body_soh_low vp -> assert (ymodem_message_vmatch (Body_soh_low vp) (Body_soh_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (ymodem_message_gf (Body_soh_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_eot_low vp -> assert (ymodem_message_vmatch (Body_eot_low vp) (Body_soh_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (ymodem_message_gf (Body_soh_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_ack_low vp -> assert (ymodem_message_vmatch (Body_ack_low vp) (Body_soh_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (ymodem_message_gf (Body_soh_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_nak_low vp -> assert (ymodem_message_vmatch (Body_nak_low vp) (Body_soh_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (ymodem_message_gf (Body_soh_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_can_low vp -> assert (ymodem_message_vmatch (Body_can_low vp) (Body_soh_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (ymodem_message_gf (Body_soh_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_crc_c_low vp -> assert (ymodem_message_vmatch (Body_crc_c_low vp) (Body_soh_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (ymodem_message_gf (Body_soh_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    )
  | Body_eot_mid cm -> (match xl with
    | Body_soh_low vp -> assert (ymodem_message_vmatch (Body_soh_low vp) (Body_eot_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (ymodem_message_gf (Body_eot_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_eot_low vp -> assert (ymodem_message_vmatch (Body_eot_low vp) (Body_eot_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (ymodem_message_gf (Body_eot_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_ack_low vp -> assert (ymodem_message_vmatch (Body_ack_low vp) (Body_eot_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (ymodem_message_gf (Body_eot_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_nak_low vp -> assert (ymodem_message_vmatch (Body_nak_low vp) (Body_eot_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (ymodem_message_gf (Body_eot_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_can_low vp -> assert (ymodem_message_vmatch (Body_can_low vp) (Body_eot_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (ymodem_message_gf (Body_eot_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_crc_c_low vp -> assert (ymodem_message_vmatch (Body_crc_c_low vp) (Body_eot_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (ymodem_message_gf (Body_eot_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    )
  | Body_ack_mid cm -> (match xl with
    | Body_soh_low vp -> assert (ymodem_message_vmatch (Body_soh_low vp) (Body_ack_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (ymodem_message_gf (Body_ack_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_eot_low vp -> assert (ymodem_message_vmatch (Body_eot_low vp) (Body_ack_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (ymodem_message_gf (Body_ack_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_ack_low vp -> assert (ymodem_message_vmatch (Body_ack_low vp) (Body_ack_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (ymodem_message_gf (Body_ack_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_nak_low vp -> assert (ymodem_message_vmatch (Body_nak_low vp) (Body_ack_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (ymodem_message_gf (Body_ack_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_can_low vp -> assert (ymodem_message_vmatch (Body_can_low vp) (Body_ack_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (ymodem_message_gf (Body_ack_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_crc_c_low vp -> assert (ymodem_message_vmatch (Body_crc_c_low vp) (Body_ack_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (ymodem_message_gf (Body_ack_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    )
  | Body_nak_mid cm -> (match xl with
    | Body_soh_low vp -> assert (ymodem_message_vmatch (Body_soh_low vp) (Body_nak_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (ymodem_message_gf (Body_nak_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_eot_low vp -> assert (ymodem_message_vmatch (Body_eot_low vp) (Body_nak_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (ymodem_message_gf (Body_nak_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_ack_low vp -> assert (ymodem_message_vmatch (Body_ack_low vp) (Body_nak_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (ymodem_message_gf (Body_nak_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_nak_low vp -> assert (ymodem_message_vmatch (Body_nak_low vp) (Body_nak_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (ymodem_message_gf (Body_nak_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_can_low vp -> assert (ymodem_message_vmatch (Body_can_low vp) (Body_nak_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (ymodem_message_gf (Body_nak_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_crc_c_low vp -> assert (ymodem_message_vmatch (Body_crc_c_low vp) (Body_nak_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (ymodem_message_gf (Body_nak_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    )
  | Body_can_mid cm -> (match xl with
    | Body_soh_low vp -> assert (ymodem_message_vmatch (Body_soh_low vp) (Body_can_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (ymodem_message_gf (Body_can_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_eot_low vp -> assert (ymodem_message_vmatch (Body_eot_low vp) (Body_can_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (ymodem_message_gf (Body_can_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_ack_low vp -> assert (ymodem_message_vmatch (Body_ack_low vp) (Body_can_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (ymodem_message_gf (Body_can_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_nak_low vp -> assert (ymodem_message_vmatch (Body_nak_low vp) (Body_can_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (ymodem_message_gf (Body_can_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_can_low vp -> assert (ymodem_message_vmatch (Body_can_low vp) (Body_can_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (ymodem_message_gf (Body_can_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_crc_c_low vp -> assert (ymodem_message_vmatch (Body_crc_c_low vp) (Body_can_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (ymodem_message_gf (Body_can_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    )
  | Body_crc_c_mid cm -> (match xl with
    | Body_soh_low vp -> assert (ymodem_message_vmatch (Body_soh_low vp) (Body_crc_c_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_soh_low vp) (ymodem_message_gf (Body_crc_c_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_eot_low vp -> assert (ymodem_message_vmatch (Body_eot_low vp) (Body_crc_c_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_eot_low vp) (ymodem_message_gf (Body_crc_c_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_ack_low vp -> assert (ymodem_message_vmatch (Body_ack_low vp) (Body_crc_c_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_ack_low vp) (ymodem_message_gf (Body_crc_c_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_nak_low vp -> assert (ymodem_message_vmatch (Body_nak_low vp) (Body_crc_c_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_nak_low vp) (ymodem_message_gf (Body_crc_c_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_can_low vp -> assert (ymodem_message_vmatch (Body_can_low vp) (Body_crc_c_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_can_low vp) (ymodem_message_gf (Body_crc_c_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    | Body_crc_c_low vp -> assert (ymodem_message_vmatch (Body_crc_c_low vp) (Body_crc_c_mid cm) == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch (Body_crc_c_low vp) (ymodem_message_gf (Body_crc_c_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops]; FStar.Tactics.trefl ())
    )

let free_ymodem_message : PPB.free_t ymodem_message_vmatch =
  PPB.free_coerce_mid free_ymodem_message_sum ymodem_message_vmatch ymodem_message_gf (FStar.Classical.forall_intro_2 ymodem_message_free_vmatch_eq)

inline_for_extraction
let write_ymodem_message_cases (k: LP.sum_key ymodem_message_sum)
  : PPS.l2r_safe_writer_sum_payload_t ymodem_message_sum parse_ymodem_message_cases serialize_ymodem_message_cases ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag k =
  match k with
  | Soh -> PPS.l2r_safe_writer_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Soh
      write_ymodem_soh_body (fun xl -> match xl with | Body_soh_low v -> Some v | _ -> None) ()
  | Eot -> PPS.l2r_safe_writer_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Eot
      write_ymodem_empty (fun xl -> match xl with | Body_eot_low v -> Some v | _ -> None) ()
  | Ack -> PPS.l2r_safe_writer_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Ack
      write_ymodem_empty (fun xl -> match xl with | Body_ack_low v -> Some v | _ -> None) ()
  | Nak -> PPS.l2r_safe_writer_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Nak
      write_ymodem_empty (fun xl -> match xl with | Body_nak_low v -> Some v | _ -> None) ()
  | Can -> PPS.l2r_safe_writer_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Can
      write_ymodem_empty (fun xl -> match xl with | Body_can_low v -> Some v | _ -> None) ()
  | Crc_c -> PPS.l2r_safe_writer_sum_case ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag Crc_c
      write_ymodem_empty (fun xl -> match xl with | Body_crc_c_low v -> Some v | _ -> None) ()

let write_ymodem_message_sum
  : PPB.l2r_safe_writer (PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch) (LP.serialize_sum ymodem_message_sum ymodem_tag_repr_serializer serialize_ymodem_message_cases) (PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag) =
  PPS.l2r_safe_writer_sum ymodem_message_sum ymodem_tag_repr_serializer write_ymodem_tag_key 1sz parse_ymodem_message_cases serialize_ymodem_message_cases
    ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch ymodem_message_conv_of_tag write_ymodem_message_cases (_ by (LP.dep_enum_destr_tac ())) ()

let ymodem_message_write_conv_eq (m: ymodem_message_mid)
  : Lemma (ymodem_message_conv m == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (ymodem_message_gf m))
  = match m with
  | Body_soh_mid cm -> assert (ymodem_message_conv (Body_soh_mid cm) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (ymodem_message_gf (Body_soh_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
  | Body_eot_mid cm -> assert (ymodem_message_conv (Body_eot_mid cm) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (ymodem_message_gf (Body_eot_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
  | Body_ack_mid cm -> assert (ymodem_message_conv (Body_ack_mid cm) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (ymodem_message_gf (Body_ack_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
  | Body_nak_mid cm -> assert (ymodem_message_conv (Body_nak_mid cm) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (ymodem_message_gf (Body_nak_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
  | Body_can_mid cm -> assert (ymodem_message_conv (Body_can_mid cm) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (ymodem_message_gf (Body_can_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())
  | Body_crc_c_mid cm -> assert (ymodem_message_conv (Body_crc_c_mid cm) == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (ymodem_message_gf (Body_crc_c_mid cm))) by (FStar.Tactics.norm [delta; iota; zeta; primops; unascribe; nbe]; FStar.Tactics.trefl ())

let ymodem_message_write_coerce_eq ()
  : Lemma (
      (forall (x: ymodem_message_low) (m2: ymodem_message_mid) . ymodem_message_vmatch x m2 == PPS.vmatch_sum ymodem_message_sum ymodem_message_low ymodem_message_tag_of_low ymodem_message_mid_of_tag ymodem_message_casevmatch x (ymodem_message_gf m2)) /\
      (forall (m2: ymodem_message_mid) . ymodem_message_conv m2 == PPS.sum_conv ymodem_message_sum ymodem_message_mid_of_tag ymodem_message_conv_of_tag (ymodem_message_gf m2))
    )
  = FStar.Classical.forall_intro_2 ymodem_message_free_vmatch_eq;
    FStar.Classical.forall_intro ymodem_message_write_conv_eq

let write_ymodem_message : PPB.l2r_safe_writer ymodem_message_vmatch ymodem_message_serializer ymodem_message_conv =
  PPB.l2r_safe_writer_coerce_mid write_ymodem_message_sum ymodem_message_vmatch ymodem_message_conv ymodem_message_gf (ymodem_message_write_coerce_eq ())

let ymodem_message_accessor_tag : PPB.accessor ymodem_message_parser ymodem_tag_parser ymodem_message_clens_tag =
  assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);
  lemma_synth_ymodem_tag_inj ();
  lemma_synth_ymodem_tag_inv ();
  PPC.accessor_ext
    (PPC.accessor_compose
      (PPS.accessor_sum_tag ymodem_message_sum ymodem_tag_repr_jumper parse_ymodem_message_cases ())
      (PPC.accessor_synth_fwd synth_ymodem_tag synth_ymodem_tag_inv)
      ()
    )
    ymodem_message_clens_tag
    ()

let ymodem_message_bytesize_eqn_soh x =
    assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);

  LP.serialize_sum_eq ymodem_message_sum ymodem_tag_repr_serializer serialize_ymodem_message_cases (Body_soh x);
  (let ln = FStar.Seq.length (LP.serialize (LP.serialize_enum_key _ ymodem_tag_repr_serializer (LP.sum_enum ymodem_message_sum)) (key_of_ymodem_message (Body_soh x))) in assert (1 <= ln /\ ln <= 1));
  (ymodem_soh_body_bytesize_eq (x))

let ymodem_message_bytesize_eqn_eot x =
    assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);

  LP.serialize_sum_eq ymodem_message_sum ymodem_tag_repr_serializer serialize_ymodem_message_cases (Body_eot x);
  (let ln = FStar.Seq.length (LP.serialize (LP.serialize_enum_key _ ymodem_tag_repr_serializer (LP.sum_enum ymodem_message_sum)) (key_of_ymodem_message (Body_eot x))) in assert (1 <= ln /\ ln <= 1));
  (ymodem_empty_bytesize_eq (x))

let ymodem_message_bytesize_eqn_ack x =
    assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);

  LP.serialize_sum_eq ymodem_message_sum ymodem_tag_repr_serializer serialize_ymodem_message_cases (Body_ack x);
  (let ln = FStar.Seq.length (LP.serialize (LP.serialize_enum_key _ ymodem_tag_repr_serializer (LP.sum_enum ymodem_message_sum)) (key_of_ymodem_message (Body_ack x))) in assert (1 <= ln /\ ln <= 1));
  (ymodem_empty_bytesize_eq (x))

let ymodem_message_bytesize_eqn_nak x =
    assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);

  LP.serialize_sum_eq ymodem_message_sum ymodem_tag_repr_serializer serialize_ymodem_message_cases (Body_nak x);
  (let ln = FStar.Seq.length (LP.serialize (LP.serialize_enum_key _ ymodem_tag_repr_serializer (LP.sum_enum ymodem_message_sum)) (key_of_ymodem_message (Body_nak x))) in assert (1 <= ln /\ ln <= 1));
  (ymodem_empty_bytesize_eq (x))

let ymodem_message_bytesize_eqn_can x =
    assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);

  LP.serialize_sum_eq ymodem_message_sum ymodem_tag_repr_serializer serialize_ymodem_message_cases (Body_can x);
  (let ln = FStar.Seq.length (LP.serialize (LP.serialize_enum_key _ ymodem_tag_repr_serializer (LP.sum_enum ymodem_message_sum)) (key_of_ymodem_message (Body_can x))) in assert (1 <= ln /\ ln <= 1));
  (ymodem_empty_bytesize_eq (x))

let ymodem_message_bytesize_eqn_crc_c x =
    assert_norm (LP.parse_sum_kind (LP.get_parser_kind ymodem_tag_repr_parser) ymodem_message_sum parse_ymodem_message_cases == ymodem_message_parser_kind);

  LP.serialize_sum_eq ymodem_message_sum ymodem_tag_repr_serializer serialize_ymodem_message_cases (Body_crc_c x);
  (let ln = FStar.Seq.length (LP.serialize (LP.serialize_enum_key _ ymodem_tag_repr_serializer (LP.sum_enum ymodem_message_sum)) (key_of_ymodem_message (Body_crc_c x))) in assert (1 <= ln /\ ln <= 1));
  (ymodem_empty_bytesize_eq (x))

let ymodem_message_accessor_soh : PPB.accessor ymodem_message_parser ymodem_soh_body_parser ymodem_message_clens_soh =
  PPC.accessor_ext
    (PPS.accessor_clens_sum_payload ymodem_message_sum ymodem_tag_repr_jumper parse_ymodem_message_cases (ymodem_tag_as_enum_key Soh) ())
    ymodem_message_clens_soh
    ()

let ymodem_message_accessor_eot : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_eot =
  PPC.accessor_ext
    (PPS.accessor_clens_sum_payload ymodem_message_sum ymodem_tag_repr_jumper parse_ymodem_message_cases (ymodem_tag_as_enum_key Eot) ())
    ymodem_message_clens_eot
    ()

let ymodem_message_accessor_ack : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_ack =
  PPC.accessor_ext
    (PPS.accessor_clens_sum_payload ymodem_message_sum ymodem_tag_repr_jumper parse_ymodem_message_cases (ymodem_tag_as_enum_key Ack) ())
    ymodem_message_clens_ack
    ()

let ymodem_message_accessor_nak : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_nak =
  PPC.accessor_ext
    (PPS.accessor_clens_sum_payload ymodem_message_sum ymodem_tag_repr_jumper parse_ymodem_message_cases (ymodem_tag_as_enum_key Nak) ())
    ymodem_message_clens_nak
    ()

let ymodem_message_accessor_can : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_can =
  PPC.accessor_ext
    (PPS.accessor_clens_sum_payload ymodem_message_sum ymodem_tag_repr_jumper parse_ymodem_message_cases (ymodem_tag_as_enum_key Can) ())
    ymodem_message_clens_can
    ()

let ymodem_message_accessor_crc_c : PPB.accessor ymodem_message_parser ymodem_empty_parser ymodem_message_clens_crc_c =
  PPC.accessor_ext
    (PPS.accessor_clens_sum_payload ymodem_message_sum ymodem_tag_repr_jumper parse_ymodem_message_cases (ymodem_tag_as_enum_key Crc_c) ())
    ymodem_message_clens_crc_c
    ()

