module YModem.Wire.Generated.Ymodem_soh_body_data

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LT = LowParse.TacLib
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPBY = LowParse.PulseParse.Bytes
module PPVD = LowParse.PulseParse.VLData
module PPAR = LowParse.PulseParse.Array
module PPVCL = LowParse.PulseParse.VCList
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPDER = LowParse.Pulse.DER
module PPLS = LowParse.PulseParse.List
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse


noextract type ymodem_soh_body_data = Seq.lseq FStar.UInt8.t 128

inline_for_extraction noextract let ymodem_soh_body_data_parser_kind = LP.strong_parser_kind 128 128 (Some LP.ParserKindMetadataTotal)

noextract val ymodem_soh_body_data_parser: LP.parser ymodem_soh_body_data_parser_kind ymodem_soh_body_data

noextract val ymodem_soh_body_data_serializer: LP.serializer ymodem_soh_body_data_parser

noextract let ymodem_soh_body_data_bytesize (x:ymodem_soh_body_data) : GTot nat = Seq.length (LP.serialize ymodem_soh_body_data_serializer x)

noextract val ymodem_soh_body_data_bytesize_eq (x:ymodem_soh_body_data) : Lemma (ymodem_soh_body_data_bytesize x == Seq.length (LP.serialize ymodem_soh_body_data_serializer x))

let ymodem_soh_body_data_validator: LPS.validator ymodem_soh_body_data_parser = LPS.validate_total_constant_size ymodem_soh_body_data_parser 128sz

let ymodem_soh_body_data_jumper: LPS.jumper ymodem_soh_body_data_parser = LPS.jump_constant_size ymodem_soh_body_data_parser 128sz

val ymodem_soh_body_data_bytesize_eqn (x: ymodem_soh_body_data) : Lemma (ymodem_soh_body_data_bytesize x == Seq.length x) [SMTPat (ymodem_soh_body_data_bytesize x)]

let ymodem_soh_body_data_lowtype = PPBY.lvec FStar.UInt8.t

noextract let ymodem_soh_body_data_mid = Seq.seq FStar.UInt8.t

let ymodem_soh_body_data_vmatch : ymodem_soh_body_data_lowtype -> ymodem_soh_body_data_mid -> Pulse.Lib.Core.slprop = LSeqB.vmatch_copy_seqbytes

noextract let ymodem_soh_body_data_conv : ymodem_soh_body_data_mid -> GTot (FStar.Pervasives.Native.option ymodem_soh_body_data) = LSeqB.seq_flbytes_conv 128

val read_ymodem_soh_body_data : PPB.copyful_parse ymodem_soh_body_data_vmatch ymodem_soh_body_data_parser ymodem_soh_body_data_conv

val free_ymodem_soh_body_data : PPB.free_t ymodem_soh_body_data_vmatch

val write_ymodem_soh_body_data : PPB.l2r_safe_writer ymodem_soh_body_data_vmatch ymodem_soh_body_data_serializer ymodem_soh_body_data_conv

val size_ymodem_soh_body_data : PPB.l2r_safe_size ymodem_soh_body_data_vmatch ymodem_soh_body_data_serializer ymodem_soh_body_data_conv

