module YModem.Wire.Generated.Ymodem_packet

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LT = LowParse.TacLib
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPBY = LowParse.PulseParse.Bytes
module PPVD = LowParse.PulseParse.VLData
module PPAR = LowParse.PulseParse.Array
module PPVCL = LowParse.PulseParse.VCList
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPDER = LowParse.Pulse.DER
module PPLS = LowParse.PulseParse.List
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse


(* Type of field data*)
include YModem.Wire.Generated.Ymodem_packet_data

noextract type ymodem_packet = {
  soh : U8.t;
  blk : U8.t;
  blk_complement : U8.t;
  data : ymodem_packet_data;
  crc : U16.t;
}

noextract type ymodem_packet' = (((U8.t & U8.t) & (U8.t & ymodem_packet_data)) & U16.t)

inline_for_extraction noextract let synth_ymodem_packet (x: ymodem_packet') : ymodem_packet =
  match x with (((soh,blk),(blk_complement,data)),crc) -> {
    soh = soh;
    blk = blk;
    blk_complement = blk_complement;
    data = data;
    crc = crc;
  }

inline_for_extraction noextract let synth_ymodem_packet_recip (x: ymodem_packet) : ymodem_packet' = (((x.soh,x.blk),(x.blk_complement,x.data)),x.crc)

inline_for_extraction noextract let ymodem_packet_parser_kind = LP.strong_parser_kind 133 133 (Some LP.ParserKindMetadataTotal)

noextract val ymodem_packet_parser: LP.parser ymodem_packet_parser_kind ymodem_packet

noextract val ymodem_packet_serializer: LP.serializer ymodem_packet_parser

noextract let ymodem_packet_bytesize (x:ymodem_packet) : GTot nat = Seq.length (LP.serialize ymodem_packet_serializer x)

noextract val ymodem_packet_bytesize_eq (x:ymodem_packet) : Lemma (ymodem_packet_bytesize x == Seq.length (LP.serialize ymodem_packet_serializer x))

let ymodem_packet_validator: LPS.validator ymodem_packet_parser = LPS.validate_total_constant_size ymodem_packet_parser 133sz

let ymodem_packet_jumper: LPS.jumper ymodem_packet_parser = LPS.jump_constant_size ymodem_packet_parser 133sz

let ymodem_packet_lowtype = (((U8.t & U8.t) & (U8.t & ymodem_packet_data_lowtype)) & U16.t)

noextract let ymodem_packet_mid = (((U8.t & U8.t) & (U8.t & ymodem_packet_data_mid)) & U16.t)

let ymodem_packet_vmatch : ymodem_packet_lowtype -> ymodem_packet_mid -> Pulse.Lib.Core.slprop = (LPC.vmatch_pair (LPC.vmatch_pair (LPC.vmatch_pair (LPS.eq_as_slprop U8.t) (LPS.eq_as_slprop U8.t)) (LPC.vmatch_pair (LPS.eq_as_slprop U8.t) ymodem_packet_data_vmatch)) (LPS.eq_as_slprop U16.t))

noextract let ymodem_packet_conv : ymodem_packet_mid -> GTot (FStar.Pervasives.Native.option ymodem_packet) = PPC.synth_conv (PPC.pair_conv (PPC.pair_conv (PPC.pair_conv (PPB.leaf_conv U8.t) (PPB.leaf_conv U8.t)) (PPC.pair_conv (PPB.leaf_conv U8.t) ymodem_packet_data_conv)) (PPB.leaf_conv U16.t)) synth_ymodem_packet

val read_ymodem_packet : PPB.copyful_parse ymodem_packet_vmatch ymodem_packet_parser ymodem_packet_conv

val free_ymodem_packet : PPB.free_t ymodem_packet_vmatch

val write_ymodem_packet : PPB.l2r_safe_writer ymodem_packet_vmatch ymodem_packet_serializer ymodem_packet_conv

val size_ymodem_packet : PPB.l2r_safe_size ymodem_packet_vmatch ymodem_packet_serializer ymodem_packet_conv

val ymodem_packet_bytesize_eqn (x: ymodem_packet) : Lemma (ymodem_packet_bytesize x == 1 + 1 + 1 + (ymodem_packet_data_bytesize (x.data)) + 2) [SMTPat (ymodem_packet_bytesize x)]

noextract let clens_ymodem_packet_soh : LowParse.CLens.clens ymodem_packet U8.t = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.soh);
}

val accessor_ymodem_packet_soh : PPB.accessor ymodem_packet_parser LPI.parse_u8 clens_ymodem_packet_soh

noextract let clens_ymodem_packet_blk : LowParse.CLens.clens ymodem_packet U8.t = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.blk);
}

val accessor_ymodem_packet_blk : PPB.accessor ymodem_packet_parser LPI.parse_u8 clens_ymodem_packet_blk

noextract let clens_ymodem_packet_blk_complement : LowParse.CLens.clens ymodem_packet U8.t = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.blk_complement);
}

val accessor_ymodem_packet_blk_complement : PPB.accessor ymodem_packet_parser LPI.parse_u8 clens_ymodem_packet_blk_complement

noextract let clens_ymodem_packet_data : LowParse.CLens.clens ymodem_packet ymodem_packet_data = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.data);
}

val accessor_ymodem_packet_data : PPB.accessor ymodem_packet_parser ymodem_packet_data_parser clens_ymodem_packet_data

noextract let clens_ymodem_packet_crc : LowParse.CLens.clens ymodem_packet U16.t = {
  LowParse.CLens.clens_cond = (fun _ -> True);
  LowParse.CLens.clens_get = (fun x -> x.crc);
}

val accessor_ymodem_packet_crc : PPB.accessor ymodem_packet_parser LPI.parse_u16 clens_ymodem_packet_crc

