module YModem.Wire.Generated.Ymodem_tag

(* This file has been automatically generated by EverParse. *)
module U8 = FStar.UInt8
module U16 = FStar.UInt16
module U32 = FStar.UInt32
module U64 = FStar.UInt64
module LP = LowParse.Spec
module LPI = LowParse.Spec.AllIntegers
module L = FStar.List.Tot
module LPS = LowParse.Pulse.Base
module LT = LowParse.TacLib
module PPB = LowParse.PulseParse.Base
module PPC = LowParse.PulseParse.Combinators
module PPBY = LowParse.PulseParse.Bytes
module PPVD = LowParse.PulseParse.VLData
module PPAR = LowParse.PulseParse.Array
module PPVCL = LowParse.PulseParse.VCList
module LPC = LowParse.Pulse.Combinators
module LPPI = LowParse.Pulse.Int
module LPPILE = LowParse.Pulse.BoundedIntLE
module PPE = LowParse.PulseParse.Enum
module PPS = LowParse.PulseParse.Sum
module PPBI = LowParse.PulseParse.BoundedInt
module PPBILE = LowParse.PulseParse.BoundedIntLE
module PPBCVLI = LowParse.PulseParse.BCVLI
module PPVG = LowParse.PulseParse.VLGen
module PPDER = LowParse.Pulse.DER
module PPLS = LowParse.PulseParse.List
module PPFD = LowParse.PulseParse.FLData
module LPPS = LowParse.Pulse.Sum
module PPSL = LowParse.PulseParse.SizeLeaf
module LSeqB = LowParse.Pulse.SeqBytes
module LPITE = LowParse.PulseParse.IfThenElse


type ymodem_tag =
  | Soh
  | Eot
  | Ack
  | Nak
  | Can
  | Crc_c

let string_of_ymodem_tag = function
  | Soh -> "soh"
  | Eot -> "eot"
  | Ack -> "ack"
  | Nak -> "nak"
  | Can -> "can"
  | Crc_c -> "crc_c"

[@LT.Norm] inline_for_extraction noextract let ymodem_tag_enum : LP.enum ymodem_tag U8.t =
  [@inline_let] let e = [
    Soh, 1z;
    Eot, 4z;
    Ack, 6z;
    Nak, 21z;
    Can, 24z;
    Crc_c, 67z;
  ] in
  [@inline_let] let _ =
    assert_norm (L.noRepeats (LP.list_map fst e))
  in
  [@inline_let] let _ = 
    assert_norm (L.noRepeats (LP.list_map snd e))
  in e

inline_for_extraction noextract let ymodem_tag_parser_kind = LP.strong_parser_kind 1 1 None

noextract val ymodem_tag_parser: LP.parser ymodem_tag_parser_kind ymodem_tag

noextract val ymodem_tag_serializer: LP.serializer ymodem_tag_parser

noextract let ymodem_tag_bytesize (x:ymodem_tag) : GTot nat = Seq.length (LP.serialize ymodem_tag_serializer x)

noextract val ymodem_tag_bytesize_eq (x:ymodem_tag) : Lemma (ymodem_tag_bytesize x == Seq.length (LP.serialize ymodem_tag_serializer x))

val ymodem_tag_validator: LPS.validator ymodem_tag_parser

let ymodem_tag_jumper: LPS.jumper ymodem_tag_parser = LPS.jump_constant_size ymodem_tag_parser 1sz

val ymodem_tag_reader: PPB.leaf_reader ymodem_tag_parser

val ymodem_tag_writer: LPS.l2r_leaf_writer ymodem_tag_serializer

val ymodem_tag_leaf_size: LPS.leaf_size ymodem_tag_serializer

let ymodem_tag_lowtype = ymodem_tag

noextract let ymodem_tag_mid = ymodem_tag

let ymodem_tag_vmatch : ymodem_tag_lowtype -> ymodem_tag_mid -> Pulse.Lib.Core.slprop = LPS.eq_as_slprop ymodem_tag

noextract let ymodem_tag_conv : ymodem_tag_mid -> GTot (FStar.Pervasives.Native.option ymodem_tag) = fun x -> FStar.Pervasives.Native.Some x

val read_ymodem_tag : PPB.copyful_parse ymodem_tag_vmatch ymodem_tag_parser ymodem_tag_conv

val free_ymodem_tag : PPB.free_t ymodem_tag_vmatch

val write_ymodem_tag : PPB.l2r_safe_writer ymodem_tag_vmatch ymodem_tag_serializer ymodem_tag_conv

val size_ymodem_tag : PPB.l2r_safe_size ymodem_tag_vmatch ymodem_tag_serializer ymodem_tag_conv

